### ISSUE TITLE
FreeREG campaign / Newsletter

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#10]

**Comment by DeniseColbert** [comment]
Ready for final check and authorisation to send

**Comment by Captainkirkdawson** [comment]
Where  would  one see the document

**Comment by DeniseColbert** [comment]
It's currently in Mailchimp- if you are signed up to our mailing list (you can do this via the FreeUKGen homepage) you'll get it when it goes out. If you'd like to see it before I send it though, I can forward a [Test] to you?
