### ISSUE TITLE
Navigation bar broken on FUG site

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1010]
![image](https://user-images.githubusercontent.com/19173257/48774339-dae3b700-ecc1-11e8-90c7-d1cb8dd4fc06.png)

But should look like this:

![image](https://user-images.githubusercontent.com/19173257/48774468-49287980-ecc2-11e8-81af-bc2962d7395e.png)

**Comment by arswright-alt-uk** [comment]
Now tracked at [FreeUKGen/FreeUKGenealogy Issue #10](https://github.com/FreeUKGen/FreeUKGenealogy/issues/10).
