### ISSUE TITLE
Create Christmas Cards

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1022]

**Comment by DeniseColbert** [comment]
A selection of designs: https://docs.google.com/drawings/d/1zcKPpmL25ClbvyuLH-qtCH7CBPNF0M6ht3hnzEFZhRc/edit

**Comment by DeniseColbert** [comment]
Exploring Kindlink project for this, see https://www.freeukgenealogy.org.uk/admin/entries/pages/2503-christmas-ecard

**Comment by PatReynolds** [comment]
all looking good!  Are the images of the cards going to be on our web page?

**Comment by DeniseColbert** [comment]
Yes, will add low-res thumbnails

**Comment by DeniseColbert** [comment]
Images added. Can you check Pat? 

Wondering about automating the sending of the eCard pack; possibly have it in the Thank You email send via KindLink upon donation? If we can't attach it to the email, maybe we could send the link to the pack on the website. (This would be a PDF with links to eCards in different formats)

**Comment by PatReynolds** [comment]
"An image to send that explaining the eCard to the recipient" should be 'explains'?

Image - does image have an alt text? [is that even a possible thing???]

**Comment by DeniseColbert** [comment]
Sorted top 2 points (alt-text is possible)

Auto-respond not possible (see email with Adriano 28/11) so I may create the email (with links) in Flash Issue and ask Helen to send (with a How-To video)
