### ISSUE TITLE
Create new Test Environment

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#104]
Needed for FreeREG and FreeCEN2, possibly also FreeBMD2. See also conversation on Docker

**Comment by richpomfret** [comment]
Lemon has now replied with a list of options - which include solutions across projects (this is a wider issue to discuss with Kirk/Eric and Ben/Doug)

**Comment by richpomfret** [comment]
To discuss this (and CMS) at a TASc meeting in order to tackle bottlenecks for this - possibly on 13th.

**Comment by PatReynolds** [comment]
Start Friday 12th complete Monday 15th.

**Comment by richpomfret** [comment]
Put TASc on hold for this week, as progress was made after reviewing past threads with Barrie. He looked again at Cloud9 and also investigating Docker (community) and iocage for setting up jails. Still to define how we keep live db synced with staging and development. Vino will assist in setting up the new dev/staging workflow.

**Comment by PatReynolds** [comment]
If not possible via AWS or preferable to use Hetzner, I have permission to buy on Hetzner rather than use AWS grant

**Comment by richpomfret** [comment]
Lemon has a preference for using AWS for our offsite backup/storage with possibility of open data in future. Costs are not sufficiently cheaper when compared to our current servers. We are therefore going ahead on the non-AWS option.

**Comment by richpomfret** [comment]
Have chased Lemon/Barrie for an update on this.

**Comment by richpomfret** [comment]
Currently awaiting a further update.

**Comment by richpomfret** [comment]
Looks like we're almost there! HURRAH. Now checking in to see when we can get Scott set-up.

**Comment by richpomfret** [comment]
Bit premature - a few teething problems (according to Barrie), but it is getting there. Hopefully have this set up before the FreeBMD event.

**Comment by richpomfret** [comment]
Moving this to done. Shall create new task for getting Scott set-up. :)
