### ISSUE TITLE
Investigte Tech for Better

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1049]
see https://www.foundersandcoders.com/techforbetter

E2 U3 S5 C8: P18

**Comment by richpomfret** [comment]
Investigated and contacted. There might be scope for a collaboration here as part of their coding bootcamp programme - particularly if we try and do the impossible and find a way to make genealogy more enticing, interesting and easily accessible for a younger generation!

**Comment by richpomfret** [comment]
Shall add this over on New Projects and we can discuss it there. Closing.
