### ISSUE TITLE
Reports for Trustees due 11 Jan

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1055]

**Comment by DeniseColbert** [comment]
My part is done, bar adding link to Gray's document and removing a sentence - unless there's anything else you think should be in there, Pat?

**Comment by PatReynolds** [comment]
Gret, thank you.

**Comment by arswright-alt-uk** [comment]
@PatReynolds Recommendation available (w/updates to reflect feedback) here: https://docs.google.com/document/d/1Qz19U17PsoD3h3Cs9DoHn65Rht54I6cH4jzNRV0HQ4o/edit?usp=sharing

**Comment by PatReynolds** [comment]
Thank you very much, @arswright-alt-uk  - one typo: " volunteers with have" needs changing to "volunteers will have".

Can you make the document so those with the link can comment?  That way you will be able to see/track/respond to anything a Trustee notes in the document.

**Comment by arswright-alt-uk** [comment]
@PatReynolds Fixed up and comments enabled; 02:20 here so I'm signing off for ~8hrs.
