### ISSUE TITLE
Arrange to attend event replacing WDYTYA Live (replacement event)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#106]
6 - 8 April 2017, NEC Birmingham

**Comment by DeniseColbert** [comment]
Enquired by email 07/10/16

**Comment by DeniseColbert** [comment]
Reply: Firstly, please accept my apologies for the delay in getting back to you. Free UK Genealogy is a perfect fit for the show, particularly with the top three areas of interest being births, deaths and marriages!

WDYTYA? Live will be taking place from 6-8th April 2017 at the NEC in Birmingham. This will be our 11th show and we’re going strong! We’re expecting around 13,500 visitors. 

 Our stands are priced at £200 per square metre with the minimum size being 2m by 2m (£800). I can see that you are a charity so you will be exempt from paying any VAT.

I have attached a floor plan so you can see the layout and the variety of stands available. Please do let me know if you want me to check availability for you; we’re about 65% booked at the moment. 

We release a manual in December with details of all the ‘extras’ such as electricity, internet access, furniture etc. and how to order. 

https://drive.google.com/a/freeukgenealogy.org.uk/file/d/0B9QXkJ8S6kJnWU56LWp6MnZzTjRrODhJMERMU0tfMF9GUk04/view?usp=sharing

Floor Plan ^^

**Comment by PatReynolds** [comment]
Is there a guide we could advertise in?

**Comment by DeniseColbert** [comment]
Advertising in the show guide is £500 full page, £250 half page. 

However... "The cost for a table is £205 (for the full three days). You get a 6ft table and chair included in the price as well as a basic listing in our show guide."

Is this manageable @PatReynolds ?

**Comment by PatReynolds** [comment]
Please cost hotel, etc @denise.colbert

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by DeniseColbert** [comment]
This is a search for within  1  mile of NEC  in ascending price order: https://uk.hotels.com/search.do?resolved-location=CITY%3A554288%3AUNKNOWN%3AUNKNOWN&f-distance=1.0&f-lid=1652581&destination-id=554288&q-destination=Birmingham,%20England,%20United%20Kingdom&q-check-in=2017-04-06&q-check-out=2017-04-08&q-rooms=1&q-room-0-adults=1&q-room-0-children=0&sort-order=PRICE

**Comment by DeniseColbert** [comment]
Train tickets for me: https://www.dropbox.com/s/vv7dt8uditnuwni/Screenshot%202016-12-28%2017.13.48.png?dl=0

**Comment by PatReynolds** [comment]
Pat to review

**Comment by PatReynolds** [comment]
Delay until next year - until we are in a position to do mass-sign-ups

**Comment by DeniseColbert** [comment]
http://thefamilyhistoryshow.com/london/   Esher, Surrey. Tickets ~ £5

Possibly combine with physical meeting

Another possibility: http://thefamilyhistoryshow.com/york/

**Comment by PatReynolds** [comment]
@patreynolds to check SoG as an organizer

**Comment by DeniseColbert** [comment]
Another possible: http://thenameevent.com/

**Comment by DeniseColbert** [comment]
This is interesting...

http://secretlives.org.uk/ 

Event in Ag/Sept '18 with Nick Barratt (amongst others) speaking. The buy Tickets button takes you to the SoG website...

**Comment by PatReynolds** [comment]
Closing as overtaken by #724
