### ISSUE TITLE
Create style guide for FUG brand

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1067]
e.g. http://www.roguefitness.com/media/styleguide/RogueFitness-brand-standards-manual.pdf

**Comment by arswright-alt-uk** [comment]
@DeniseColbert For clarification, how does this issue differ from Issue #992 ..?

**Comment by DeniseColbert** [comment]
It doesn't! #992 didn't show when I searched earlier. Will close that one.

**Comment by DeniseColbert** [comment]
@PatReynolds to review clarifications on this document: https://docs.google.com/document/d/1vysu4iTMD7Yw0PQgM-a_EFLXJMT0cmMFzDrJo3KytA8/edit?usp=sharing

**Comment by PatReynolds** [comment]
I've commented on what I think was waiting for my commeents, @DeniseColbert

**Comment by PatReynolds** [comment]
Use  >ss pro > helvetica 

Also look to see what comes bundled with Windows and Mac, and see if they have anything in common which is in 'our style' which we could use.

**Comment by DeniseColbert** [comment]
Final tweaks sent to Katy 02/02/21
