### ISSUE TITLE
Consitution missing from FUG website

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1079]
Possibly been moved and link not updated?

**Comment by DeniseColbert** [comment]
@PatReynolds This is strange... when I navigate to it in Assets it's there:

![image](https://user-images.githubusercontent.com/19173257/52071140-48da1380-257a-11e9-8446-68bfd6df367a.png)

The only difference in the 2 urls is the slash at the end- have removed from link and now works.

**Comment by PatReynolds** [comment]
There  now, thank you, so closing.
