### ISSUE TITLE
Arthur bird blog post

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1085]

**Comment by DeniseColbert** [comment]
Problem with adding image to Craft, but draft made. (emailed @arswright-alt-uk and @smrr723 about image problem)

**Comment by arswright-alt-uk** [comment]
@DeniseColbert Per email reply, I'd recommend saving the PNG file as a JPG file and re-uploading (unable to determine root cause of PNG upload failure at this time).
