### ISSUE TITLE
Add Insta & Pinterest icons to email signatures

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1088]
Create documentation to inform staff how to do this.

**Comment by DeniseColbert** [comment]
Easyfundraising added and Instruction doc shared w/ @PatReynolds 29/11/19

HOWEVER... Do we want to replace easyfundraising with FUG Donate CTA?

**Comment by PatReynolds** [comment]
Where are the images, please?  And yes, FUG donate CTA.

**Comment by DeniseColbert** [comment]
Images are linked on the document - G Drive links below each thumbnail

**Comment by PatReynolds** [comment]
Can you provide the path to the images, please, I can't find them.
