### ISSUE TITLE
Email FC Coords about 'making' new Coords / Proofreaders / Validators

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1089]
Per discussion with Brenda, ask coords if they have any helpers local to them who might be interested in taking on one census year in a county (one of Brenda's) OR interested in helping out with Brenda's proofreading/validating workload. The coord would meet up with them to explain the role/show the ropes.

Needed by #59

**Comment by DeniseColbert** [comment]
Draft sent 10/4 to Pat

**Comment by PatReynolds** [comment]
It's an view only' but not a lot to comment on.
Second paragraph " to equip their transcribers"  maybe use the word Helpers, - or  change the  Helper earlier in the pass age to Transcriber? 
Maybe add to the first paragraph 'We are getting new transcribers signing up - and have plenty for them to transcribe now.'?

**Comment by DeniseColbert** [comment]
Made those changes, and added: "Alternatively, you may not be able to physically meet with them due to distance etc. but could ‘meet’ via Skype, Google Meet/Hangouts (or similar), and I would be happy to help with this as needed." to paragraph 3.

Let me know if you're happy for me to send this to Brenda.

**Comment by DeniseColbert** [comment]
... also added 

"Equally, if you have any other ideas on how we can go about increasing the number of FreeCEN Coordinators, we would love to hear them."

to the CTA to get in touch.

**Comment by PatReynolds** [comment]
Great - good to go.  I will try and get the 'information for coords' ready for Alison to proof in this week, as it will be helpful.

**Comment by DeniseColbert** [comment]
Sent to Brenda for her feedback on 9/7

**Comment by DeniseColbert** [comment]
@PatReynolds - Brenda has offered to host a group - have added as much to the doc, with a comment.
