### ISSUE TITLE
Decide what to do with GoCardless

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1103]
Only online system left with no on-site GiftAid reclaim/select.  

**Best:** Move to Kindlink (if they do a direct debit)?

**Next best:** Move to the pathway for cheques/bank transfers? (landing page after setting up on goCardless is the Giftaid page)?

**Worst:**  Or maintain two buttons?

**Comment by DeniseColbert** [comment]
Does PayPal giving allow regular donations by DD? If we're looking to streamline our pathways, this could replace GC.

**Comment by DeniseColbert** [comment]
Kindlink does offer monthly donations, Adriano said by card so not sure if this counts as Direct Debit. 

![image](https://user-images.githubusercontent.com/19173257/57294801-ad989300-70c0-11e9-893e-4f0704472552.png)

**Comment by DeniseColbert** [comment]
No, it's not a direct debit - they are recurring card payments. 
​
​Recurring card payments – A recurring card payment, also known as a ‘Continuous Payment Authority’ (CPA) is an authorisation provided by the customer that allows you, as the merchant, to take regular payments from the customer’s debit or credit card. Not all customers are happy to set up a direct debit, so this allows you to take payments that vary in frequency and amount. It will remain in place until the customer cancels the arrangement.

Direct Debit – A Direct Debit is very similar to the process described above. However, in this case, the customer must authorise the merchant to take money from their account by giving you a mandate to do so. You can then collect regular, recurring payments, payments with varying dates and amounts, and one-off collections. One of the key differences between the two payment types is that a Direct Debit is paid directly from the customer’s bank account, so customers must sign up to the Direct Debit using their bank account and sort code.

**Comment by DeniseColbert** [comment]
https://queerideas.co.uk/2019/02/we-have-reached-peak-regular-giving-so-what-next.html

PayPal **do** offer RG by DD. However, you must have a PayPal account.

**Comment by PatReynolds** [comment]
How many are giftaiding? Streamline to no-giftaid? Can they be routed to Thank you page?  If not we could write and ask (small volume of people sign up anyway).
Pat to write to current users, Denise to put in newsletter as a poll.

**Comment by PatReynolds** [comment]
Emailed all current users 13/8/2019

**Comment by PatReynolds** [comment]
Consultation only brought one response, but GC is much liked by that respondent (I think it's used by quite a lot of organisations.

We might want to use GoCardless for the Patrons scheme (if Kindlink isn't as good).  Some people don't like auto card payment as it can be harder to cancel than DD.

therefore decision is to retain. Would need to set up new versions with a redirect to Giftaid / back to projects page.

**Comment by PatReynolds** [comment]
New buttons made with redirect to giftaid.
Applied to take US$.

New plans
£2 https://pay.gocardless.com/AL0002WWQ8PCX8
£5 https://pay.gocardless.com/AL0002WWQA86AZ
£10 https://pay.gocardless.com/AL0002WWQDP6DJ
£20 https://pay.gocardless.com/AL0002WWPZD382
£50 https://pay.gocardless.com/AL0002WWQ3EG05

Draft 5 has these new buttons.

**Comment by PatReynolds** [comment]
Go Cardless links now all for with or without Giftaid, with re-route to the giftaid form thank you page.

**Comment by PatReynolds** [comment]
GoCardless page now ready for proofing.
Nb daughter pages for giftaid / no giftaid no longer needed.

Realise we don't use the Giftaid Logo which would be nice here and elsewhere, so opened a new story.  Need not hold this one up.

**Comment by DeniseColbert** [comment]
New page published so closing.
