### ISSUE TITLE
April Trustee Meeting Agenda (for 23 March)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1106]
Additional items - Transcription Agreement.
Conference.

**Comment by PatReynolds** [comment]
Can you proof and send out, please.

**Comment by DeniseColbert** [comment]
Proofed; will send out when comment resolved

**Comment by PatReynolds** [comment]
Comment resolved

**Comment by DeniseColbert** [comment]
Sent 4/4
