### ISSUE TITLE
Find replacement for Waffle.io

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1111]

**Comment by Captainkirkdawson** [comment]
Options are likely Github-projects, jira, huboard, zenhub, zube, trello.

I would reject  
Github-projects as missing too many features
huboard as missing too many features and low take up
Jira as far too heavy
trello as too light weight and lakes effective integration with github
zube as lacking in features and low take up
Zenhub has most of what we needs and a solid take up

**Comment by richpomfret** [comment]
Currently investigating 2 most likely candidates - Zenhub and Trello.
