### ISSUE TITLE
GitHub: Create FreeUKGen/FreeUKGenealogyWP

### ISSUE THREAD

**Issue by arswright-alt-uk** [FreeUKGen/Coordination#1115]
I do not have sufficient permissions to create empty repo to initialize WordPress migration work.

Requesting empty repo + permissions for working with repo at GitHub.

**Comment by richpomfret** [comment]
Created the repo for you and you shold have an invite email to it.

**Comment by arswright-alt-uk** [comment]
Access confirmed, closing issue.
