### ISSUE TITLE
Review/establish next GA tasks

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/Coordination#1118]
Working with data science/GA volunteer to progress our reporting in relation to tracking acquisition/retention and engagement across our sites

**Comment by richpomfret** [comment]
Review tasks David has added to Waffle (FC). Also establish best place to add or move these tasks (if necessary).

**Comment by DeniseColbert** [comment]
Emailed David 02/04 re. weekly Meets alternating Rich/me. Awaiting reply and will then set up.
Touched on the need to put stories in the right place and with enough info; whoever meets him next can expand on this.

@richpomfret  is there a good resource out there for best practice for writing issues? I think this would be a great addition to our onboarding documentation.

**Comment by DeniseColbert** [comment]
Met with David today, he's going to proceed with creating 'no bots' views for all projects (FR was the only one that had this), and continue with setting up the reports you've asked for.

**Comment by DeniseColbert** [comment]
Unassigning myself as on leave next 2 weeks.

**Comment by PatReynolds** [comment]
@rich to check user number stats on FreeREG

**Comment by richpomfret** [comment]
Current discussions on working out the best approach for Google Tag Manager alongside Analytics - particularly IF it can be helpful for simplifying our cookie collection/consent and tracking. Considerng this specific high level story now closed and covered by more specific GA and GTM tasks.
