### ISSUE TITLE
Set up Technical Architecture Subcom

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#113]
TMP to be part / liaison.

**Comment by richpomfret** [comment]
Emails sent out to executives (Ben Laurie has expressed an interest) and shall email rest of dev team to see who wishes to be part of this (Kirk already expressed an interest). Next steps include setting out basic roadmap, outlining key responsibilities and decision-making processes for TAS.

**Comment by richpomfret** [comment]
This is now complete - now to set up TASc email group/alias (will add new story), remind those who expressed an interest and aim to set up the first meeting for the end of this month.
