### ISSUE TITLE
Change My Donate links to Kindlink (May) and further update (June)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1135]

**Comment by DeniseColbert** [comment]
Replaced MyDonate with Kindlink here: https://www.freeukgenealogy.org.uk/admin/entries/pages/1822-how-to-donate/drafts/126

Please check.

**Comment by PatReynolds** [comment]
Pat to test draft.

**Comment by PatReynolds** [comment]
Done.

I have also (in draft2) added "Debit and Credit" before 'Card' for clarity.  I'll make further changes once I have finished the paypal giving set-up, as the Paypal text and the link will need changing.

**Comment by PatReynolds** [comment]
Updated draft 2 - for @DeniseColbert to proof/check and make live.

**Comment by DeniseColbert** [comment]
Done
