### ISSUE TITLE
GA Reduce Cardinality of Page Identification

### ISSUE THREAD

**Issue by dhousman** [FreeUKGen/Coordination#1138]
I noticed an issue with the way GA was processing query parameters. Currently google is incorporating query parameters in the way it identifies pages. For example, Google thinks that the page "freereg.org.uk/" is different from "freereg.org.uk/?locale-en". This is increasing the number of unique pages that google thinks its seeing. Due to this, pages are being counted in the "(other)" bucket (this is actually the most frequented page on your site by a large margin. I think that we need to configure google to ignore query parameters like "locale", "source", "option". This will reduce uniqueness and make the data easier to look at. I believe that I can handle this through configuration. 

Another similar issue is in the path for the "search_queries" page. Currently google is counting this page: "/search_queries/5c8c2afe33045b540f2c58d1?locale=en" as a different page from this one: "/search_queries/5c8702af4325a69cda351c88?locale=en" Is there a reason behind that level of specificity? If not, i would recommend truncating that to bucket search pages together. I believe this is also something that I can do through configuration. I'm seeing similar issues on FreeCEN2 and FreeBMD

**Comment by DeniseColbert** [comment]
@richpomfret can't find dhousman in the assigning list, do we need to re-add him to the team?
