### ISSUE TITLE
Promote Pelagios Grant

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1146]
Publicise in newsletter and social media
Pat to write to International Geneological Standards folk
Pat to draft paragraph for newsletter

**Comment by PatReynolds** [comment]
Waiting for Pelagios blog post to go live before amending our news post with a link.
Writing to FHISO also waiting for Pelagios' blog post.

**Comment by PatReynolds** [comment]
First draft completed - over to you @DeniseColbert

**Comment by DeniseColbert** [comment]
Made live and put on Social 29/11/19
