### ISSUE TITLE
approach Speakers for Conference

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1150]

**Comment by PatReynolds** [comment]
Contcted O D-W 15/5

**Comment by DeniseColbert** [comment]
@PatReynolds to follow up HB, and Brenda re. Yorks Coord

**Comment by PatReynolds** [comment]
Checked 9/7/19

**Comment by PatReynolds** [comment]
Pat to think about potential speakers

**Comment by PatReynolds** [comment]
The person I was thinking of turns out not to be using our data for his research.

Approach anyway, and also Coords list.
