### ISSUE TITLE
Investigate whether NowDonate is too good to be true

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1170]
https://www.nowdonate.com/why-choose-us

Compare capacity of both systems to thank donors.

Check what they mean by 'international currencies'

Chekc if they can automate sending out an update X months after donation

**Comment by DeniseColbert** [comment]
I signed up so we could do a reccy: info@ email address, will ping you password.

Note adding payment providers in dashboard; this is where charges come in. Can add PayPal and Go Cardless, as well as others we don't already use.

**Comment by PatReynolds** [comment]
@PatReynolds to look at import capabilities and check if it is good for all (except maybe Paypal?)
