### ISSUE TITLE
Actions after the Genealogy Show

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1188]
Pat - claim expenses from GenShow - DONE
Pat - submit expenses to FUG - DONE
Pat - contact Fed of F H S - DONE
Pat - contact MoD - DONE
Pat - contact Gen Show re talk - DONE
Pat - revise talk for publication and distribute -DONE
Pat - discover if the parish-from-the-page number on FreeBMD is really a thing (yes, it is, sub-district from a page): need new story on FreeBMD2 to consider the implementation of a s-d from a page feature) - DONE
Pat - briefing note for Trustees - DONE
Denise - contact Myrtle - DONE
Denise - submit expenses to FUG - DONE

**Comment by PatReynolds** [comment]
@Denise could you check/proof the slides - they are in Presentations, a google slides and ppt version.

**Comment by DeniseColbert** [comment]
@PatReynolds are the two versions the same (I don't have powerpoint so can I proof the Google slides version and that will do the job)?

**Comment by DeniseColbert** [comment]
Google slides version proofed
