### ISSUE TITLE
Celebrate Open Data Day 2021

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1192]
Take down a brick wall!  Challenge our volunteers to find find your 'missing link' using social media with a hashtag #brickwallODD 

Fundraise for and appoint Intern for this project.

Update for 2021: use twitter - @DeniseColbert  to make contact with person who ran stream last year.
and contact ODD re funding longer term.

Update for 2022: - create a dedicated ODD Brick Wall Facebook group

**Comment by DeniseColbert** [comment]
Brick wall form completed with everything I know about individual also consent to share info from unanswered questions on social media

Groups.io forum

**Comment by PatReynolds** [comment]
@DeniseColbert to approach those who took up the ODD challenge last year to suggest we publicise this year and they answer, prioritising using Open Data sites to answer the queries
