### ISSUE TITLE
Recruit additional trustees

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#12]
Recruit additional Trustees (max 9) consistent with identified skill gaps

**Comment by DeniseColbert** [comment]
https://www.ncvo.org.uk/practical-support/governance/trustee-bank

**Comment by PatReynolds** [comment]
2 Candidates sent to Camilla 3/1/2017

**Comment by PatReynolds** [comment]
Contact and update candidates

**Comment by PatReynolds** [comment]
2 candidates sent to Richard 7/2/2017 @DeniseColbert to recruit Trustee / AB member with financial expertise

**Comment by PatReynolds** [comment]
Please proof Draft#1 @DeniseColbert

**Comment by PatReynolds** [comment]
Applicants all contacted 17/2
