### ISSUE TITLE
Webpage on different records to transcribe

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1201]
https://www.freeukgenealogy.org.uk/admin/entries/pages/2793-which-project. @PatReynolds please proof and suggest improvements before I seek the same from Allan, Brenda and Steve.

**Comment by PatReynolds** [comment]
I'd describe the management teams as "of experienced volunteers".

Maybe put an image in of each?

Mention choice of county on FreeREG and FreeCEN?
