### ISSUE TITLE
Recruit paths and search features intern

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#121]
Repeat #457 on FreeREG (with correct choices); #256 on FreeREG; Issue 52 on FreeCEN; finally issue #802 on FreeREG (if there is time)
Folder /projects/Intern refers to work undertaken, folder /community/interns/website testing to recruitment

**Comment by PatReynolds** [comment]
Looking at the York bursaries ...  there are limits on weeks/hours.  Student max 10 weeks, max 16 hours per week... so we would be limited to 160 hours, term time.  Graduates 2 weeks / 70 hours.   This is going to be quite tight for this bursary, but we could always (if the person was good, and ran out of time) employ them as an intern after the scheme).

**Comment by DeniseColbert** [comment]
York are shortlisting today and will send to Pat later on

**Comment by richpomfret** [comment]
Now to short-listing on the 26th (due to decision to leave application process open for longer period of time).
