### ISSUE TITLE
Consider creating formal fundraising group(s) /committee(s) 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1229]
(Friends of Free UK Gen /FreeBMD /FreeREG /FreeCEN etc.

Fundraising on behalf of

**Comment by PatReynolds** [comment]
WEb page for Fundrasigin team made live 21/8/2020

Advert needs linking to Management Opportunities page.

**Comment by DeniseColbert** [comment]
Done
