### ISSUE TITLE
Fundraising at 2019 conference

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1231]

**Comment by DeniseColbert** [comment]
https://docs.google.com/document/d/1Zm1PnXB4TjFFkmy-HWfD8OHtda6Evr3F1wnyu1Kys3g/edit

**Comment by PatReynolds** [comment]
Denise sent email to Helen V. 8/11/2019

**Comment by PatReynolds** [comment]
@PatReynolds  to split money between the two Kindlink Fundraisers

**Comment by PatReynolds** [comment]
Creat Dummy Page for FreeREG project on Kindlink, donate money in, and then deselect the fundrasising active button, pending having something to raise money for.
