### ISSUE TITLE
FreeUKGEN website text is too light- make darker.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1234]
We lost a potential donor due to the website text being too light for her to read. Not sure if we're making the text darker when new, accessible colours roll out. @AlOneill is this planned?

**Comment by AlOneill** [comment]
Yes, the default text colour will be darker — (#)222 rather than the current (#)444

**Comment by arswright-alt-uk** [comment]
@DeniseColbert If this is an issue that you would like to see corrected on the present design it's an easy fix - proceed with change or wait to redesign?

**Comment by AlOneill** [comment]
Yes — a one-line edit could update the default text colour across all 3 projects — with one more edit to update the FreeUKGen site. (Assuming it was the default text colour, the body text colour, that is the issue.)

**Comment by DeniseColbert** [comment]
@AlOneill yes it is the body text colour.

@arswright-alt-uk please do ahead and change the text colour to #222 on the FreeUKG site.

I will make a story on systemwide for the change on other websites.

Thanks, both :)

**Comment by AlOneill** [comment]
@DeniseColbert On reflection, it would be better to not change the text colour ahead of the other changes, for technical reasons. Sorry!

**Comment by DeniseColbert** [comment]
No problem; however, since the issue that prompted this story concerns the FreeUKG website (and specifically income, which would give it a high priority), I think @arswright-alt-uk should make the change on there. Code is totally separate, so I'm assuming that would be OK?

**Comment by AlOneill** [comment]
@DeniseColbert Sure: I have no knowledge of how the GUKG CSS is organised, so by all means go ahead thee.

**Comment by arswright-alt-uk** [comment]
Created https://github.com/FreeUKGen/FreeUKGenealogy/issues/58 for this issue, leaving open for @DeniseColbert to close upon creating systemwide issue.

**Comment by DeniseColbert** [comment]
Systemwide story created. Closing.
