### ISSUE TITLE
Plan pre-scrum and scrum timings to facilitate Kirk's involvement

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1238]

**Comment by DeniseColbert** [comment]
Will this help for FreeBMD2? I can duplicate/make it general for use in the other projects? https://doodle.com/poll/3tks7fye6avurvr2

**Comment by richpomfret** [comment]
@DeniseColbert thank you - yes that could be useful. It looks like we could simply move the FreeCEN refinement meeting from 2pm to 5pm (after rather than before the FreeBMD2 meeting). We do not currently have any meeting for FreeBMD2 at all in the books for next week..

**Comment by richpomfret** [comment]
Looks like we can move FreeREG back to 5pm-6pm on Mondays, which gives us a bit of extra space for FC and BMD2. :)
