### ISSUE TITLE
BMDs at Sea - Links

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1252]
https://www.freeukgenealogy.org.uk/admin/entries/pages/2597-bmds-at-sea

PLease chaeck @PatReynolds

**Comment by PatReynolds** [comment]
Made one addition.  The last two sentences might need combining into one.  I didn't think the second link added anything not in the first link.  Perhaps link directly to https://www.familysearch.org/search/catalog/results?count=20&query=%2Bkeywords%3Apassenger%20%2Bkeywords%3Alist (not sure that works! - it is the FamilySearch catalogue search.

**Comment by PatReynolds** [comment]
Denise to check that this is done.

**Comment by DeniseColbert** [comment]
Done, now live. Closing.
