### ISSUE TITLE
Actions from Trustee meeting July 2019

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1256]
- [x] Andrew re financial spreadsheets help - DONE 22/7
- [x] Check insurance policy re corruption/bribery - in progress, asked broker 16/7 chased 11/12
- [x] Whistleblowing - DONE
- [x] add footnotes to clarify disclosure protections - DONE
- [x]  re-check advice on, and clarify in the policy how to raise concerns, leapfrogging to all trustees, making it easier to whistle-blow- DONE
- [x] Draft new version for volunteers, rephrasing passim - moved to new story - DONE
- [x]  Explain volunteers are employees for this (and other) purposes - checked and need to write separate policy - DONE.
- [x]  Add to volunteer handbook - moved to new story - DONE

- [x] Look at google searches for genealogy - add to report / correlate with banner income - DONE

- [x]  Change policy group agenda/minutes to be 'last meeting of Trustees'.

- [x] Sign agreement with Partner for Adsense

- [x] Actions re Open Data

- [x] check Anthony's email sent on to Trustees - DONE

- [x] Expediate Trac on T&C update - created and added interim text.

- [x] Join FFHS - DONE

- [ ] Call to action - circulate for comments/ideas

- [x] PR to write press release on ability to take screen shots, etc. from FreeBMD

- [x] Chase typo on Transcription Agreement - send to Trustees.

- [x] Font - send to Trustees for approval - DONE 22/7

- [x] Check- do adverts down the side scroll down? -DONE
- [x]  FreeBMD2 search results need a legend - DONE

**Comment by PatReynolds** [comment]
Whistleblowing DONE.  New story on need for policy for Volunteers. @Denise can you proof the Employee version, and check against requirements from the meeting?

**Comment by PatReynolds** [comment]
Draft press release for development/thoughts @DeniseColbert https://docs.google.com/document/d/1E82OstpuCE45JyZrBXST5dT0-ibHEbBGliMGkuFRxDU/edit?usp=sharing

**Comment by PatReynolds** [comment]
Asked Barrie to resend change on Transcription Agreement 11/12/2019

**Comment by DeniseColbert** [comment]
Proofed - made one suggestion.

**Comment by PatReynolds** [comment]
Thanks, Denise - this can now be issued (I think you have the mailing list for press releases on Mailchimp?

**Comment by DeniseColbert** [comment]
Done
