### ISSUE TITLE
Set up Kindlink to collect donations

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1277]
https://charity.kindlink.com/donations/settings

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/9af777f4-dede-4f8e-91b0-f970298844ea)

https://charity.kindlink.com/donations/stripe-onboarding

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/1e7a80c7-fccb-46c0-9326-834b541438c5)

NEED to restore to Version 8 Pat Reynolds of "Ways to donate" when we can take money via Kindlink

**Comment by DeniseColbert** [comment]
I'll disable Kindlink from Donation stream, will enable when setup is complete.

**Comment by PatReynolds** [comment]
Just completed form.

**Comment by DeniseColbert** [comment]
This appears to be set up now: 
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/68ea3773-a065-4a57-90dd-622795d0bf12)

**Comment by DeniseColbert** [comment]
Reverted to Version 8 (ways to donate page in Craft) - can be closed.
