### ISSUE TITLE
November Newsletter

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1295]

**Comment by DeniseColbert** [comment]
46M records FreeREG
https://mail.google.com/mail/u/0/#inbox/FMfcgxwDqnqjNBBqwFSgnKkMhJznpdNv

**Comment by DeniseColbert** [comment]
Viewed records feature on FreeCEN

**Comment by PatReynolds** [comment]
Is this ready for me to proof - I can't see it (let me know date sent, please, if it is lurking in my in-box).

**Comment by DeniseColbert** [comment]
Was waiting for the OK on the colours blog, will add it and send draft NL, probably tomorrow.
