### ISSUE TITLE
Volunteer expenses claim links volunteers to Employee Handbook

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1304]
Expenses claim form links to old Employee Handbook, not to volunteer handbook.  Might be good to have a page on FUG website (not linked to anything else) where all the handbooks and forms point, where we can update the rate from time to time.

**Comment by DeniseColbert** [comment]
Made a comment in volunteer expenses policy about link. 

Re. page on website, one page for all docs i.e. handbooks, policies, forms? So volunteers can view employee docs etc. Or two - one for volunteers, one for employees?

**Comment by DeniseColbert** [comment]
Decision still pending on a) pointing to employee handbook (which doesn't give mileage rate anyway) and b) what to put on new web page @PatReynolds

**Comment by PatReynolds** [comment]
Link to rate for the form (both places): 
https://www.gov.uk/expenses-and-benefits-business-travel-mileage/rules-for-tax
Saves us having to create such a page!

**Comment by DeniseColbert** [comment]
Added .gov/ HMRC link to volunteer expenses policy and Employee Handbook. Point a) still persists- are we sure we want to link volunteers to the Employee Handbook?

**Comment by PatReynolds** [comment]
Separate Expenses Policy from the Employee handbook, and link to it from both Employee Handbook and Volunteer Expenses Policy

**Comment by DeniseColbert** [comment]
New document for Expenses Policy: https://docs.google.com/document/d/1N7SbIZ70IQAlKxrGCrFkgy9aQrtct791G_BA-b8AHH0/edit?usp=sharing please review @PatReynolds

**Comment by DeniseColbert** [comment]
Please also check replacement text in Employee Handbook

**Comment by PatReynolds** [comment]
Policy fine, change to Employee Handbook too.

**Comment by DeniseColbert** [comment]
Expenses issue now fixed in all documents.

Whilst tinkering with Employment Handbook I merged changes since last trustee sign-off (July) into copy [FOR REVISION]. Does this need trustees to review? We just missed the January meeting; do we wait until the next one or send around via email?
