### ISSUE TITLE
Send Annual Report 2019 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1305]
Pat to write introduction

**Comment by PatReynolds** [comment]
First draft 14/2/2020

**Comment by DeniseColbert** [comment]
Read over this today, will work on infographics with design volunteers and on making technical language more accessible. Would this work as a 'crafted' PDF e.g. https://helpmesee.org/extdata/1/rec_docs/25_HelpMeSee_2015_Annual_Report.pdf?

**Comment by DeniseColbert** [comment]
Great ideas here https://www.networkforgood.com/nonprofitblog/choose-the-right-annual-report-format-for-your-donors/

And lots of inspiration here https://www.nonprofitmarketingguide.com/resources/nonprofit-annual-report-examples/

**Comment by PatReynolds** [comment]
Ooh yes!  That's great!!!  I like the way they use images/words to do with sight.  I'm thinking of something along the lines of time+people, possibly.

**Comment by DeniseColbert** [comment]
Text almost ready; will indicate on doc where infographics could be used and graphs sourced FAO @KatyMawhood
