### ISSUE TITLE
Accessibility statement freeukgen

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#131]
link to "access for all" on front page of website

**Comment by DeniseColbert** [comment]
Duplicate of #95? Or should we have separate stories for each statement?

**Comment by PatReynolds** [comment]
For main Free UK Gen website (should refer to what we are doing for all websites).

**Comment by PatReynolds** [comment]
Place link in Footer of main website.

**Comment by DeniseColbert** [comment]
Draft done, if you could have a look and let me know what else needs adding

**Comment by PatReynolds** [comment]
That's fine - please add to footer.

**Comment by DeniseColbert** [comment]
Done
