### ISSUE TITLE
Investigate Groups.io for FUG & FreeBMD newsletters

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/Coordination#1310]
Email sign-ups/newsletters are always a great way of nudging people back to a website. However, ours is a little tucked away (perhaps resolved with a pop-up when the user is about to leave the page/site).

When trying to sign up, the user is asked to input their name and email and then hit subscribe. When doing this, they are then taken to another screen which asks them to do the same thing again - this is off-putting and shouldn't be necessary. I am not quite sure why we say we'll only send one email every 2 months too, we simply need to make the emails of interest.

**Comment by richpomfret** [comment]
When trying to complete the sign-up, it then hits a bug and won't take you back to the site. I'll stop complaining now. ;)

**Comment by DeniseColbert** [comment]
Emailed FlashIssue 22/11 re. subscribe bug.

Re. 
> I am not quite sure why we say we'll only send one email every 2 months too, we simply need to make the emails of interest.

This has been in place since before I started with FreeUKG - I guess it's to reassure subscribers that we won't send them lots of mail.

**Comment by PatReynolds** [comment]
Flashissue know it is a bug, but have no eta.
Look for alternatives.
Be good to have something with an auto-response to sign up.

**Comment by PatReynolds** [comment]
Groups.io as the solution?

**Comment by DeniseColbert** [comment]
Signed up with Groups.io. From what I've read so far it seems that it could be a good fit. Seems we can set a Group as 'Announcement' (subscribers can't post) but we have to upgrade to be able to 'direct add' our existing subscribers (one-off $20 for a month would give us plenty of time to do this).

Will perform a few tests sending to @PatReynolds

**Comment by PatReynolds** [comment]
Denise to try making (existing) newsletter in Mailchimp and sending to Groups.io
Denise then to test thoroughly
