### ISSUE TITLE
Papers for Advisory Board, 9th Jan 2020 (circulate update by 20 Dec)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1314]
- [ ] Circulate Advisory Board Update, bu 20th December, invite comments by 1st Jan.
- [ ] Circulate AB agenda by 2nd Jan

**Comment by PatReynolds** [comment]
Hi Denise, report ready for proofing. I'll put the link in Slack. Pleaes let me know if I've missed something important!

**Comment by DeniseColbert** [comment]
I've proofed it, and will send once my suggestions have been reviewed. Will send with a request for suggested agenda items from the board.

**Comment by PatReynolds** [comment]
Thanks - I've just asked Richard - plus I want to see if tomorrow I can finish the audit and put together something on 'what we need folks to do' matching to that - to send out with report.
