### ISSUE TITLE
Create 2x A5 ads for technical (retired coders) and documentation volunteers 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1318]
To be emailed to volunteers with a request for them to print out and put up on noticeboards in their local areas (hospitals, Costa, Sainsburys etc have free-ad boards)

**Comment by PatReynolds** [comment]
See also systemwide #135

**Comment by PatReynolds** [comment]
add to text: you'll need your own development environment

@PatReynolds to feedback to email 4th April 15.23

**Comment by PatReynolds** [comment]
Done, and sent as part of Volunteer's Newsletter to FreCEN, FreeREG and FreeBMD volunteers, Trustees, Advisory Board, and to as many of the foundation volunteers as I could find.  21/8/20
