### ISSUE TITLE
Add data on financials and beneficiaries, etc. to Kindlink from Annual Report

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1324]

**Comment by DeniseColbert** [comment]
Info on Annual Report doesn't seem to match up with Kindlink e.g. Beneficiaries tab requires personal data on individuals, Financial info required is income and spending which aren't on the Annual Report etc.

**Comment by DeniseColbert** [comment]
Financilas done. How many volunteers do we have at last reckoning @PatReynolds ?
