### ISSUE TITLE
Replace "other Free UK Genealogy projects" images in Craft

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1328]
See email sent 8/11/19, subject: _"Images in 'FreeUKGEN Projects' area of FreeUKGEN website / Grunticon"_

**Comment by DeniseColbert** [comment]
Re. Kirk and Alison's replies, we should consider implementing this (along with regular font) on WP version of FreeUKGEN site, rather than in Craft as we don't have capacity to do it easily and soon.
