### ISSUE TITLE
New colours blog post

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1331]

**Comment by DeniseColbert** [comment]
Ready for proofing https://www.freeukgenealogy.org.uk/admin/entries/blogPost/2947-accessibility-improvements-new-colours-for-freecen-freereg

**Comment by PatReynolds** [comment]
Excellent work - no corerctions/changes needed, please release.

**Comment by DeniseColbert** [comment]
Thanks Pat.
