### ISSUE TITLE
FreeCEN volunteer - Transcription Tools - Role Description

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1332]

**Comment by allanraymond** [comment]
What about the same for FreeBMD? 

FreeBMD has been waiting a very long time for someone to develop transcription tools for non Windows volunteer.

**Comment by DeniseColbert** [comment]
@allanraymond this is a liaison role for someone in FreeCEN who is familiar with the tools to advise the development team. I'm not sure of the plans for FreeBMD tools right now (perhaps @richpomfret can help there) but an equivalent volunteer (and more!) may well be needed in FreeBMD2.

**Comment by allanraymond** [comment]
Unfortunately I have had no luck when posing this question to Rich, always a negative sort of response. I have been asking this question for a number of years.
