### ISSUE TITLE
Recruit a FreeCEN2 Researcher Specialist (could be a UK family historian familiar with census materials - does not have to be an existing FreeCEN volunteer).

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1338]

**Comment by PatReynolds** [comment]
Advertised 16/12 to transcribers and coords

**Comment by DeniseColbert** [comment]
Advertised on Social Media

**Comment by PatReynolds** [comment]
Seen on Facebook!

**Comment by DeniseColbert** [comment]
Inundated with responses already!

**Comment by PatReynolds** [comment]
Denise/Pat to add details to the role description.  Denise to contact (?using flashissue) enquirers with updated role, and ask them for more details from them (also push towards helping others on FreeCENfacebook, transcribing, etc)

**Comment by PatReynolds** [comment]
Pat to check form, then Denise to send out.

**Comment by DeniseColbert** [comment]
2 x researcher specialist vols recruited and added to new Groups.io Exec list and invited to scrums going forward
