### ISSUE TITLE
Formalise procedure for updating / versioning Google Documents with inbound links.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1354]
See draft https://docs.google.com/document/d/1yHCD56nh9ijBkbYS5Gs9NUHjLR3CSy1XZzuyFurlQnM/edit?usp=sharing

**Comment by PatReynolds** [comment]
That's perfect, thank you.

**Comment by PatReynolds** [comment]
@Denise to send to development team, support team and documentation teams.

**Comment by PatReynolds** [comment]
Put in Google group for doc vols, and on slack.
