### ISSUE TITLE
Minutes of the January 2020 Trustees meeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1368]

**Comment by PatReynolds** [comment]
Sent paperwork to accountants 3/2/2020

**Comment by DeniseColbert** [comment]
I think your comment should have gone into a different story?

**Comment by DeniseColbert** [comment]
My bit's done- sen't doc in an email 10/2/20

**Comment by PatReynolds** [comment]
I got a bounceback saying not delivered to executive@freeukgenealogy.org.uk - but Graham has got it. Is the address wrong?

**Comment by DeniseColbert** [comment]
I hadn't made the group but I have now. Graham will have it as you tagged him in a comment. Can you resend?

**Comment by DeniseColbert** [comment]
Email titled: Additional Financial Document and bank balances received. Haven't had minutes though.

**Comment by PatReynolds** [comment]
I will send minutes now, now that I know I have the correct email address.

Best wishes,

**Comment by PatReynolds** [comment]
Contacted Aleandra and Graham 25/3.
