### ISSUE TITLE
limit searches to exclude repeated Census report

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1373]
I'd would be nice to limit searches to exclude repeated Census report for when searching by surname. In a search I get 130+ results I have to go through one by one, but this is super inefficient when their are only ~40 unique results.

**Comment by PatReynolds** [comment]
Decided in scrum 5/2/2020 that the utility of only having to look at 40, rather than 200 records was not as important as finding two people with the same name in a very large "household" such as a hospital or school.
