### ISSUE TITLE
Create Onboarding Pathway for new Ruby Volunteer Coders

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1378]
In order to on-board new Ruby coders without placing a strain on current developers, we need to have a replacement for Cloud9 / similar pathway in place.

**Comment by PatReynolds** [comment]
Hidden Gems: Invite to roadmap meetings and to one scrum so they can see the big picture, encourage to take on stories / attend regularly when they self-assess their coding skills as adequate.

**Comment by PatReynolds** [comment]
Hi @Vino-S could you invite the new coders to a scrum please (FreeCEN for Anne and whatever is convenient for Ian).  I will invite to roadmap meetings.

**Comment by DeniseColbert** [comment]
Denise to invite Anne and Ian to FR Roadmap meeting

**Comment by PatReynolds** [comment]
@DeniseColbert to talk to Kirk about database volunteer and introduce coder to Vino
