### ISSUE TITLE
Onboard trustee w/ special interest in fundraising

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1381]
Help set up on/ using Google

**Comment by PatReynolds** [comment]
Review role description - send to Pat, then add to Reach, etc.

**Comment by PatReynolds** [comment]
Needs re-activating (reach, charity job)

**Comment by PatReynolds** [comment]
Denise to contact Yvette

**Comment by PatReynolds** [comment]
@DeniseColbert tosend declaration form to Trustees
