### ISSUE TITLE
Specification for 2020 Conference

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1396]
Broadcast via YouTube
Q&A on Social
How long presentations, the how of them
Identify volunteer support needed

**Comment by PatReynolds** [comment]
Denise to send planning document to Trustees and AB for them to add their thoughts to.

**Comment by PatReynolds** [comment]
@DeniseColbert to update

**Comment by DeniseColbert** [comment]
Updated 27/08/2020

**Comment by DeniseColbert** [comment]
Emailed Pat 22/09

**Comment by DeniseColbert** [comment]
Sent out 28/09

**Comment by PatReynolds** [comment]
Denise to review.
