### ISSUE TITLE
Initial decisions for 2021 Conference

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1398]
Identify Date
What areas do we want covered?
Identify groups and individuals working in those areas

Decided: use Zoom
- [x] initial publicicity
- [x] book speakers

**Comment by PatReynolds** [comment]
Pat to add to agenda

**Comment by PatReynolds** [comment]
@PatReynolds to contact https://opengendata.org/ on her return.

Very drafty agenda created - please move to the conference folder - which I couldn't find :-(

**Comment by PatReynolds** [comment]
A "Bring your own cake" competition?

**Comment by PatReynolds** [comment]
To decide (add to agenda for Trustees meeting)
date(s) and time(s).
where is our audience (how split between time zones).

**Comment by PatReynolds** [comment]
Denise to send doodle for dates (mid-Oct to mid-Dec) for availability updates.
Pat to email potential presenters once date known.

**Comment by PatReynolds** [comment]
Denise to ask Trustees about pattern (evening-evening, evening-morning or day).

**Comment by PatReynolds** [comment]
Denise to review decisions with trustees re timings/dates

**Comment by DeniseColbert** [comment]
Two subsequent Saturdays - 4pm to 7pm UK (+North America and NZ maybe) & 8 to 11 am UK (Australia, Far East/ India, and NZ maybe)

From Richard:
Each conference 'day' lasted three hours. It was split into two halves, with a 30-minute break/break-out in the middle.
Each half-session lasted 75 minutes. Each of the three speakers was asked to talk for 15 minutes; the examples I have checked actually varied between 13-17 minutes. The talks were all pre-recorded. The panel session involved all three speakers, lasted 22 minutes, and was (obviously) live.  Essentially the panel ran until the scheduled end of the session.

**Comment by PatReynolds** [comment]
@DeniseColbert to make an initial timetable for discussion at next Trustees meeting on this basis
