### ISSUE TITLE
Donor survey/email

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1402]
See doc emailed 2/4

**Comment by PatReynolds** [comment]
@PatReynolds  to comment - potential to involve Richard L. while Pat on furlough

**Comment by PatReynolds** [comment]
Commented - I'll talk to Richard about this this afternoon.

**Comment by DeniseColbert** [comment]
Email copy (draft) sent to Richard on 20/5/20

**Comment by DeniseColbert** [comment]
Acknowledge that this is a year out of date, in future we hope to be able to get this out closer to the financial year.

**Comment by PatReynolds** [comment]
Send Denise spreadsheet of Donors as far back as can be downloaded from PayPal, plus link to earlier month by month spreadsheets
