### ISSUE TITLE
Add FB / tweets monthly on additions to records

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1411]
https://freecen1.freecen.org.uk/recent.html has the latest additions - worth a tweet and fb post by county, with an invitation to 'share to those you know have ancestors here'.

FreeREG more difficult (but you can use the county pages to see 'latest additions' - but that doesn't say how many.  Maybe @edickens or @Sherlock21 has a report or an idea of which parishes have seen an lot of records being added? Or use Eric's newsletter to highlight counties (May Lancashire had 40k+, Sussex and Essex had 35k+, Kent and Warwickshire had 15k+  WEst Riding of Yorkshire passed 2 million records and Northumberland passed 1 million. Worth providing a link to the 'updated record' page for those counties for people wanting to see the detail.

FreeBMD I think it's a case of keeping an eye on the stats pages (e.g. https://www.freebmd.org.uk/progressM.shtml) to see which type/year have been completed in a given month.

@Denise to document where to look on each project / make smoother

Volunteer to find out twitter, facebook and insta presences of Record Offices, Family History societes and any others who might be interest in a particular place.

**Comment by DeniseColbert** [comment]
Started a doc to record discussion: https://docs.google.com/document/d/1r4AkSvt_jcmr6HQhxvdwY7x5-5doBJnOELtt_N_BIuE/edit?usp=sharing

**Comment by PatReynolds** [comment]
Recruit on social media - Pat (twitter) Denise (fb) (ideally with canva, or willing to learn)
