### ISSUE TITLE
July Newsletter

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1423]
UCF

**Comment by DeniseColbert** [comment]
Awaiting info from Allan, and looking for anything FreeBMD related we can put in?

**Comment by PatReynolds** [comment]
Maybe the graph showing recent additions?

**Comment by PatReynolds** [comment]
Denise to add graphics/data to the newsletter on recent increases in records.

**Comment by DeniseColbert** [comment]
Sent to @PatReynolds for checking 2/10
