### ISSUE TITLE
Volunteer newsletter 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1435]
**Who?** - Across all three projects would keep the workload manageable
**What?** - Include stats from project newsletters
**How?** - Denise to collate info from Allan, Chris and Eric and add organisational news/requests
**Where?** - Is there an argument for having a central mailing list for this? Or do we continue with sending via message system for FreeREG, Google Group for FreeCEN and Groups.IO for FreeBMD? 
**When?** - The 3 projects' updates happen at different points. When would be a sensible point to send this NL? FreeREG feedback asks for them to not be too frequent to avoid overload. Also potential repetition due to coordinators sending updates too. Would quarterly help mitigate this?

Issue 2:
Include Reward Gateway info (also news that we can't use their o/seas versions, sorry!

Issue 3: **Include news about what we are applying for in the next Volunteer’s newsletter
**

**Comment by DeniseColbert** [comment]
FreeREG volunteer feedback: https://docs.google.com/document/d/1Vv0HzLXR39VpZPiBW3HkaWpBuw4rZLLshj7jnOcvszY/edit?usp=sharing

**Comment by PatReynolds** [comment]
Pat to write about project news.

Job sharing

**Comment by PatReynolds** [comment]
Draft written.
