### ISSUE TITLE
Contact speakers for conference

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1437]
- [x] Erica Baker [https://www.ericabaker.com/](url) Email: speaker@ericabaker.com (Genealogy Tech)
- [x] TNA (Experience of opening their records during lockdown)
- [x] Archives.ie [https://www.archives.ie/about-us](url) (How Open are they?)
- [x] Slavery project (How Open are they?)  Cambell (UCL) on the Mellon funded Slavery project???
- [x] https://www.openarch.nl/?lang=en
- [x] Turing Institute???
- [x] Someone from the Forum on The Family History Information Standards Organisation on the Extended Legacy Format / and perhaps someone else with an opinion of Gedcom
- [x] Someone from Wikitree

- [ ] Open GLAM
- [ ]  GOONS
Denise to find contact details for above

**Comment by PatReynolds** [comment]
Pat to contact potential speakers

**Comment by DeniseColbert** [comment]
Updated Speakers doc with contact info for you to contact the last two orgs @PatReynolds
