### ISSUE TITLE
No-fee Donations site

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#144]
There is a new donation platform: https://wonderful.org/ looks like aimed at people who raise money for charities but may also work for us. They take NO FEES! 100% of donations go direct to charities.

**Comment by PatReynolds** [comment]
Looks good.  I've asked Camilla about moving to it once CIO is in place.

*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
