### ISSUE TITLE
Database statistics reporting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1452]
The purpose of this issue is to capture the database statistics reporting across our websites, to see which are common, and therefore will be implemented via multimodal, and which are unique.

The reportiong of this data is for two purposes:
a) to inform the user (e.g. that a search has failed to find something not because the event did not happen, but because we have no transcription of that event.
b) to be used by the Comms team to create social media posts, newsletter (and possibly other uses) which allert the users to new data becoming available (e.g. to say that a piece on FreeCEN has been completed, or that the marriages 1550-1700 have now been added to a parish on FreeREG, or that or that deaths for a certain period on freeBMD are now complete.  All with a caveat that 'completed' is not a guarantee of completeness, as for various reasons the transcription of the event searched for may still not be there.

**Comment by allanraymond** [comment]
Do you have background information relating to this Issue?

**Comment by PatReynolds** [comment]
Sorry, @allanraymond - written in haste, I've now added the description.

**Comment by allanraymond** [comment]
Thanks.

With regards to FreeBMD.

a) anyone who searches FreeBMD and can't locate a record already have the option of clicking 
**Don't understand the results? Can't find the record you are looking for?
Perhaps our Results Help could have the answer.** 
b) our Coverage Charts at https://www.freebmd.org.uk/progress.shtml shows whether a particulat event/period has been transcribed

**Comment by DeniseColbert** [comment]
Superseded by systemwide story on multimodal reports. Closing
