### ISSUE TITLE
Static statistics for footer of each project

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1453]
(Main story on Systemwide)

**Comment by PatReynolds** [comment]
For each project:

How many active volunteers there are @PatReynolds 
How many searches a month  (from analytics, combine the two FreeCEN figures) @DeniseColbert 
How many records in the database (automatic for FreeREG, and FreeCEN, needs a manual take of Distinct Records from FreeBMD1  Pat to ask Vino about potential for automation on FreeBMD2.
