### ISSUE TITLE
November 2020 Trustee meeting minutes

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1458]

**Comment by DeniseColbert** [comment]
https://docs.google.com/document/d/10iYKjFd2WP9r6I6cV_-atG8YbXOMBYspAgtS8ahA8X8/edit?usp=sharing

**Comment by PatReynolds** [comment]
Thanks, @DeniseColbert  fine to circulate (no corrections, just did the lookup of the constitution).

Need to note in agenda fro next meeting the decision to appoint Kathryn as a trustee ... will go and start the agenda now before I forget that!

**Comment by DeniseColbert** [comment]
Circulated. Can close when/if your final bit for next agenda is done @PatReynolds 

**FYI** I put the date of the meeting on the Trustee details doc, if it's wrong please change.
