### ISSUE TITLE
March financials

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1479]
- [ ] Create issue for 3 months forward (or reactivate old one)
- [ ] Overtime (and ask Paybureau to run payroll, even if no additional hours) 
- [ ] Execute payroll 
- [ ] Check reconciliation  Zoho and Quickbooks 
- [ ] Financial Report
- [ ] Three-month projection (and move money)
- [ ] Check VAT incoming
- [ ] Pay Pensions

**Comment by DeniseColbert** [comment]
Duplicate closing
