### ISSUE TITLE
Papers for July 2022 Trustee/Advisory Board Meeting(s)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#1492]
- [ ] Agenda for Advisory Board
 - [ ] update general metrics
 - [ ] Agenda for Trustees
 - [ ] Previous minutes (add shortcut to folder)
 - [ ] Updated minute book (add shortcut to folder)
 - [ ]  Report on decisions made outside the meeting
 - [ ]  Budget reports (FUG and Trading Co)
 - [ ]  List of policies to be written / reviewed
 - [ ] Forward projection
 - [ ] Financial update
 - [ ]  Risk register
 - [ ]  Metrics (move data from Financial and Strategic reports here for 1/22 meeting onwards)
 - [ ]  Open Data sign-up report
 - [ ] Andrew's update on fundraising
 - [ ] Report on each service, as appropriate
 - [ ] Priorities of work to next meeting

**Comment by PatReynolds** [comment]
@PatReynolds  to check big report to see if she has missed anythinng

**Comment by PatReynolds** [comment]
@DeniseColbert could you take a look at the agenda, please?  Are the links correct?
