### ISSUE TITLE
Minutes of August Trustee meeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1512]

**Comment by PatReynolds** [comment]
Pat tosend Denise her notes

**Comment by DeniseColbert** [comment]
https://docs.google.com/document/d/1dO9rkzk-evlhNDPLaZm-lRxdMpygQZq6YoIGV3FSfq8/edit?usp=sharing

**Comment by PatReynolds** [comment]
Updated draft - some questions for you @DeniseColbert
