### ISSUE TITLE
Volunteer Survey

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1513]
Volunteer survey:
Ask people about the average time they spend per week, and how many records they transcribe in a week on average
Anonymise, so we can ask about disabilities and age

**Comment by DeniseColbert** [comment]
Add demographic Qs from SOG survey

**Comment by DeniseColbert** [comment]
Send to Comms team, Alison, Eric, Philip, Mick Claxton

**Comment by PatReynolds** [comment]
@PatReynolds to see if any questions could be combined

**Comment by PatReynolds** [comment]
Not sure I've found the right version ... have made one suggestion (will do a look re combination if it's the right version, now for some lunch or I will be eaten by a cat).
