### ISSUE TITLE
Create Ebay seller account

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1542]
For Helen B to manage, if needed

**Comment by Powerboy2021** [comment]
Guy can anyone help me create an account eBay Seller?

**Comment by DeniseColbert** [comment]
![image](https://user-images.githubusercontent.com/19173257/145172333-aae3cb56-0205-426c-9efe-f7793686b36f.png)

How do we want to set up payments?

**Comment by PatReynolds** [comment]
Payment now succesfully added, so closing!
