### ISSUE TITLE
Minutes of October 2021 meeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#1544]

**Comment by DeniseColbert** [comment]
https://docs.google.com/document/d/1tRHjfux9XR4dakl2UIuSkf0UJI2oRh7Dfa2yU-mIZYk/edit?usp=sharing

**Comment by PatReynolds** [comment]
Added what I have in my notes - some as questions.

**Comment by DeniseColbert** [comment]
Have answered, and Andrew and I clarified FR stuff earlier

**Comment by PatReynolds** [comment]
Have just checked with Graham re pay run.

**Comment by DeniseColbert** [comment]
There are still unresolved comments @PatReynolds , do we still want to send?

**Comment by PatReynolds** [comment]
Still a couple of issues but will need trustees to tell me what I wrote. Otherwise good to go
