### ISSUE TITLE
Distribute Security Policy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#158]
Distribute security policy (or cut-down instructions, relevant to roles) to all

**Comment by richpomfret** [comment]
Include explanatory note re: class/groups. To highlight certain areas for transcribers/volunteers (etc).

**Comment by richpomfret** [comment]
To also explore sending out a questionnaire/self-assessment for users as part of this.

**Comment by richpomfret** [comment]
To discuss distribution (to co-ordinators who then pass on?) and for new users to automatically receive/agree to when signing up as volunteers.

**Comment by Captainkirkdawson** [comment]
Love to know what it was

**Comment by richpomfret** [comment]
Consider it a late Christmas gift. ;) I'll be sending it out over the next few days.

**Comment by PatReynolds** [comment]
@DeniseColbert would you like an early Christmas present?? Could you take a look at the security policy and make versions of the bits that apply to various kinds of people, using appropriate language for them (e.g. transcribers, project managers).  Don't worry about the top level security stuff: Rich and Lemon, etc. are able to take the policy and know what to do with it. Thanks!

**Comment by DeniseColbert** [comment]
We should consider how to give access to core volunteers- other policies are linked to in handbook

**Comment by DeniseColbert** [comment]
Transcriber version done but awaiting feedback / comment replies

Mid-level to be completed (definition cull and Appendices organised) upon comment replies

**Comment by PatReynolds** [comment]
My feedback done. @richpomfret do you have anything?

**Comment by DeniseColbert** [comment]
I don't *think* Appendix A should be in the Coord or Transcriber versions, but could you confirm?

Replied, added and acted on your comments Pat.

**Comment by PatReynolds** [comment]
Yes, link to in handbook, no appendix A (rename B as A in these documents).

Pat Reynolds
Executive Director, Free UK Genealogy

On 13 Jun 2017 2:14 p.m., "DeniseColbert" <notifications@github.com> wrote:

I don't *think* Appendix A should be in the Coord or Transcriber versions,
but could you confirm?

Replied, added and acted on your comments Pat.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/FreeUKGen/Coordination/issues/158#issuecomment-308111338>,
or mute the thread

**Comment by DeniseColbert** [comment]
Mid-level version sorted; need replies to comments on Transcriber version

**Comment by PatReynolds** [comment]
Thank you Denise. Checked/responded 26/6.

**Comment by DeniseColbert** [comment]
Mid-level document complete

Transcriber document needs definitions placing in-text

**Comment by DeniseColbert** [comment]
I started to place definitions in text but it became very messy very quickly (E.g. public services and private services are definitions branching off the definitions for server, so we'd end up with 2 lots of brackets within brackets just in one sentence). 

How about placing the definitions table in the appendix?

**Comment by PatReynolds** [comment]
I have cut down the definitions as far as possible in the Transcribers' version  - and had a couple of comments for you.

**Comment by DeniseColbert** [comment]
Done- fixed a few broken contents links and removed stray sentence

**Comment by richpomfret** [comment]
Distributed 'in part' - holding off on full distribution until confirmation on actions relating to Barrie's comments (@Pat to review). However we may need to implement these into the next iteration of the document if it risks delaying us much further.

**Comment by pat** [comment]
I don't think you want me reviewing this - presuming you meant @PatReynolds?
