### ISSUE TITLE
Proof Guest Blog

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#166]

**Comment by DeniseColbert** [comment]
Anne has been asked by a small US based company to do a blog for their website on the GRO index. It will not be published until January at the earliest.  She's asked if it would be ok with us if she  gave them the same blog but with a few alterations – their word count is less and it will not require the background info.  They are aware it was written for us.

**Comment by PatReynolds** [comment]
Heading image?
