### ISSUE TITLE
Amend Tech Volunteer ad for posting in new year

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#176]

**Comment by DeniseColbert** [comment]
Would this service work for us? https://members.charityithelp.org.uk/sign-up-as-a-charity-guidance

**Comment by PatReynolds** [comment]
Yes, I think so.  Mention open source in application - if they have an issue with it, they'll say.

**Comment by richpomfret** [comment]
Just got an email from a new potential volunteer, so I presume this task is now complete and ready to add to 'Done'?

**Comment by DeniseColbert** [comment]
Great news! Yes it was 'done' when you amended it, I had my own story for
recruiting and Pat created a story for you to appoint volunteers earlier
today.

Kind regards,

Denise

**********
*Denise Colbert*
Engagement Co-ordinator

[Usual working days: Monday, Tuesday and Wednesday]

E: denise.colbert@freeukgenealogy.org.uk <denise.colbert@freeukgen.org.uk>
T: +44 7825 338014
W: http://www.freeukgenealogy.org.uk/

Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A Charitable Incorporated Organisation registered in England and Wales,
number 1167484.

VAT registration: 233 0105 70
