### ISSUE TITLE
Adjust anchor tag margin to account for static header

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#180]
On FreeUKGen website. See #44

**Comment by DeniseColbert** [comment]
On the Open Data Backgorund page at http://www.freeukgenealogy.org.uk/about/opendata/open-data-background/ there are a set of links near the top of the page. Some of these are 'anchors' which should take you to different parts of that page.  However, the points seem to be 'off' a little, possibly due to the static header?  We want the anchors to show the beginning of the section on the screen. Please ask for further clarification if needed.

**Comment by bev-fc** [comment]
What I see the cause is the static header, 'anchors' starts from the top of the browser, covered by static header

**Comment by DeniseColbert** [comment]
Is there a way  we can  adjust it or get round this somehow?

**Comment by bev-fc** [comment]
Was there a purpose for the static header? Do you want to keep the static header or you are okay with to modify it to non-static - the header will scroll up together with the contents of the page?

**Comment by DeniseColbert** [comment]
@PatReynolds what do you think?
