### ISSUE TITLE
Remove never-started transcribers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#182]
Email all in that situation (ID, no files) and ask them if they have sent files to a coordinator, are still working on files, or have stopped working, inviting them to tell us why they stopped (and send us the file of anything they have done).

**Comment by archerbarrie** [comment]
In relationship to FreeBMD (it is unclear what projects this task applies to) joining is handled entirely through syndicate coordinators. We should not, therefore, be emailing transcribers directly without first consulting with the syndicate coordinators. This is common courtesy but also the coordinators may already have addressed the situation.

**Comment by allanraymond** [comment]
I personally remove all volunteers in FreeBMD who have not transcribed for the project and prior to doing this I give the respective Coordinator two weeks to respond to my advice that the volunteer is a potential candidate for removal from the database.

**Comment by PatReynolds** [comment]
Restricted to FreeREG - pat to Contact @SteveBiggs to see how/who to take forwards there

**Comment by SteveBiggs** [comment]
I think this a SC responsibility. First thoughts:
- Any new volunteers who sign up at the website are contacted by the SC they signed up with to get them started. If they don't start for any reason, the SC deactivates them.
- Volunteers who never complete training are reported by Jo to the relevant SC, who should then deactivate the userID.
- Transcribers who never complete the first batch and give up or become uncontactable for a period (1 month?) should be deactivated by the SC.
- SCs should periodically purge their user list for any with 0 files - try contacting the user and if no response after a month, then deactivate.

**Comment by PatReynolds** [comment]
sounds good.  See also #254 on Coordination board.
