### ISSUE TITLE
Changes to Volunteering page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#183]
remove adverts for Advisory board and Craft, add advert for Partner Research volunteer.

**Comment by DeniseColbert** [comment]
I've combined the Advisory Board with the Trustee paragraph. Also removed Adsense ad and changed Sean's details to Rich's.

It's Draft 1

I'll add the Design , Partner Research  and FreeBMD clean-up vols later

**Comment by PatReynolds** [comment]
Now live
