### ISSUE TITLE
'Message submitted' on FreeUKGen contact form

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#184]
Message will be displayed after Send was clicked, till the new page gets reloaded.

**Comment by bev-fc** [comment]
deploy plan ready, if it is okay to use "a temporary css file" solution for now, we can do it now; or, we can wait till heard from others how to rebuilt compressed css file

**Comment by DeniseColbert** [comment]
Can you put the deploy plan in  here Bev?

**Comment by bev-fc** [comment]
purpose: after user click send contact form, display a message to let user know it is been submitted correctly

steps: 
1. modify /home/apache/hosts/craft/plugins/sproutforms/templates/_special/templates/form.html to create a field holding the messages
2. modify /home/apache/hosts/craft/templates/_layouts/main.twig to display the message only when submitted information are correct
3. create /home/apache/hosts/public/styles/css/additional.css to define how to display the message

Verify: 
after submit is accepted, message should be displayed. When it disappears, new record will appear in CP nav->Forms

**Comment by DeniseColbert** [comment]
I had asked you to deploy in here earlier Bev but I think the tab crashed (my laptop has been in the twilight zone today!)

**Comment by bev-fc** [comment]
what do you mean tab crash and twilight zone? It worked fine on my browser.

I rolled back the change, we can find another time to test it again if you like.

**Comment by DeniseColbert** [comment]
No, sorry Bev! I meant that you didn't see my comment to you to make
temporary css as my browser tab crashed. Twilight zone is a figure of
speech for strange things happening. The fix was fine, please roll back the
rollback ☺

Kind regards,

Denise

**********
Denise Colbert
Engagement Co-ordinator

E: denise.colbert@freeukgen.org.uk
T: +44 7825 338014
W: http://www.freeukgenealogy.org.uk/

Free UK Genealogy
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484.

VAT registration: 233 0105 70

On 8 Dec 2016 22:57, "Bev Yu" <notifications@github.com> wrote:

what do you mean tab crash and twilight zone? It worked fine on my browser.

I rolled back the change, we can find another time to test it again if you
like.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeUKGen/Coordination/issues/184#issuecomment-265881132>,
or mute the thread

**Comment by bev-fc** [comment]
okay, I will apply the change again. :) Sorry for my misunderstanding.
