### ISSUE TITLE
Annual Report and Accounts 2016

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#185]
Deadline 31 January 2017

**Comment by PatReynolds** [comment]
Denise, can you check the Trustee's statement (in governance,  2015_6 Charity Commission and Accounts

**Comment by DeniseColbert** [comment]
Can't access folder

**Comment by DeniseColbert** [comment]
Done. (some tiny suggestions)

**Comment by PatReynolds** [comment]
Thanks, now opened to Trustees for comments.
