### ISSUE TITLE
Develop a plan for migrating FreeBMD to a new design

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#19]

**Comment by sean-wood** [comment]
Waiting for the roadmap from Allan to start defining a plan

**Comment by PatReynolds** [comment]
Awaiting meeting date from Allan

**Comment by PatReynolds** [comment]
Finish writing PID. @richpomfret please ask If I need to add/finish anything.

**Comment by richpomfret** [comment]
@PatReynolds I've done a minor pass to this (adding in Open data etc). Worth us going through it to review where we now are and what may be missing. I think once this is agreed/signed off (with Barrie/Allan too), we can proceed with fleshing out each key deliverable/epic into sub requirements.

**Comment by richpomfret** [comment]
Let's move this back into the backlog and change title to 'update..' - we have a high level plan which has been added (as stories) to the Waffle board. PID and roadmap are in the project folder and I'll add in a high level sprint schedule too.
