### ISSUE TITLE
Add google analytics to Free UK Gen website

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#199]
Code sent to Bev

**Comment by bev-fc** [comment]
Code has been added into Craft

**Comment by PatReynolds** [comment]
Pat - check working OK

**Comment by PatReynolds** [comment]
Working fine - report in Communications folder - says 'all web sites' but is www.freeukgen.org.uk

**Comment by bev-fc** [comment]
Can you attach a screenshot?

**Comment by PatReynolds** [comment]
![freeukgen analytics](https://cloud.githubusercontent.com/assets/6338822/21888920/51c2b57a-d8be-11e6-8291-f7f17c4b42d6.JPG)

Please let me know if there are specific sections/reports you need.

**Comment by bev-fc** [comment]
Hi Pat, do you mean the view name is "All Web Site data"?
