### ISSUE TITLE
Improving FreeCEN newsletter

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#200]
Rootsweb changes format of Chris's NL - "One of the thoughts I did have is to have the newsletters on a website, and when a new one becomes available, simply provide people with the link to it.

Putting them on the FreeCEN website is a possibility if it can be done.  I do have access to other sites so have a choice of places to put them."

**Comment by PatReynolds** [comment]
Member area of FreeCEN2 might be good.

**Comment by DeniseColbert** [comment]
Get Chris access to Refinery, ask Vino about Refinery training for Rena, Geoff, Pat and myself

**Comment by DeniseColbert** [comment]
Document to support comms coord: https://docs.google.com/document/d/1GVQwNOj6FWyobwgX6r5I1TfJCconx86evlAbOOT1Rls/edit?usp=sharing for discussion @PatReynolds

**Comment by PatReynolds** [comment]
@DeniseColbert to ask Chris what statistics/info he would like to include.

**Comment by PatReynolds** [comment]
@Denise to add to Developer calendar so can see when updates happen. @PatReynolds to review document

**Comment by DeniseColbert** [comment]
Great, thanks. Ready to send to Chris then :)

**Comment by PatReynolds** [comment]
All comments now resolved - ready to send to Chris :-)

**Comment by PatReynolds** [comment]
Yup!

**Comment by DeniseColbert** [comment]
Sent that in time for the NL that went out last night. Next job is to sign off on the template and link to/from guidance. Could you proof please @PatReynolds ? https://docs.google.com/document/d/1FBp6xszy1f6Aa62J3rq71VxdqQCGxc5bUACG8k0rFRs/edit#
