### ISSUE TITLE
Change word/doc letter, etc. templates

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#201]
New footer - for use from 1st Jan 2017
Free UK Genealogy CIO is a charity acting as an umbrella organisation for the FreeBMD, FreeREG and FreeCEN projects.
A charity registered in England and Wales, Number 1167484  
VAT registration: 233 0105 70

**Comment by PatReynolds** [comment]
e.g. pdfs on website

**Comment by PatReynolds** [comment]
Pat to check regs on use of official address.

**Comment by DeniseColbert** [comment]
This is in GSuite admin settings:

![gmail footer](https://cloud.githubusercontent.com/assets/19173257/22695621/3e120dca-ed43-11e6-8caf-2cc60657c545.PNG)

**Comment by PatReynolds** [comment]
We don't have to use an official address.

I've seen this wording for the number part which seems clearer.

Free UK Genealogy CIO is a charity acting as an umbrella organisation for the FreeBMD, FreeREG and FreeCEN projects.
We are a  Charitable Incorporated Organisation registered with the Charity Commission for England and Wales number 1167484
VAT registration: 233 0105 70

**Comment by DeniseColbert** [comment]
All documents dealt with, apart from organogram (in progress) and Gift Aid form

**Comment by DeniseColbert** [comment]
Footer on some FreeBMD pages needs updating (site:www.freebmd.org.uk 1096940) E.g. https://www.freebmd.org.uk/district-map-all-dir.1395091734/_.html

FreeREG is clean, FreeCEN, just this page http://www.freecen.org.uk/UsageInfo.html
