### ISSUE TITLE
Update references to Free UK Genealogy to reflect change to CIO

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#203]
From 1st January 2017 - where we give the registered charity number, this is now: 1167484.  Where name is formal (e.g. where registered number is used) Free UK Genealogy should be changed to Free UK Genealogy CIO.

to do this: check for "Free UK Genealogy" and "1096940"

**Comment by DeniseColbert** [comment]
There are many sites with out of date pages that reference the old number. However, there are only two instances of the old number on our website: one in an old file no longer in use (but returned in the Google search) and one mention of it in a PDF from a 2018 Conference presentation.
