### ISSUE TITLE
Volunteer planning

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#21]
Identify roles and skills where new volunteers are required, and develop and deliver plan to recruit them

**Comment by DeniseColbert** [comment]
https://drive.google.com/open?id=1_4g85mw2qUdsBp-l3qcIHQx8LSUxxcIMLvm_Zbc53kc

**Comment by PatReynolds** [comment]
@patreynolds to provide model

**Comment by PatReynolds** [comment]
Emailed 8/1

**Comment by DeniseColbert** [comment]
Volunteer document to be sent out to projects
