### ISSUE TITLE
Transfer March  18 Domain Names (do Feb)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#213]
Transfer 
freeukhistory.com
freeukhistory.net
freeukgenealogy.net
freeukgenealogy.org
to Gandhi.net

**Comment by richpomfret** [comment]
Who are we transfering these domains across to?

**Comment by richpomfret** [comment]
Transfering needs to be done via the control panel within fasthost: https://help.fasthosts.co.uk/app/answers/detail/a_id/559/~/transferring-.uk-domain-names-away-from-fasthosts

**Comment by richpomfret** [comment]
Transfer is now in progress.

**Comment by PatReynolds** [comment]
freeukgenealogy.org.uk still to be transferred?
