### ISSUE TITLE
January 2017 Newsletter

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#215]

**Comment by DeniseColbert** [comment]
@PatReynolds we have exceeded our 2000 subscriber limit with Mailchimp (2007 & 3 in a test list of you, Helen and I)

**Comment by DeniseColbert** [comment]
Things we can do:

1) For this campaign, remove people like Josh from SuperCool Designs (not sure how many there are like this: will it take us below 2,000?

2) For this campaign, create a segment of subscribers who opened the last 5 campaigns (~1,450), & those who signed up after 15th Dec 2014 (1,997)

3) After newsletter is sent, create a campaign (segment: subscribers who haven't opened the last 5 campaigns for example) to ask if they still want to hear from us and invite them to unsubscribe if not.

Or something else?
