### ISSUE TITLE
Recruit for Advisory Group

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#22]

**Comment by DeniseColbert** [comment]
Footnote added in draft FreeREG newsletter

**Comment by PatReynolds** [comment]
Have first AB meeting on eve of Tues 24th Jan
Recruit deadline: 1st December

**Comment by DeniseColbert** [comment]
Emailed to CultureLaw, Museums, HeritageEd and Archives mailing lists. Decent amount of interest.

Emailed request for project leaders to disseminate to Coords and volunteers. Responses coming in from FreeREG

Need clarification on the physical meeting

**Comment by DeniseColbert** [comment]
Skills spreadsheet started-  in Community folder.

**Comment by DeniseColbert** [comment]
Send details to Camilla

**Comment by PatReynolds** [comment]
Pat - add last few, and send to Camilla

**Comment by PatReynolds** [comment]
Done and sent 3/1
