### ISSUE TITLE
February Blog

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#221]

**Comment by DeniseColbert** [comment]
I wonder if Alison might like to write a piece about FR2 (as per #1070 ):

"Perhaps we need to work a bit harder on selling FR2. Change is harder to take when user has little idea of why it is needed and what the net benefits are. Article could cover such things as increased flexibility of new search approach, the need to accommodate a variety of devices, the need to be accessible to those with disabilities, the availability of up to date and accurate numbers of records, benefits to transcribers and coords (and hence for researchers), &c, &c."
