### ISSUE TITLE
Add go cardless buttons to donation page and giftaid page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#231]
Buttons or links for:
£5 per month no giftaid: https://pay.gocardless.com/AL0000RGH6R8YG
£5 per month giftaid: https://pay.gocardless.com/AL0000RGJ58C0F
£2 per month no giftaid: https://pay.gocardless.com/AL0000RGJG64XT
£2 per month giftaid: https://pay.gocardless.com/AL0000RGJNABMW
£100 per  month no gift aid:  https://pay.gocardless.com/AL0000S11MEQKA
£100 per  month gift aid: https://pay.gocardless.com/AL0000S11PPEHZ
£50 per  month no gift aid: https://pay.gocardless.com/AL0000S11VTQRG
£50 per  month gift aid: https://pay.gocardless.com/AL0000S11ZFNDC
£20 per  month no gift aid: https://pay.gocardless.com/AL0000S125A118
£20 per  month gift aid: https://pay.gocardless.com/AL0000S1289RZV
£10 per  month no gift aid: https://pay.gocardless.com/AL0000S12A2FGE
£10 per  month gift aid: https://pay.gocardless.com/AL0000S12E1DF6
To pay another amount, or to pay in Euro or Swedish Krone, please contact us and we will manually set up the payment.

**Comment by PatReynolds** [comment]
Perhaps as table separating giftaid and non gift aid?  Vertical if horizontal wraps badly on mobiles

**Comment by DeniseColbert** [comment]
Free UK Gen green
