### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#24]
Shaw Trust - 2/8/16

**Comment by PatReynolds** [comment]
Signed documents now on the drive.

*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
