### ISSUE TITLE
Donate text

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#245]
Review/revise across all websites

**Comment by DeniseColbert** [comment]
Ideas for FreeREG: https://docs.google.com/document/d/1xavXbF_rL7GNlx5tNlJobVIPFpmwz_7Dfwl4DMl4y68/edit#

**Comment by PatReynolds** [comment]
Consult with FreeBMD and FreeCEN on their donate lines / potential to incorporate changing donate on search for FreeBMD.

**Comment by PatReynolds** [comment]
Denise to make 'generic' and individual project sections. Pat to add to Trac, Denise to FreeCEN waffle

**Comment by DeniseColbert** [comment]
My part of this is done

**Comment by PatReynolds** [comment]
Allocated to trac#524
