### ISSUE TITLE
Survey of those who sign into FreeREG but don't transcribe

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#254]
Denise to talk to Mark James and Jo about onboarding and training

**Comment by DeniseColbert** [comment]
Contact Steve re Mark and getting survey out

**Comment by DeniseColbert** [comment]
Emailed 9/5/17

**Comment by DeniseColbert** [comment]
Could you please review and finalise survey? See email 7/6/17

**Comment by DeniseColbert** [comment]
Survey ready

**Comment by DeniseColbert** [comment]
Draft email, send to Pat to check (bcc undisclosed recipients)

**Comment by DeniseColbert** [comment]
Email ready to go pending approval of draft text sent to Pat 11/9

**Comment by DeniseColbert** [comment]
Sent to 430 users, 13/9/17
