### ISSUE TITLE
Gifts and hospitality policy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#264]
Pat to look for draft

**Comment by DeniseColbert** [comment]
...and point Denise at it

**Comment by PatReynolds** [comment]
corporategiftsandhospitality.pdf in governance / misc documents.

**Comment by PatReynolds** [comment]
Also create gifts and hospitality register

**Comment by DeniseColbert** [comment]
Done. In Community --> Policies

**Comment by PatReynolds** [comment]
Pat to check

**Comment by PatReynolds** [comment]
Looks good - I have a couple of questions.

**Comment by DeniseColbert** [comment]
No response from Edward Philips, is it something we can ask Tim or someone else from Moorcrofts?

**Comment by DeniseColbert** [comment]
I thinkthis is done now that we've had clarification from Tim?
