### ISSUE TITLE
Gift Aid

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#27]
Gift Aid: we are now claiming gift aid through Charity Choice. We have in place the mechanisms on paypal to claim gift aid (the button served is determined by whether or not the gift aid box is ticked). The wording on donations and gift aid needs improving, harmonising across sites. A gift aid form for non-paypal donors is being created on www.freeukgen.org.uk. For decision: should we place a ‘donate’ link on the bottom of search results pages?

**Comment by DeniseColbert** [comment]
On the www.freeukgen.org.uk website, I've started to build a form to collect the GiftAid data if someone doesn't want to use PayPal or Charity Choice (both of which collect it for us).  Could you have a go at completing that, and have a look at the text on the giftaid page there, and the pages on the other websites to see if you can make it flow better/be more understandable?

**Comment by DeniseColbert** [comment]
Form completed- should I place it on the Donate page of the website?

**Comment by PatReynolds** [comment]
Yes please - save as draft and let me know it is ready to test.

*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by DeniseColbert** [comment]
Hi Pat,

I updated the whole of the donate page and included the form a few weeks
ago. It's ready for test with a view to assessing if it could do with even
more streamlining. It's saved as a draft.

Kind regards,

Denise

**********
*Denise Colbert*
Engagement Co-ordinator

E: denise.colbert@freeukgen.org.uk
T: +44 7825 338014
W: http://www.freeukgenealogy.org.uk/

Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484.

VAT registration: 233 0105 70

**Comment by DeniseColbert** [comment]
This is the only information in the giftaid pdf that isn't in the form- how should we present it?

Please notify the charity if you:
 want to cancel this declaration
 change your name or home address
 no longer pay sufficient tax on your income and/or capital gains
If you pay Income Tax at the higher or additional rate and want to receive the additional tax relief due to you, you must include all your Gift Aid donations on your Self-Assessment tax return or ask HM Revenue and Customs to adjust your tax code.

**Comment by DeniseColbert** [comment]
The background for the giftaid image is a variant of the brown used in the FreeREG logo. It's not used at all on the main site (apart from where FR logo is) so should I change it?

**Comment by PatReynolds** [comment]
Please put text on the form, below the 'submit' button.

Background colour: less urgently, I think it needs to be lower saturation.

**Comment by PatReynolds** [comment]
Please split out the first line of address from the rest of address, and also add an 'email' field.

**Comment by DeniseColbert** [comment]
I've split up the address info.

I can add the text below the submit button but it would be on the donate page rather than the form.  Have a look below the form on draft 2 of the page

**Comment by PatReynolds** [comment]
That looks good.  Can you add an email address for contacting us - info@, perhaps?

**Comment by DeniseColbert** [comment]
Done- please check and make live if you're happy.

**Comment by PatReynolds** [comment]
That's great.

Many thanks!

Best wishes,

Pat

*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by DeniseColbert** [comment]
I removed the info from the Donate page that Alex used for the Home page. It's draft 3 if you'd check it over. Wondering if we should keep paragraph 2 or delete that too?

**Comment by PatReynolds** [comment]
Thanks, Denise.  I've published it as is.

Yes, I think the second paragraph can go (or perhaps move down into the
Volunteering paragraph?

Best wishes,

Pat

*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by DeniseColbert** [comment]
Added it to volunteering paragraph, saved page as draft 3 for you to check and publish.

**Comment by DeniseColbert** [comment]
Is draft 3 ok @PatReynolds ?

There is a new donation platform: https://wonderful.org/ looks like aimed at people who raise money for charities but may also work for us. They take NO FEES! 100% of donations go direct to charities.

**Comment by DeniseColbert** [comment]
Noticed I had another pending draft (draft 2) which was the one we're discussing earlier in this ticket, it hadn't been published. I have now incorporated those additions into draft 3 so if you're happy, you can publish that one and delete draft 2.

**Comment by PatReynolds** [comment]
Checked and published.


*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
