### ISSUE TITLE
Finish unreg charity Minutes book

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#281]

**Comment by DeniseColbert** [comment]
Query regarding 2017_02_21 Minutes - dates don't match. Have these been formally approved for inclusion into the minute book?

**Comment by PatReynolds** [comment]
Yes. Please add to the agenda for 6th May.

Pat Reynolds
Executive Director, Free UK Genealogy

On 7 Apr 2017 2:52 p.m., "DeniseColbert" <notifications@github.com> wrote:

Query regarding 2017_02_21 Minutes - dates don't match. Have these been
formally approved for inclusion into the minute book?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeUKGen/Coordination/issues/281#issuecomment-292542130>,
or mute the thread

**Comment by DeniseColbert** [comment]
Done and in folder. Title: Final FreeUKGen Minute Book
