### ISSUE TITLE
Investigate crowd sourcing for film and fiche

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#287]
As alternative to volunteer getting money from group of transcribers.

Other uses????

**Comment by PatReynolds** [comment]
See https://www.nesta.org.uk/blog/how-find-right-crowdfunding-platform-your-good-cause for listing of platforms.  Hubub was the one I was thinking of

**Comment by PatReynolds** [comment]
Pat to look for the vols wanting to buy fiche - to invite to platform

**Comment by PatReynolds** [comment]
Emailed S&N 2/8/2019

**Comment by PatReynolds** [comment]
Wrote s&n 7/11/2019
@DeniseColbert I have set up the 1861 Suffolk Census - please proof and make live.

**Comment by DeniseColbert** [comment]
This sentence... "The monies raised will be used to provide volunteer transcribers with the images to transcribe. " Could we add in exactly what we'd be purchasing?

E.g. ... The monies raised will be used to purchase the 1861 census microfiche rolls from Suffolk Archives. We will then be able to give extracted images to our highly experienced volunteers to transcribe.

**Comment by PatReynolds** [comment]
Live 21/11/2019 for 3 months.
