### ISSUE TITLE
Create a stock set of images etc. for communications

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#289]
Andrew is beginning to work on using logos to make some images we can draw on in different situations. I have asked him to create 'celebratory' media for each project, and some ideas for the launch of FreeCEN2. Also, he is creating some images using BMD certs. Any suggestions of other things we could do with are welcome.

**Comment by DeniseColbert** [comment]
There is a need for photographs to be included in these. And any ideas appropriate/relevant to what we do / are about.

**Comment by PatReynolds** [comment]
It would be good to have some with people in.  Hands on keyboards, that sort of thing.
