### ISSUE TITLE
Family Tree mag FreeREG article

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#307]
Hello, my name's Rachel Bellerby and I work on Family Tree magazine (www.family-tree.co.uk) We're always looking for interesting new content for our website and I'm writing an article for the magazine about how people should consider becoming a volunteer on a family history project. To complement this, we're hoping to publish a guest article and I wondered whether one of the FreeReg team might be willing to write a short piece (around 400-600 words) for our website about the benefits of volunteering to become a transcriber for you, what the work involves, how it can benefit the volunteer, etc. We can then publish this on our website, along with a link through to your website so that people can register to volunteer with you if they like the idea. In terms of timings, we'd be happy to fit in with your schedule and could get the piece onto our site within a day or two of receiving it from you. If this might be of interest, please do get in touch. Kind regards Rachel Bellerby 0113 2002922

**Comment by Captainkirkdawson** [comment]
We should respond positively

**Comment by Captainkirkdawson** [comment]
Are we going to respond?

**Comment by DeniseColbert** [comment]
I called Rachel and left a message; will chase up later today.

**Comment by DeniseColbert** [comment]
Rachel would like to open this up to the other projects also. For FreeREG, Sandra has indicated that she would be happy to write the article.

**Comment by DeniseColbert** [comment]
Sandra is currently working on this.

**Comment by DeniseColbert** [comment]
@CommsCoord How is this going Sandra?

**Comment by CommsCoord** [comment]
Hi Denise

I have spoken with Rachel and she has told me what she needs, and I am
getting on with it in snatches between dealing with FR Comms and my ​family
being here. Rachel is aware of all this and she has said that anytime we
submit will be fine. Will be looking to have something to her in draft by
end of month, and leaving time for any proofing and adjustments that may
need to be done.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Kind regards
The Communications Team

**Comment by DeniseColbert** [comment]
Great, thanks Sandra. Let me know if I can help with anything.

**Comment by DeniseColbert** [comment]
https://www.family-tree.co.uk/how-to-guides/getting-started/freereg-genealogy-website-find-your-ancestors-for-free
