### ISSUE TITLE
Publicity for launch of FreeCEN2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#313]
Launch to include push for new volunteers (with transcribers agreement)

**Comment by PatReynolds** [comment]
Pat to send Denise Communication Plan example.

**Comment by DeniseColbert** [comment]
Comms plan done.

Stories created.

Sarah Hopton has sent Pat invoice for ad in Family Tree Magazine

**Comment by PatReynolds** [comment]
Invoice not received.  Please ask Sarah to resend (cc Helen).

**Comment by DeniseColbert** [comment]
Have done so- but Sarah is on leave until 24/7

**Comment by DeniseColbert** [comment]
Sarah emailed that this was complete
