### ISSUE TITLE
Recruitment of new TPM

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#32]

**Comment by Captainkirkdawson** [comment]
What or who is a TPM?

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
Technical Project Manager - i.e. Sean.



*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
