### ISSUE TITLE
Add 'Donate' and change 'Blog' to 'News' to sections of FreeUKGen

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#336]
Add between Home and Blog 
Change 'Blog' to 'News' (call 'blog posts' 'articles')

**Comment by DeniseColbert** [comment]
![image](https://cloud.githubusercontent.com/assets/19173257/25187484/0efedd00-251b-11e7-9cc8-4a771643ae77.png)

**Comment by DeniseColbert** [comment]
![image](https://cloud.githubusercontent.com/assets/19173257/25187588/5e503340-251b-11e7-98ad-643cd500b047.png)

**Comment by bev-fc** [comment]
You can do it from admin page

![20170430_002](https://cloud.githubusercontent.com/assets/22349799/25566394/b28301e4-2da5-11e7-9385-3117e965bdda.jpg)
![20170430_003](https://cloud.githubusercontent.com/assets/22349799/25566396/b2849e64-2da5-11e7-94fe-34b8566c0a77.jpg)
![20170430_004](https://cloud.githubusercontent.com/assets/22349799/25566395/b2832610-2da5-11e7-9e0a-6fb369ba531c.jpg)
![20170430_005](https://cloud.githubusercontent.com/assets/22349799/25566416/2454a430-2da6-11e7-9ae0-9ec68f339580.jpg)

**Comment by PatReynolds** [comment]
Thanks.  Donate tab added successfully.  I have followed instructions for Blog  >> News, but it does not seem to have worked.  @DeniseColbert can you check both are fine?

**Comment by DeniseColbert** [comment]
I was just doing working on this; I wonder if that was why you couldn't make the change. I'll check.

**Comment by DeniseColbert** [comment]
No, the link stays as Blog but the title is News when I double-click. I've cleared my cache and no change.

![image](https://cloud.githubusercontent.com/assets/19173257/25613862/b34d524a-2f27-11e7-80c7-6c6c5ad2cbd5.png)

**Comment by bev-fc** [comment]
Sorry my mistake, I missed one step before changing 'blog' to 'news' in settings -> header

![20170502_001](https://cloud.githubusercontent.com/assets/22349799/25624379/26e92ec8-2f27-11e7-8b72-39006800c283.jpg)
![20170502_002](https://cloud.githubusercontent.com/assets/22349799/25624380/26f5dd58-2f27-11e7-9191-194d8222d88c.jpg)
![20170502_003](https://cloud.githubusercontent.com/assets/22349799/25624378/26e91b7c-2f27-11e7-8ba0-8b3aa1bcf860.jpg)

Now please redo the last step and click save again.

**Comment by DeniseColbert** [comment]
Thank you Bev, I did that with no problem.

**Comment by DeniseColbert** [comment]
Hi @bev-fc 
Can we change the slug to news also? Just for completeness. I looked but can't see a clear way.

![2017-05-08](https://cloud.githubusercontent.com/assets/19173257/25807053/6e66041c-33fd-11e7-898a-07630d65380b.png)

**Comment by bev-fc** [comment]
Hi @DeniseColbert , we need to do this together. First, your turn: 

![20170518_003](https://cloud.githubusercontent.com/assets/22349799/26200336/9d0bfbdc-3b9b-11e7-8487-a33d4085eeb3.jpg)

![20170518_004](https://cloud.githubusercontent.com/assets/22349799/26200343/a29e9de8-3b9b-11e7-9ddf-057ae161ddb0.jpg)

![20170518_005](https://cloud.githubusercontent.com/assets/22349799/26200345/a60d5dfc-3b9b-11e7-9b6e-cc833ac4293d.jpg)

![20170518_006](https://cloud.githubusercontent.com/assets/22349799/26200347/a95889f0-3b9b-11e7-884d-104b811286d5.jpg)

![20170518_007](https://cloud.githubusercontent.com/assets/22349799/26200353/acf5ee18-3b9b-11e7-87ac-c42999fb2f99.jpg)

![20170518_008](https://cloud.githubusercontent.com/assets/22349799/26200357/b025169a-3b9b-11e7-83cc-f65f296631cf.jpg)

![20170518_010](https://cloud.githubusercontent.com/assets/22349799/26200365/b9be4032-3b9b-11e7-855f-7328ee8878e4.jpg)

![20170518_011](https://cloud.githubusercontent.com/assets/22349799/26200370/c002cd46-3b9b-11e7-85af-0bb398a77b07.jpg)

Then my turn to modify /home/apache/hosts/craft/config/routes.php
