### ISSUE TITLE
Live Preview facility on Craft showing disabled content

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#344]
See screenshot below

**Comment by DeniseColbert** [comment]
![image](https://cloud.githubusercontent.com/assets/19173257/25432577/d8ca0360-2a7c-11e7-8de4-9157d56ee086.png)

**Comment by DeniseColbert** [comment]
The disabled content below the image shown in the snip is also showing in LP mode.

**Comment by bev-fc** [comment]
default is both disabled/enabled entries are shown in live preview mode, only enabled entries are shown on web, you can use www.freeukgenealogy.org.uk/about/pages/other-ways-to-help to view the enabled entries.

**Comment by bev-fc** [comment]
default is both disabled/enabled entries are shown in live preview mode, only enabled entries are shown on web, you can use www.freeukgenealogy.org.uk/about/pages/other-ways-to-help to view the enabled entries.

**Comment by PatReynolds** [comment]
Thank you, Bev.
