### ISSUE TITLE
Create Facebook groups for volunteers

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#346]
To foster a sense of community

**Comment by allanraymond** [comment]
FreeBMD already have a Facebook page.

**Comment by DeniseColbert** [comment]
Ask REG and CEN for volunteers to moderate groups.

Consider a 'Core' group

**Comment by DeniseColbert** [comment]
Ask FreeBMD if they may prefer a volunteer-only facebook group

**Comment by allanraymond** [comment]
I wish to retain the situation we have at the moment for the FreeBMD facebook group, Having it open for anyone to join the Facebook page is another avenue to entice individuals to join and transcribe for FreeBMD. I see no advantage in having it as volunteer only group.

**Comment by DeniseColbert** [comment]
Sorry- 'prefer' could be misleading here. We aren't looking to change the existing group Allan, but offer an alternative which is just for volunteers, if they would deem it useful.

**Comment by allanraymond** [comment]
No problem, however I see no advantage in having a second FreeBMD but volunteer only facebook page.

**Comment by PatReynolds** [comment]
We should ask  - but we should be prepared to find everyone is happy with the status quo.  Allan - the idea was suggested to us as a way of fostering a sense of community in the projects, but the FreeBMD Facebook group may well be already doing that.

**Comment by allanraymond** [comment]
There is no logic in having two FreeBMD Facebook pages, the existing one works fine and serves the need of our volunteers and those just interested in FreeBMD.

I have no intention of asking.

**Comment by PatReynolds** [comment]
@DeniseColbert to work with Ann and Helen (and anyone else interested) in setting up the FreeREG group

**Comment by DeniseColbert** [comment]
Group created, admins added. Discussion ongoing re. set up of group. Possibility of whole page community TBD with Pat

**Comment by PatReynolds** [comment]
check on whois.com
