### ISSUE TITLE
Improve onboarding process within FreeREG to help address high dropout rate

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#349]
From AB meeting 24/04/17
* Show prospective volunteers examples of the materials within each project and let them choose the project that they prefer
* Communicate that some batches may take longer than others and not to feel the pressure of time too keenly
* Present example transcription material in an interactive format that may demonstrate to volunteers that they actually can (or cannot) read text that looks difficult.

E1 U6 S10 C5: P22

**Comment by PatReynolds** [comment]
Draft mock-ups now at Projects>FreeREG>Mock-ups @DeniseColbert can you improve/check/proof?

**Comment by DeniseColbert** [comment]
They look good, placed a comment on one

**Comment by PatReynolds** [comment]
Send to Steve.
