### ISSUE TITLE
Use second advertiser?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#351]
E.g. yahoo?

**Comment by PatReynolds** [comment]
Anna to check adsense conditions.  Pat then to set up (?media.net).

**Comment by AnnaKle** [comment]
http://www.media.net - good AdSense substitute. We can use it on http://www.freeukgenealogy.org.uk.
Google seems fine with most networks as long as we don't style the ads to look like theirs.
https://support.google.com/adsense/answer/9728?hl=en-GB

**Comment by PatReynolds** [comment]
Medianet seems to be contextual only. But signed up anyway - may use on FUG website.

**Comment by DeniseColbert** [comment]
Is that allowed in Google Grant terms?

**Comment by PatReynolds** [comment]
I have asked the community if any gg holder is doing this.  I'm thinking of amazon and barnes and noble, partly as some folk have nooks, and partly because some folk avoid amazon on ethical grounds.
