### ISSUE TITLE
Missing dash after /author/ http://www.freeukgenealogy.org.uk/blog/authorpatreynolds/

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#352]

**Comment by bev-fc** [comment]
Pat, could you show me how did you get http://www.freeukgenealogy.org.uk/blog/authorpatreynolds/ instead of http://www.freeukgenealogy.org.uk/blog/author/patreynolds/, through clicking what?

**Comment by bev-fc** [comment]
@AnnaKle @PatReynolds From the file I received, I still couldn't figure out how did you get  http://www.freeukgenealogy.org.uk/blog/authorpatreynolds  from  http://www.freeukgenealogy.org.uk/blog/author/patreynolds/ , how can I simulate the problem? what do you want me to do?
[Dead.Link.Checker.reports.pdf](https://github.com/FreeUKGen/Coordination/files/998056/Dead.Link.Checker.reports.pdf)

**Comment by DeniseColbert** [comment]
I think this is done now - there is a slash. However, new story on author links showing posts by all authors.
