### ISSUE TITLE
Look for plugin to remind slack users of upcoming deadlines

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#366]

**Comment by richpomfret** [comment]
Testing github & waffle integration - but looks like we have a plethora of 'apps' to choose between i.e. https://slack.com/apps/A0HBTUUPK-to-do-bot

**Comment by richpomfret** [comment]
Installed (https://freeukgenealogy.slack.com/apps/A0HBTUUPK-to-do-bot) which allows us to create simple tasks and assign/give deadlines. To test whether this can be used for general deadlines/assign tasks to 'teams'.
