### ISSUE TITLE
Test Broadcast of Conferences

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#37]
Need to design setup for camera rather than phone based conference broadcasting, and test

**Comment by DeniseColbert** [comment]
For September meeting, I will need to broadcast via the youtube account of FreeUKGen
For Advisory Board meetings etc. my own account will do I think.

**Comment by PatReynolds** [comment]
Pat to set up a test hangout on freeukhistory

**Comment by PatReynolds** [comment]
Do you still need me to do this for next Advisory Board meeting?

**Comment by DeniseColbert** [comment]
No, AB meeting is fine going from my account. It's the Sept meeting we need it to go from the account linked to our YouTube channel. (freeukhistory?)
