### ISSUE TITLE
Advisory Board July meeting note

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#370]
Meeting in development calendar

**Comment by DeniseColbert** [comment]
@PatReynolds  and trustees now added (erroneously added Executive@ rather than 'trustees' contact group)

**Comment by DeniseColbert** [comment]
Paperwork needs completing

**Comment by PatReynolds** [comment]
@DeniseColbert is there anything more for me to do now?

**Comment by DeniseColbert** [comment]
It just needed checking so if that's done, that it I think.

**Comment by PatReynolds** [comment]
Ty, @DeniseColbert good to go now without amendment.

**Comment by DeniseColbert** [comment]
You linked to it in the agenda which I sent yesterday, is there anything for me to do now?

**Comment by PatReynolds** [comment]
Can you check that I linked to the correct note, and not the one for the meeting before?  Otherwise, nothing to do.

**Comment by DeniseColbert** [comment]
Done :)
