### ISSUE TITLE
Communication Plan FC2

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#372]
In Communications folder

**Comment by DeniseColbert** [comment]
Denise to finish editing

**Comment by DeniseColbert** [comment]
Get prices for advertising

**Comment by DeniseColbert** [comment]
Done, ready for review

**Comment by DeniseColbert** [comment]
Complete. Now in FreeCEN2 launch folder

**Comment by Captainkirkdawson** [comment]
Would it be possible to have access to the folder to have a scan?

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by DeniseColbert** [comment]
Done :)
