### ISSUE TITLE
Draft role description and Set up / write agenda for next Policy Group meeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#373]
Policy on area of coverage Eire? Pre-partition Ireland? UKOT? Etc.
Policy on coverage of non-genealogical issues on social media.

**Comment by DeniseColbert** [comment]
For SM ref. email 24/5

**Comment by PatReynolds** [comment]
Policy on advertiser types to bar, if any.
Re-invigorate Place discussions
Write and circulate to Trustees chair's role description

**Comment by PatReynolds** [comment]
Also: storage of images and other originals
