### ISSUE TITLE
Rearrange donation pathway on FUG site

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#375]
Shorten journey by having Gift Aiders stay on main page

**Comment by DeniseColbert** [comment]
Done, checked and made live, as content not changed. A quick check over would be good to confirm though @PatReynolds

**Comment by PatReynolds** [comment]
If you want to donate money, and are a UK tax payer, we can reclaim 25% extra - at no cost to you - using the Gift Aid scheme.  The links and buttons on this page assume you are giving us permission to claim Gift Aid. If when you have read the details, you decide you are not eligible, or prefer not to make a Gift Aid declaration, please click here  to make a donation WITHOUT Gift Aid.

**Comment by PatReynolds** [comment]
Paypal: remove Giftaid Tickybox, and ensure it is the GiftAid button

**Comment by PatReynolds** [comment]
Enable bank transfer and cheque with link to Gift Aid form.

**Comment by PatReynolds** [comment]
Make similar changes on the without giftaid page

**Comment by DeniseColbert** [comment]
Main donate page done BUT- I removed the tickybox code and placed it in a separate (disabled) html box. But I'm unsure if the code that's left is 'With Gift Aid' paypal code. I can't find the code for the paypal button on the 'without Gift Aid' page- it just appears as a button. Can you check please Pat?

**Comment by DeniseColbert** [comment]
Without Gift Aid page also done.

**Comment by PatReynolds** [comment]
MyDonate now ask the giftaid question, so text needs changing on our website to reflect this.

**Comment by PatReynolds** [comment]
Paypal buttons: the one on the main (with gift aid) page is actually the without giftaid button (and the image is missing).  It also appears (correctly) on the without giftaid page.

The with giftaid button:
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="NWFG3LLZGKBPJ">
<input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>

**Comment by DeniseColbert** [comment]
I've sorted the buttons/code.

Missing Image: do you mean the Gift Aid one? Should I make another with our more accessible colours?

GA declaration link now fixed

**Comment by PatReynolds** [comment]
All working perfectly now / images correct.  Closing, ty.
