### ISSUE TITLE
Add FUG newsletter sign-up form to the project webites

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#377]
FreeREG & CEN initially, & BMD if possible (if not, then when reskinned)

**Comment by DeniseColbert** [comment]
To be discussed with Pat at next meeting

**Comment by PatReynolds** [comment]
Discuss where to place (e.g. on side bar, in advert slot

**Comment by DeniseColbert** [comment]
Closing this as I've opened a story on FreeBMD2

**Comment by Captainkirkdawson** [comment]
Why closed ? nothing has been done on the projects to be my knowledge. Surely this should be systemwide

**Comment by DeniseColbert** [comment]
I opened a story on FreeBMD2 so placement can be considered by UXers then implemented there, and fed into REG & CEN
