### ISSUE TITLE
Advertise for volunteer MACBMD developer

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#388]

**Comment by DeniseColbert** [comment]
Ad now up on Social Coder, posts on SM

**Comment by PatReynolds** [comment]
Pat to advertise on code4lib

**Comment by PatReynolds** [comment]
done, but I think recruit@freeukgenealogy.org.uk will get the email needed to make it live.  could @DeniseColbert or @richpomfret make it live if they get the email?

**Comment by DeniseColbert** [comment]
No email received as yet, but will do if one arrives.

**Comment by PatReynolds** [comment]
Check that it is live

**Comment by PatReynolds** [comment]
Confirmed live: closing issue.
