### ISSUE TITLE
FC2 Launch: Design flyers & posters

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#399]

**Comment by DeniseColbert** [comment]
Hangout tba

**Comment by DeniseColbert** [comment]
Messages:
Are you paying for something you can get for free?
FreeCEN2 is our *new-look* website. 
We need your feedback to make it even better/
Give us your feedback now, to help us make it even better

**Comment by lindseyprice** [comment]
Hi folks, 

I've been working on the copy for the posters. What do you think?

Main text: Are you paying for records you could see for free?

Body text: FreeCEN2 gives you free access to census records for England, Scotland and Wales. Share your feedback now to help make this new-look website even better.  

https://freecen2.freecen.org.uk

**Comment by simonebonnett** [comment]
I think it's great - to the point

**Comment by DeniseColbert** [comment]
Tweaked just a little:

Main text: Are you paying for records you could see for free?

Body text: FreeCEN2 gives you free access to census records for England, Scotland and Wales. Share your feedback with us to help make our new-look website even better.

https://freecen2.freecen.org.uk

**Comment by DeniseColbert** [comment]
https://drive.google.com/open?id=0BxZmlI0ZQEEZYzhBVWdUOXpMdG8
