### ISSUE TITLE
Donation campaign (SM)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#403]
Mini-campaign to highlight new donation streams (MyDonate & Go Cardless)

Plan for major campaign when Legacy and In Memoriam systems are in place

**Comment by DeniseColbert** [comment]
Still to be highlighted in mini-campaign: easyfundraising; easysearch; Go Cardless

**Comment by simonebonnett** [comment]
Will be separate mini campaigns - give us greater traction over a longer period of time

**Comment by DeniseColbert** [comment]
Do we have posts planned to mention MyDonate and Go Cardless?

**Comment by simonebonnett** [comment]
Yes I aiming to highlight these after the Freecen launch. Have been highlighting easyfundraising. Not a lot of uptake across SM - any increase in donations via this platform?

**Comment by PatReynolds** [comment]
MyDonate shows a couple of periods of activity 23 June and (declining) few days after, Then another batch (steady) 7-10 July.
![mydonate june - july 2017](https://user-images.githubusercontent.com/6338822/28263949-c2938c20-6ae0-11e7-86a2-d2cc2c9bd568.PNG)

One person joined gocardless 16th June.

Paypal has continued unchanged through June and July - 0, 1, 2, or 3 donations per day, no pattern.

**Comment by DeniseColbert** [comment]
This is July's activity on easyfundraising:

![image](https://user-images.githubusercontent.com/19173257/28308363-dc55b580-6b9d-11e7-891a-62f81098467a.png)
