### ISSUE TITLE
Reorganise volunteer page of main website

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#404]
Make subpages for types of volunteering
Create buttons for actions/conversions

**Comment by DeniseColbert** [comment]
Subpages created (in draft) @PatReynolds  to check/make suggestions

**Comment by DeniseColbert** [comment]
Transcriber subpage enhanced with bulleted reasons:
![image](https://user-images.githubusercontent.com/19173257/27687706-c684e60e-5ccf-11e7-811d-84c256dd3dcc.png)

**Comment by PatReynolds** [comment]
maybe the last bullet point needs expansion - 'being online' can be read as 'we have a website'.  Maybe something like 'increasingly enabling volunteering online'

**Comment by DeniseColbert** [comment]
Made that change.

Also played with Core subpage:
(Bold magenta lines will be one or the other- disabled blocks appear in live preview mode)

![image](https://user-images.githubusercontent.com/19173257/27690367-1a5e77d2-5cd9-11e7-9a69-849cc1fd78f1.png)

**Comment by DeniseColbert** [comment]
@MikeLi1 Volunteering main page (Draft 1) is ready  for buttons and for @PatReynolds  to check text

**Comment by DeniseColbert** [comment]
Button labels:

Volunteer Transcriber opportunities
*Core* Volunteer opportunities
Tech Volunteer opportunities
Management Volunteer opportunities

http://www.freeukgenealogy.org.uk/admin/entries/pages/284-volunteer/drafts/45

**Comment by PatReynolds** [comment]
Checked and made live.

Maybe the text on the buttons could be more like an invitation?

**Comment by DeniseColbert** [comment]
Thanks Pat. Can you give an example of text you have in mind?

@MikeLi1 Apologies, I forgot to discuss the 'Apply' button/s on each page:

-- Transcriber page - 3 buttons, one for each project, links are on the page already

-- Core Volunteer page - for now, one button that leads to either recruit@freeukgenealogy.org.uk or an application form (that is very nearly ready, but not quite) TBD

-- Management volunteer page - a button for trustee applications that goes to Pat's email address (and one for Advisory Board if it's decided this is a good place for it - @PatReynolds? TBD

-- Tech volunteer opportunities - a button that goes to recruit@freeukgenealogy.org.uk or a n application form (again, this one isn't quite ready either) TBD

**Comment by DeniseColbert** [comment]
Management opportunities page updated (draft 1) Pat to check
Trustee and AB pages made, again Pat to check

Pat to advise on button text - easily changed.

**Comment by DeniseColbert** [comment]
@PatReynolds when you've checked the SEO & SM volunteer pages, could you make Draft 1 of Core Volunteer page live please? It has the buttons for those roles.

**Comment by PatReynolds** [comment]
All good. Draft published, SEO and Social Media pages made live.

**Comment by DeniseColbert** [comment]
Pat, could you check Management Opportunities page, Draft 1 - also Trustee and ADv Bd pages (not yet live)?

**Comment by PatReynolds** [comment]
Draft checked and made live, but subpages are not up to date - will need to revise Trustee page after I meet with Richard on Friday, and I think you need to edit the Advisory Board one (but couldn't see a draft).

**Comment by DeniseColbert** [comment]
Advisory board draft created - only seeking  Archives expertise right now as we're seeking internally / from previous applicants for other areas

**Comment by PatReynolds** [comment]
@patreynolds to check Advisory board

**Comment by PatReynolds** [comment]
Queried @DeniseColbert 12/12

**Comment by DeniseColbert** [comment]
@PatReynolds Should I make your draft of Trustee page live?

**Comment by PatReynolds** [comment]
Yes, please.  Also link from Trustee and Advisory Board pages.

**Comment by DeniseColbert** [comment]
Page live. Trustee page drafted with button (and Billy removed) but getting Bev's help with  alignment. 

AB page draft created with button added that goes to application page. @PatReynolds could you check Draft 1 of AB application page as well as these 2 drafts, and make live?

**Comment by PatReynolds** [comment]
Trustee board checked and published, thank you.

I thought the Advisory Board in one sentence read too much like the advertisement than a description of the board, so have changed it and left for you to approve.

Also, added a deadline to Trustee Recruitment.
