### ISSUE TITLE
Video for September Meeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#408]
Need to practice, and issue instructures

**Comment by PatReynolds** [comment]
Pat to test her camera. Simone bringing hers.  Denise and Pat to test recording with showmore.

**Comment by DeniseColbert** [comment]
Test hangouts on air with Pat

**Comment by DeniseColbert** [comment]
@simonebonnett Possibly Facebook live?

**Comment by DeniseColbert** [comment]
Facebook live not appropriate as HoA will cover what we need.

**Comment by PatReynolds** [comment]
HoA appears to be Facebook Live.  I think picture quality is ok, but we will want to use a radio mike.
