### ISSUE TITLE
Software Development Agreement

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#411]
Our preference is for Open, but we may need assignment in specific cases.

**Comment by PatReynolds** [comment]
Draft: https://docs.google.com/a/freeukgenealogy.org.uk/document/d/1wV4pi_8v-0ySh5d-9HmteJW9-UHJnGedwR30gBPfPa0/edit?usp=sharing

Probably better as 'making open source' than a licence.  Possible with a licence for non-code contributions, such as documentation and front end design.

**Comment by DeniseColbert** [comment]
Proofed, but will proof again once finalised
