### ISSUE TITLE
Check email consent on fundraising websites

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#427]
MyDonate has consent tickybox.
GoCardless appears not to have the consent to give us the data in the first place, but is (see email 12/7/2017) 
PayPal has the consent to give us the data, but only for us to use it "to complete your transaction".
Need to add consent to Paypal and GoCardless on our website.
Economic 0, urgency 10, strategic 10, cost 6: priority 26

**Comment by PatReynolds** [comment]
Need to check Recycle charity

**Comment by DeniseColbert** [comment]
Is there something for me to add to the website re. Paypal & Go Cardless?

**Comment by PatReynolds** [comment]
Gather consent on thankyou landing page (tickybox for newsletter, for other emails, email address).

Could also use the thankyou page for gathering Gift Aid consent, to streamline user journey.

**Comment by PatReynolds** [comment]
Need to check Charity Choice and Easy Fundraising
