### ISSUE TITLE
Change button colour to purple on FreeCEN landing page

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#428]
Here:
http://www.freeukgenealogy.org.uk/admin/entries/pages/1007-freecen

Purple: #591D77

**Comment by bev-fc** [comment]
Hi @DeniseColbert, what's the difference between #428 and #429 ?

**Comment by DeniseColbert** [comment]
Sorry Bev, the button I'm referring to here is the 'Search' button that is currently 'Gold' in the code.

**Comment by bev-fc** [comment]
Hi @DeniseColbert , you can change within the html block, from data-color="gold" to data-color="purple"

**Comment by DeniseColbert** [comment]
I did that but the colour seems to be magenta rather than purple:

![image](https://user-images.githubusercontent.com/19173257/28411790-d952ecfc-6d39-11e7-8e6f-ab8ce4067ca3.png)

**Comment by DeniseColbert** [comment]
Hover state is more like purple but still different to #591D77:

![image](https://user-images.githubusercontent.com/19173257/28415336-2254281e-6d47-11e7-980c-93941a91beeb.png)

**Comment by bev-fc** [comment]
Hi @DeniseColbert , I modified from css file, it is #591d77 now, for hover color, it is supposed to be different from the original color, if you want another hover color than the current one, can you ask the person who wrote the ladda.min.css file for a new color code that matches the requirement? I can then modify the css file.

**Comment by DeniseColbert** [comment]
Many thanks Bev. I am still seeing the magenta colour instead of purple though- is there something I need to do to get the colour to correct?

The hover state is fine, that was just for your info
