### ISSUE TITLE
Add purple to Craft 'Highlight' block colours

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#429]
#591D77

**Comment by bev-fc** [comment]
Hi @DeniseColbert , if you want to do it by yourself, here is the steps: 

1. go to settings -> fields -> Article -> Highlight -> Colour
![20170714_003](https://user-images.githubusercontent.com/22349799/28214466-549da148-6878-11e7-9ac0-e3f56006d85e.jpg)

![20170714_004](https://user-images.githubusercontent.com/22349799/28214481-69b7c694-6878-11e7-8a98-c2869c43c486.jpg)

![20170714_005](https://user-images.githubusercontent.com/22349799/28214499-77ca31b8-6878-11e7-8428-e568ed00cabb.jpg)

![20170714_006](https://user-images.githubusercontent.com/22349799/28214505-834741e8-6878-11e7-8c4f-fcaea18b5edc.jpg)

2. click "Add an option"
![20170714_007](https://user-images.githubusercontent.com/22349799/28214528-928df282-6878-11e7-99fe-7d7b3222c42b.jpg)

3. enter the colour
![20170714_008](https://user-images.githubusercontent.com/22349799/28214549-a828cfcc-6878-11e7-8ded-8cd1fd99b666.jpg)

4. reorder it if you want
![20170714_009](https://user-images.githubusercontent.com/22349799/28214559-b25d227c-6878-11e7-9250-ffe470b29c4f.jpg)

5. click 'Save'
![20170714_010](https://user-images.githubusercontent.com/22349799/28214565-bb8bdd3e-6878-11e7-9377-595a166dce5b.jpg)

**Comment by DeniseColbert** [comment]
Thanks Bev. I followed your instructions and seem to have added the purple to the colours available, but the highlight block is transparent with black / grey text in Live Preview. Could you take a look please?

**Comment by DeniseColbert** [comment]
See above:

![image](https://user-images.githubusercontent.com/19173257/28412704-e5c106ec-6d3c-11e7-8719-0faf25542c57.png)

**Comment by bev-fc** [comment]
Sorry my bad, the original css didn't define class for colour purple, I have modified, can you check it again? (you may need to clear your browsing data first)

**Comment by DeniseColbert** [comment]
Yay! All working fine now, thanks Bev.

Best wishes,

Denise

**********
*Denise Colbert*
Engagement Co-ordinator

[Usual working days: Monday, Tuesday and Wednesday]

E: denise.colbert@freeukgenealogy.org.uk <denise.colbert@freeukgen.org.uk>
T: +44 7825 338014
W: http://www.freeukgenealogy.org.uk/

*Join us on Social Media:*

* <https://www.facebook.com/freeukgen>    <https://twitter.com/Freeukgen>*


Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A Charitable Incorporated Organisation registered in England and Wales,
number 1167484.

VAT registration: 233 0105 70
