### ISSUE TITLE
Plan September 2018 meeting

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#433]

**Comment by PatReynolds** [comment]
email trustees

**Comment by PatReynolds** [comment]
150 seats

**Comment by PatReynolds** [comment]
Speakers: history and future of FreeBMD (tech!); history and future of crowdsourcing; BMD records.  Trustee meeting week before and only 1 hour meeting on Saturday to give more room for ?4 speakers + discussion.

**Comment by DeniseColbert** [comment]
Maybe add coming to the end of the first keying to the celebrations? See email from Ted 14/3

**Comment by PatReynolds** [comment]
@DeniseColbert to send out eventbrite page links and arrange speakers

**Comment by PatReynolds** [comment]
@patreynolds to read email on teas and coffees

**Comment by PatReynolds** [comment]
@DeniseColbert to check that people can take teas and coffees from the cafe into the auditorium, and that they can bring own flasks.

**Comment by PatReynolds** [comment]
@patreynolds to check advertisement fees

**Comment by PatReynolds** [comment]
Souvenirs, games, etc. to be planned.

**Comment by DeniseColbert** [comment]
https://drive.google.com/open?id=0B9QXkJ8S6kJnVGtKVFplX1hONVB0SzVGei1IQ0duVkhqVDFn
