### ISSUE TITLE
FreeBMD2 comms plan

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#434]

**Comment by DeniseColbert** [comment]
Started: https://docs.google.com/document/d/1-qOSgBGckI5kl1_uYh6Nt4ctUtcp8EUMXpVNGwK8prA/edit#

Can you check @PatReynolds that this is OK? (using FC2 launch plan as template)

**Comment by PatReynolds** [comment]
Checked

**Comment by DeniseColbert** [comment]
Ready for you to look over the body of the plan now @PatReynolds , some questions on the document for you too.

**Comment by PatReynolds** [comment]
I have answered where I can ... (often just with other suggestions) ping back to me if no resolution.

**Comment by DeniseColbert** [comment]
Couple of questions in comments

**Comment by PatReynolds** [comment]
Think I've resolved.

**Comment by DeniseColbert** [comment]
Made another pass, please check

**Comment by PatReynolds** [comment]
Checked and made one comment.  Otherwise good!

**Comment by DeniseColbert** [comment]
Can be considered complete, then. (I'm going to keep the comments with suggestions for copy ie they'll be 'unresolved')
