### ISSUE TITLE
Explore logos / blending / shades

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#435]
Accessible colours do not necessarily make the best shades for logos. Consider having brighter (less accessible) shades in logos

**Comment by PatReynolds** [comment]
I would be happy with that.  Is it just FreeCEN, or is wider?

**Comment by DeniseColbert** [comment]
Good question, we should ask Alison. I have some colour ideas for FreeREG too, to add to discussion on colours
