### ISSUE TITLE
Donate button appears twice on Donate page

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/Coordination#445]
http://www.freeukgenealogy.org.uk/about/help-us-keep-history-free/

At the foot of the page, the donate button appears twice - one is active and one isn't. Appears to be a bug (happens in both Chrome and Firefox on desktop. Looks almost OK on mobile, but one is still inactive. Suggest removing the one that's inactive.

**Comment by PatReynolds** [comment]
Remove the picture of the logo and if possible replace with another image.

**Comment by DeniseColbert** [comment]
Done - please check.
