### ISSUE TITLE
Redesign Open Data pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#465]
separate pages for those donating data, new volunteers, existing volunteers, wanting to get at data.

**Comment by PatReynolds** [comment]
Make paragraphs relating to opting out and opting not to opt prior to making those options live on the website.

**Comment by PatReynolds** [comment]
Add in info on Linked Open Data

**Comment by PatReynolds** [comment]
Linked Open Data page now ready for proofing, @DeniseColbert

**Comment by DeniseColbert** [comment]
Proofed and made live
