### ISSUE TITLE
Migrate www.freeukgenealogy.org.uk to https

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#471]
Email received from Google about our use of forms - please migrate (will forward email).

**Comment by lemon-ukgen** [comment]
So there's two things here:

Firstly, the site is already available over https (visit https://www.freeukgenealogy.org.uk/ to see), but we don't automatically redirect http to https. That's something I can do.

But the second thing is that I shouldn't do that until will address all the "mixed content" issues. These are links and assets the pages' contents that are `http://` not `https://`. These need to be addressed inside the CMS.

The main offenders seem to be

* logo images (eg http://www.freeukgenealogy.org.uk/files/Logos-promos-badges/New-logos/BMD-hex.PNG)
* form tags (eg the search form submits to http://www.freeukgenealogy.org.uk/search/)

but for completeness we should change all the navigation links from things like

* `<a href="http://www.freeukgenealogy.org.uk/news/">News</a>`

to

* `<a href="https://www.freeukgenealogy.org.uk/news/">News</a>`

**Comment by DeniseColbert** [comment]
@lemon-ukgen I'll speak to Bev about changing all the navigation links but for the logo images / form tags, can I just go into Craft and add in the 's'?

**Comment by PatReynolds** [comment]
@lemon, do all links need the form https://www.whatever, or is www.whatever ok?

**Comment by lemon-ukgen** [comment]
For links and form targets we need `https://` to be in the URL. 

So for the image link example above

`<img ... src="http://www.freeukgenealogy.org.uk/files/Logos-promos-badges/New-logos/BMD-hex.PNG">`

needs to become 

`<img ... src="https://www.freeukgenealogy.org.uk/files/Logos-promos-badges/New-logos/BMD-hex.PNG">`

and so forth. In Craft you can click `HTML` to get the raw view and add the `s` where needed. See the example screenshot attached. (These are the hex logos on the home page I mention above).

There might be a more Craft-y way of doing that, but I can't see where you specify the image when you edit links in general.

**Comment by lemon-ukgen** [comment]
<img width="923" alt="http" src="https://user-images.githubusercontent.com/16789923/30537197-14b4641e-9cac-11e7-9825-838b8668d5b8.png">

**Comment by DeniseColbert** [comment]
I've changed all instances of links in pages, emailed Bev and lemon 21/9 about other parts of task.

**Comment by allanraymond** [comment]
I notice the title says "Migrate .... to **httops**" should this read "Migrate ....to **https**"?

**Comment by PatReynolds** [comment]
Yes @allanraymond , typo corrected.

**Comment by PatReynolds** [comment]
@DeniseColbert to check that the change to https can be made now / has been made

**Comment by PatReynolds** [comment]
@DeniseColbert can you check with @bev-fc that she has what she needs.
