### ISSUE TITLE
add https://www.clahub.com/ to tech sign up /operation

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#475]
E0 U6 S10 C7: P23

**Comment by richpomfret** [comment]
Now taking a look at this..

**Comment by PatReynolds** [comment]
to use: Ben L suggests Apache's
or one Pat drafted?

**Comment by richpomfret** [comment]
We currently use Apache for our license agreement - this is an interesting read in relation to whether we opt for CLA at the moment or not: https://opensource.stackexchange.com/questions/5585/benefits-of-a-cla-when-using-apache-2-0-license

**Comment by richpomfret** [comment]
Added this now as a test on our Coordination repo - note that we can add in requests for email address/name/initials etc if required. Shall roll out onto our other repos if you're fine with this one.
