### ISSUE TITLE
Recruit & support new Comms Coord team

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#491]

**Comment by DeniseColbert** [comment]
Jo is now receiving volunteering queries.

Now waiting on info from discussion with Eric B etc. for Data Corrections volunteer and feedback volunteer

**Comment by DeniseColbert** [comment]
Role descriptions started

**Comment by DeniseColbert** [comment]
Feedback Volunteer RD draft sent to @SteveBiggs & @PatReynolds on 4/10

**Comment by SteveBiggs** [comment]
I have added some comments to the draft.

**Comment by DeniseColbert** [comment]
Thanks Steve.

Comments to be reviewed.

**Comment by PatReynolds** [comment]
@DeniseColbert to arrange meeting with Pat, Steve, EricD and Rich/Vino to finalise document

**Comment by DeniseColbert** [comment]
Doodle sent out 27th Nov

**Comment by PatReynolds** [comment]
Please could you resend the document to me?

**Comment by PatReynolds** [comment]
@DeniseColbert to circulate FAQ
General comment - leads to a page that defines each type of question, and leads to their FAQ, with a final 'not included above - Other comment or question' contact
