### ISSUE TITLE
Decide how to share Security Policy with volunteers

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#504]
Policy Acknowledgement form?
This would mean we'd need 3 - one for each level of the document

**Comment by DeniseColbert** [comment]
Also, clarify who gets which version (low/mid-level)

**Comment by richpomfret** [comment]
Full level for fullstack (or backend) developers and the rest should be determined by access to systems. In terms of distribution, Allan ( for BMD) requested that we send it out via the admin list to transcribers. We can consider doing the same for other projects (and have it ready for any new starters as part of onboarding).

**Comment by PatReynolds** [comment]
Can you ask Brenda and Steve whether they want you/me to send to their lists, they'll send to lists, or whether we will have it available for download on login to FreeREG/FreeCEN2.

**Comment by PatReynolds** [comment]
1/ Rich to send to fullstack/backend level, then
2/ determine who is mid-level, and directly email to them, also with copy of low level and explanation that low level will be going to all,
3/ send to the lists (direct or Brenda/Steve).
