### ISSUE TITLE
Create Forum

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#510]
Possibly use Vanilla on www.freeukgenealogy.org.uk?

**Comment by richpomfret** [comment]
Option of using Slack or Reddit here - currently testing. To then add links to all of our Open Data info and to open up discussion points.

**Comment by PatReynolds** [comment]
@DeniseColbert and @patreynolds to check. @richpomfret to add sign up

**Comment by PatReynolds** [comment]
Need to include details of how to sign up anonymously

**Comment by PatReynolds** [comment]
See if we can get people in without them having to create a google account

**Comment by DeniseColbert** [comment]
We had this issue with the Advisory Board Google group; if you do find a way around this I'd be interested to know

**Comment by richpomfret** [comment]
Users can view but not post with the Google group unless signed-up. Craft itself uses 'Stack exchange' which is a community Q&A option (suitable for Open Data although will investigate if it fits for other required functionality). I think sign up is usually manditory for posting though..shall investigate.

**Comment by PatReynolds** [comment]
Set up stack exchange forum for Code of Conduct Review discussion

**Comment by richpomfret** [comment]
Stack Exchange process takes a while (to move it through a beta stage) and it is limited to a Q&A format. Let's stick with Google Groups for Open Data initially - for purposes of getting it 'out there' and then move across to SA when possible.

**Comment by PatReynolds** [comment]
Go with Google, acknowledging that it isn't perfect, and asking for alternatives. @richpomfret to ask @Vino-S to make forum live.
@patreynolds to try any alternative for the Code of Conduct.
FreeREG #35 needs actioning before go live.
Also on FreeCEN (@patreynolds to check and create story, if needed, on FreeCEN)
