### ISSUE TITLE
FreeREG roadmap delivery plan/Github milestone update

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#514]

**Comment by PatReynolds** [comment]
any more to be done on this @richpomfret ?

**Comment by richpomfret** [comment]
Yes - shall include updating milestones in Github as part of this task. Therefore will add in 1.8 etc and look to configure sub-releases based on core features/epics (to discuss but may resemble 1.5.9 Communication etc).

**Comment by richpomfret** [comment]
Now complete as above.
