### ISSUE TITLE
Resources for Volunteer speakers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#519]
eg powerpoint with Open Data video, clips, slides with bullet point reminders

**Comment by DeniseColbert** [comment]
Done, sent to Pat 9th Nov

**Comment by DeniseColbert** [comment]
Currently creating a form to gather info on speakers. If we're offering our ppt to volunteers, should we put it on the project websites (downloadable) maybe, and keep it updated with current news / figures? Or should I send the updated version out on request?

**Comment by PatReynolds** [comment]
Put presentation behind login (FreeBMD vols will need to ask for link unti FB2 is active)

**Comment by PatReynolds** [comment]
@DeniseColbert to send out survey
