### ISSUE TITLE
Create new donate pages

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#529]

**Comment by DeniseColbert** [comment]
Shaping up, new wire frame TBD with Pat

**Comment by PatReynolds** [comment]
Information on charges: MyDonate charges 20p per credit card transaction, 30p per debit card transaction (I'll add the charges for others as I come across them)

**Comment by PatReynolds** [comment]
Ask SEO volunteer about moving the data on individual projects to to their landing pages - any impact on SEO?

**Comment by PatReynolds** [comment]
@patreynolds to check pages and make live.

**Comment by DeniseColbert** [comment]
Can you hold off on this until later in the week Pat, as Bev and I need to work on the side bar. Will update this story when it's ready.

**Comment by DeniseColbert** [comment]
So the sidebar will apparently materialise when the pages are made live. However, we still need to set up a link for the 'Buy us a coffee' image. I think you mentioned MyDonate as they collect Gift Aid info? Can we set up a MyDonate page with a pre-populated amount?

**Comment by PatReynolds** [comment]
Yes, but will need to be an 'event' (so time limited) and will have minimum donation of £2 (their lower limit).

**Comment by DeniseColbert** [comment]
Found a website that uses this idea and they use a PayPal page with a blank amount box: https://goo.gl/UutsUf

So our regular MyDonate link should be fine I think.

**Comment by DeniseColbert** [comment]
Sent layout options to Pat 11/1

TBD: 
Do we want coffee cup image on the page?
Would a margin around the image look better?
Text and button on image (in coloured box) or below image (as per draft 2)

**Comment by DeniseColbert** [comment]
Thank you for supporting FreeUKGEN page needs linking
