### ISSUE TITLE
Link to newsletters from main website

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#53]

**Comment by DeniseColbert** [comment]
I have made a page under 'About' and saved as a draft. It is hosting links at the moment, as I can't see how to link to PDFs (that is NL1 in 'assets')

**Comment by DeniseColbert** [comment]
Worked it out- PDF now up.

Next problem: how to hide page from navigation but link to it.

**Comment by PatReynolds** [comment]
Sidebar: access this (and footer, etc.) via settings.

**Comment by bev-fc** [comment]
Is it not an issue anymore?

**Comment by PatReynolds** [comment]
No, thank you - we solved it.


*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
