### ISSUE TITLE
Refinery training

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#530]
- set people up in slack channel
- online training session (hangout on air, on slack channel
- other resources

**Comment by DeniseColbert** [comment]
Find out availability, first Vino, than Doodle (make it around 7 - 8pm). Decide what to cover

**Comment by DeniseColbert** [comment]
Add Geoff to channel, ask him about Slack. Contact Rena and Chris re. Slack. Also choose date for training.
