### ISSUE TITLE
update all projects on Github

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#538]

**Comment by richpomfret** [comment]
Ensure readme is updated on all core projects (such as we have with BMD). To include link to volunteer pages.

**Comment by PatReynolds** [comment]
Check what Ben is doing/has done, - is anything left?

**Comment by PatReynolds** [comment]
Check on Github -anything stlll needing doing? Schedule meeting with Ben to review/do anything else needful for new volunteers/recruitment

**Comment by richpomfret** [comment]
Set-up a new meeting to review these.

**Comment by richpomfret** [comment]
Updated FreeREG and FreeCEN on Github to include the readme and contributing md files - including a bit about the ideas list/survey for people to fill in/get access to our Slack volunter channel (the setting up of which might require another story).
