### ISSUE TITLE
RailsGirls summer of code (opens 20 Nov)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#539]

**Comment by DeniseColbert** [comment]
You have until January 31st, 2017 (23:59:00 UTC) to submit your project on our Teams App; you will need to authenticate with GitHub. Once logged in:

Click on “Submit your project” in the navigation bar.
By default, we assume the submitter is also the primary mentor. If that isn’t the case, enter the name of the primary Mentor as well as their email address and GitHub handle.
Add the project’s name, website, repo and a description: what the project is about, what stage it’s at, and maybe something about the team behind it.
Add features and tasks: outline how you image the students to contribute, features you’re planning to work on, issues that need help.
Add requirements: describe skills and experience students should bring to work on the project, e.g.
Provide a small example or coding challenge for students to solve upfront.
Add links to online courses or katas students should be confident with.
Frame possible features students could work on.
…or just ask the students to contact you for this.
Add keywords: this can mean a language, like “Python”, framework like “React”, but also specific technologies or concepts.
Add the name of your license in the “license” field.
You can flag your project as “suitable for beginners” by using the available checkbox.
Click Submit!

**Comment by PatReynolds** [comment]
@richpomfret  to add label to project boards 'SoC' - to identify features/projects that might be suitable. for RG SOC, Google SOC, etc.

NB participation RailsGirls SOC is ft July 1st - Sept 30th ( last year)

**Comment by DeniseColbert** [comment]
SoC added to FC, FR and FBMD2 boards.

**Comment by PatReynolds** [comment]
Read application details and added comments on NewProjects #45 -
