### ISSUE TITLE
Actions from skills review for Advisory Board

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#541]

**Comment by DeniseColbert** [comment]
Contacted some members re. continued involvement 7th Nov

**Comment by DeniseColbert** [comment]
29/11 - Contacted Shelagh and Anne (FreeCEN), sent message to FreeBMD list and FB group

**Comment by DeniseColbert** [comment]
To do: Write to board re. email from Pat 15/11

**Comment by PatReynolds** [comment]
Contacted Mia and Rachel 30/11

**Comment by DeniseColbert** [comment]
Michele is on board

**Comment by DeniseColbert** [comment]
ARA can't help. Will put out on Jisc mailing lists next week

**Comment by PatReynolds** [comment]
@DeniseColbert to place on Archives' mailing list

**Comment by PatReynolds** [comment]
@patreynolds to ask BenB.

**Comment by DeniseColbert** [comment]
@PatReynolds could you take a look at Draft 1 of the AB page and make live if all is well?
https://www.freeukgenealogy.org.uk/admin/entries/pages/1675-advisory-board-opportunities/drafts/64

I've added some info about contribution, it may be too much so please adjust as you see fit. Also enabled the block with the bullet points but have framed it differently.

**Comment by DeniseColbert** [comment]
We also need to decide how to proceed with non-contact members

**Comment by PatReynolds** [comment]
@patreynolds to check mia and rachel

**Comment by PatReynolds** [comment]
No reply from Mia, Rachel's reply was in spam :( so replied today 8/1, hoping to have a phone conversation this week or next.
