### ISSUE TITLE
#archivehour [deadline noon 21st Dec]

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#542]
https://twitter.com/archivehour

Last Thursday of the month, 8-9pm UK time. #archivehour hosted each month by one of nine ARA regions/sections plus a guest host! Everyone welcome!

**Comment by DeniseColbert** [comment]
Our volunteer posted with the hashtag, but having looked at how the first one went, I think we could engage at a higher level with the conversations happening during the hour. Your wheelhouse,  @PatReynolds ?

**Comment by PatReynolds** [comment]
Next one's theme will be audiovisual heritage, which doesn't seem particularly good for us.  Let's plan for the following one.

**Comment by PatReynolds** [comment]
It's #festivearchives with Secret Santa - need to send dm before 21st Dec.

**Comment by DeniseColbert** [comment]
Registered. In calendar for 22nd
