### ISSUE TITLE
Revise security policy Nov 2017

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#543]
National Records of Scotland requires that we include:
1      	The Boundary Firewall Controls that are in place
2      	The Secure Configuration polices that are in place
3      	The Access Control policies that are in place
4      	The Malware Protection policies that are in place.
5      	The Patch Management policies and procedures that are in place
6      	The Decommissioning plans that are in place

**Comment by PatReynolds** [comment]
Remind  people about revising early new year, revised policy to Trustees for January meeting

**Comment by richpomfret** [comment]
I now have a few revision requests - shall nudge for final requests to be sent through by end of this week.

**Comment by richpomfret** [comment]
To add in revisions and send around proposed updated version - to trustee's with list of changes for approval.

**Comment by richpomfret** [comment]
Reviewing NCSC (cyber security guidance) to see if we should take on board any suggestions/changes. Will then prepare and send around to trustee's for change approval.

**Comment by richpomfret** [comment]
To send out this week (and shall link on the TASc channel too).

**Comment by richpomfret** [comment]
This has fallen to the wayside over last month. Looking at it now.

**Comment by richpomfret** [comment]
Closing - this has now been replaced by task #656
