### ISSUE TITLE
Recruit social media volunteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#550]

**Comment by DeniseColbert** [comment]
@PatReynolds to proof webpage

**Comment by DeniseColbert** [comment]
Emailed Andy and Loren re. hangouts

**Comment by DeniseColbert** [comment]
Hangouts scheduled with Laura and Rebecca

**Comment by DeniseColbert** [comment]
Tuesday morning booked out with SM applicant hangouts

**Comment by DeniseColbert** [comment]
Loren started
