### ISSUE TITLE
Recruit Analytics Volunteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#551]

**Comment by DeniseColbert** [comment]
Draft RD sent to Pat 16th Nov

**Comment by PatReynolds** [comment]
Commented 21/11

**Comment by DeniseColbert** [comment]
Please check web page for role @PatReynolds and make live

**Comment by DeniseColbert** [comment]
One decent applicant so far

**Comment by DeniseColbert** [comment]
Skills review completed, Slack channel created, Mike invited. Next: email candidates and add to channel

**Comment by DeniseColbert** [comment]
Dragos onboard, meeting with Sarah next week (mon)
