### ISSUE TITLE
Recruit Record Office Engagement Volunteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#552]

**Comment by DeniseColbert** [comment]
Draft RD sent to Pat 16th Nov

**Comment by PatReynolds** [comment]
Commented 21/11

**Comment by PatReynolds** [comment]
Finalised text 23/11

**Comment by DeniseColbert** [comment]
Thanks. Please check web page for role @PatReynolds  and make live (under Core Volunteers page)

**Comment by DeniseColbert** [comment]
Live on recruitment channels, to be placed on JobsDesk and JISC mailing lists

**Comment by DeniseColbert** [comment]
Frances in - post. Emailed Lorraine who is interested in filling Partner Research role when Rd has been checked by Pat
