### ISSUE TITLE
Link SM accounts to new Hootsuite account

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#554]
info@ address

**Comment by DeniseColbert** [comment]
Done: unfortunately our SM accounts can only be managed by one HS account.

**Comment by PatReynolds** [comment]
Denise to link our SM accounts to the new HS account

**Comment by DeniseColbert** [comment]
Authentication email (to info@) didn't arrive. Investigating.

**Comment by DeniseColbert** [comment]
Done - closing.
