### ISSUE TITLE
Archive FreeUKGenealogy on Github

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#555]
Move live issues to coordination board

**Comment by PatReynolds** [comment]
@richpomfret is this still needed?

**Comment by arswright-alt-uk** [comment]
Merged historical git repository to [arswright-alt-uk/FreeUKGenealogy](https://github.com/arswright-alt-uk/FreeUKGenealogy) and completed pull request to [FreeUKGen/FreeUKGenealogy](https://github.com/FreeUKGen/FreeUKGenealogy).
