### ISSUE TITLE
Develop a Mac version of BMDVerify

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/Coordination#556]
To ensure we have all documentation/process in place for volunteer to move onto developing this when required.

**Comment by PatReynolds** [comment]
Or web version - moving everyone online at this point in the process.

**Comment by richpomfret** [comment]
As part of a bigger picture plan, I think it will be important to map out the tools for each project and determine any overlap e.g. considering the use of templates and how we might develop across project web solutions..

**Comment by PatReynolds** [comment]
Now covered by UniTT , so closing.
