### ISSUE TITLE
Explore holding an Open Data Day (March)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#557]
As per Pat's email on Nov 4th

**Comment by DeniseColbert** [comment]
Add to other Waffleboards?

**Comment by PatReynolds** [comment]
a hangout on air?

**Comment by PatReynolds** [comment]
Advisory board involvement?

**Comment by DeniseColbert** [comment]
Twitter / Facebook Q&A to Pat and / or Trustees?

**Comment by PatReynolds** [comment]
Asked for suggestions 14/12

**Comment by PatReynolds** [comment]
@patreynolds to write something (?FB post) on Open Death Data

**Comment by PatReynolds** [comment]
Draft blog written.
