### ISSUE TITLE
Papers for Trustee meeting 25/11

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#560]

**Comment by PatReynolds** [comment]
@DeniseColbert Financial and Strategic report ready for proofing - please update Adwords section (highlighted in yellow) and add anything else from you re. comms  - in the docs for review meeting folder.

**Comment by DeniseColbert** [comment]
Done- please check the Comms & Communities section @PatReynolds 

Should I add stories to board for recruiting AdExchange / AdSense volunteers?

**Comment by PatReynolds** [comment]
Yes, please.

**Comment by DeniseColbert** [comment]
Done
