### ISSUE TITLE
Papers for January Trustee meeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#575]

**Comment by DeniseColbert** [comment]
Agenda template placed in Docs to be Reviewed, ready for populating.

(I will update the minute book this week and re-link - it's a slightly bigger job without MS Word)

**Comment by DeniseColbert** [comment]
Have tagged CvM for response to a comment on 9/9/17 minutes

**Comment by DeniseColbert** [comment]
@PatReynolds can you make the amendment to 9/9 minutes based on Camilla's update please? I'll then go ahead with the minute book.
