### ISSUE TITLE
Recruit volunteer for Zooniverse Project Builder text entry

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#576]
(#43 NP)

E0 U6 S7 C5:P18

**Comment by PatReynolds** [comment]
Need to identify what to transcribe.

**Comment by DeniseColbert** [comment]
How urgent is this for me this week?

**Comment by PatReynolds** [comment]
Not urgent fo you - actually now decided that due to inability on zooniverse to allocate/manage transcriptions, it's not for FreeREG at this time - experiment to run on FreeBMD only, so closing this.
