### ISSUE TITLE
Review recent FreeCEN2 feedback

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#591]

**Comment by PatReynolds** [comment]
add 'what we have fixed' link to the search page, and feed back to those who submitted to let them know.  Add common 'problems we know about, but haven't yet fixed' on the feedback form

**Comment by DeniseColbert** [comment]
Stories from comments are up to date. Have also compiled a document of positive feedback and extracted info on where respondents heard about FC2 for report to trustees.
