### ISSUE TITLE
Wikipedia style special donation opportunity

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#596]
Analyse Results

**Comment by DeniseColbert** [comment]
![image](https://user-images.githubusercontent.com/19173257/48263761-1a3b1980-e41f-11e8-9441-196d4cd79df1.png)

**Comment by PatReynolds** [comment]
@PatReynolds to ask Vino to cost the stories on FreeBMD and add herself to any developer jobs that do not have anyone attached to them yet.

**Comment by PatReynolds** [comment]
Asked @Vino-S 16 Feb 2022
