### ISSUE TITLE
FreeREG FAQs

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#604]

**Comment by PatReynolds** [comment]
@DeniseColbert to make and circulate separate document

**Comment by PatReynolds** [comment]
@DeniseColbert to circulate FAQ
General comment - leads to a page that defines each type of question, and leads to their FAQ, with a final 'not included above - Other comment or question' contact

**Comment by PatReynolds** [comment]
@patreynolds to look at test3, @DeniseColbert to circulate questions

**Comment by PatReynolds** [comment]
Email sent 14/3/2018

**Comment by PatReynolds** [comment]
@DeniseColbert to speak to Steve about drafts and recruiting Data Correction Volunteer

**Comment by DeniseColbert** [comment]
DCC RD done.

All draft FAQ pages were lost in Sunday's sync. Work to be re-done.

**Comment by PatReynolds** [comment]
https://www.freeukgenealogy.org.uk/about/volunteer/tech-volunteering-opportunities/

**Comment by DeniseColbert** [comment]
Done.
