### ISSUE TITLE
Create CIO minute book

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#63]

**Comment by DeniseColbert** [comment]
@PatReynolds - done and placed in Meetings folder in the drive

**Comment by PatReynolds** [comment]
also for CIO

**Comment by PatReynolds** [comment]
add May minutes to unincorporated miniutbooks

**Comment by DeniseColbert** [comment]
Done

**Comment by DeniseColbert** [comment]
CIO Minute Book in Meetings folder.  Will make PDF once checked by Pat.

**Comment by PatReynolds** [comment]
Checked and is fine.  Thank you!

**Comment by DeniseColbert** [comment]
Great, PDF created.

**Comment by PatReynolds** [comment]
Can you now add the January / February meetings - sorry!

**Comment by PatReynolds** [comment]
Can you now add the meetings up to the most recent?  Sorry about missing this last week.

**Comment by DeniseColbert** [comment]
No probs; done.
