### ISSUE TITLE
Add apache licence to all code

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#636]
Currently only Myopic Vicar / Ruby

**Comment by richpomfret** [comment]
It's now there/added on FreeReg, FreeCEN, FreeBMD, WinFreeREG, BMD-X. Not sure we need to add elsewhere (at a glance). Can close if not.

**Comment by PatReynolds** [comment]
FreeREGimage management Scribe API (or whatever licence source code is), errbit (or whatever licence source code is),  UkHgisPlaceProviders, jquery (or whatever licence source code is), forename, opensourceindexing (or whatever licence source code is) fromcursivetodatabase (or whatever licence source code is)

**Comment by richpomfret** [comment]
Done. Double-checked and added licenses where applicable (some open source projects where we have use code operate under a MIT license).
