### ISSUE TITLE
Donations in own currencies

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#650]
Add Paypal buttons for donations in AUS$, CAN$, US$ and NZ$.

**Comment by PatReynolds** [comment]
Code sent 16/2.
When live, publicise in social media?

**Comment by DeniseColbert** [comment]
2 drafts made, issues with spacing, aesthetics, code

**Comment by PatReynolds** [comment]
@patreynolds to check French Canadian text on paypal and check that NZ dollars is set up for NZ dollars not  US dollars ...  @DeniseColbert I think we need a line at the bottom which says contact us (links to info@ email) if you would like to pay in another currency, and we'll make the button.
I like the borders, but they take up space (the tighter spacing is better, particularly if we add in more buttons ....

**Comment by PatReynolds** [comment]
NZ dollar is fine.  Paypal sets its language by the language of the computer talking to it, so I've asked the SM team if they can ask someone in Quebec to test it for them.

**Comment by PatReynolds** [comment]
@DeniseColbert to check on FB

**Comment by DeniseColbert** [comment]
Pat's post has indeed vanished! I'll schedule a post on the FB page...

**Comment by DeniseColbert** [comment]
Posted.

**Comment by PatReynolds** [comment]
@DeniseColbert to schedule for FB

**Comment by DeniseColbert** [comment]
No takers! Have posted it in a few FB groups now.

**Comment by PatReynolds** [comment]
Quebecois fine. Pat to check default country of Canadian English

**Comment by PatReynolds** [comment]
Add £ exsisting button,  AUS CAN NZ US$; add text to say you don't need a PayPal account

**Comment by PatReynolds** [comment]
I can't see why the Canadian English button is giving Quebecois!  It was set to British English, so I've changed that to Canadian English, and emailed the resulting code to you

**Comment by PatReynolds** [comment]
To be tested by Canadian vol.

**Comment by DeniseColbert** [comment]
The French Canada button presents in French in Quebec, and English in BC.

Issue with the default country being 'off' e.g. NZ page, default is USA:

![image](https://user-images.githubusercontent.com/19173257/42163636-46b98940-7dfb-11e8-8af1-8a0c0c8157c2.png)

Other pages appear differently to NZ page eg:

![36544533_1065018670318178_6690282475513446400_n](https://user-images.githubusercontent.com/19173257/42271594-a29a1ce4-7f7b-11e8-9ce7-83138f104621.jpg)

**Comment by DeniseColbert** [comment]
It has been suggested that using Quebecois would exclude non-Quebecois francophones so should be removed.

**Comment by PatReynolds** [comment]
Buttons are geographical, so donations for France, French Polynesia, etc. would all need their own buttons.  Suggest closing.

**Comment by DeniseColbert** [comment]
Before we do,  we should make this draft live - will you check and do so Pat? https://www.freeukgenealogy.org.uk/admin/entries/pages/1822-how-to-donate/drafts/106
