### ISSUE TITLE
Review/refresh tech volunteer pathway on main recruit pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#653]
Bring into line with new agreed onboarding processes

**Comment by PatReynolds** [comment]
@DeniseColbert to make change to text requested by Rich and make live.

**Comment by DeniseColbert** [comment]
Done:

![image](https://user-images.githubusercontent.com/19173257/35562727-343776e6-05ac-11e8-9ba6-0c7cfe3a60ca.png)
