### ISSUE TITLE
Update Security policy (v 1.3)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#656]
Update to record implementation of changes needed for GDPR

**Comment by PatReynolds** [comment]
https://docs.google.com/spreadsheets/d/1P_0SNRTFD0kcTcpc5IuDR4d4NWX7LaGLpF8sTyRSee4/edit?usp=sharing has the audit Main thing is the addition of dates for disposal and methodology ... some actions needed re cookies, too.

**Comment by richpomfret** [comment]
Updated with data breach info. I would presume data disposal/methodology goes into the privacy policy?

**Comment by PatReynolds** [comment]
add in how to delete Google drive, @richpomfret to send draft full version to trustees and projects

**Comment by richpomfret** [comment]
Updated to 1.1 with details on deleting permanently from Google drive/cloud storage. Shall send out next for feedback.

**Comment by PatReynolds** [comment]
Password protect data if you are going to travel to places where you may be required to give access to your device.

**Comment by richpomfret** [comment]
Shall nudge for any final updates this week and lock it down before the next trustee meeting.

**Comment by PatReynolds** [comment]
Rich to send to trustees for final sign-off.

**Comment by richpomfret** [comment]
Sent to trustees for approval.

**Comment by richpomfret** [comment]
@DeniseColbert handing over to you in order to split into different versions as per the last iteration. Let me know if you have any questions (link will be emailed).

**Comment by DeniseColbert** [comment]
Is it this one, @richpomfret ?  (1_1 not 1.3)

**Comment by richpomfret** [comment]
@DeniseColbert  Yes it is 1_1. Not sure where 1.3 came from - 1.2 will be the next iteration.

**Comment by DeniseColbert** [comment]
There is a section in the abbreviated version of 1.0 that's absent from 1.1 https://docs.google.com/document/d/1crRavinH83m_4JMHMFJRxpAW-LBDmhmm1pCHo5jcx0Y/edit#heading=h.nhwgj46lzg7n

Does this need amending, or can I add it in wholesale? @richpomfret

**Comment by DeniseColbert** [comment]
Previous comment removed as superseded. Could you highlight the parts of 1.1 that should go into this part of 1.1 so I don't omit anything? https://docs.google.com/document/d/1crRavinH83m_4JMHMFJRxpAW-LBDmhmm1pCHo5jcx0Y/edit#heading=h.nhwgj46lzg7n @richpomfret

**Comment by PatReynolds** [comment]
I have marked up the full 1.1 (aka 1.3) document.  Please let me know if you wanted me to mark up something else.

**Comment by DeniseColbert** [comment]
That was fine, made almost all changes needed but made a few comments that need answering before we can close.

**Comment by PatReynolds** [comment]
Think all done now - please let me know if not.

**Comment by DeniseColbert** [comment]
Documents are complete, and links updated on application forms.

Is there anywhere else to update links?

**Comment by PatReynolds** [comment]
@DeniseColbert to add to handbooks
