### ISSUE TITLE
Point Easy Fundraising to Pat and Denise

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#66]

**Comment by PatReynolds** [comment]
Can you create easyfundraising@freeukgenealogy.org.uk and point it at the two of us - then you will get the campaign stuff too.

**Comment by DeniseColbert** [comment]
I'm all set up on easyfundraising now, not sure why this was still open. I've created the alias (well, it's a group really) so should I change the email address on your account to easyfundraising@freeukgenealogy.org.uk?

**Comment by DeniseColbert** [comment]
Yep!

**Comment by DeniseColbert** [comment]
Done
