### ISSUE TITLE
New Tech Volunteer survey 'tinyurl' link

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/Coordination#661]
To update and remove the tinyurl link, as it appears to send the user to an irritating screen prior to the actual survey. We mostly hyperlink to this survey, so no url shortener is really needed.

**Comment by DeniseColbert** [comment]
I use the built-in google shortener with no problems

![image](https://user-images.githubusercontent.com/19173257/35630482-7342242e-0699-11e8-8cb9-ead61f0b7757.png)

**Comment by DeniseColbert** [comment]
I noticed a tinyurl link on the form to the ideas list so have swapped it out for a goo.gl one (url a bit long not to be shortened)
