### ISSUE TITLE
Recruit legacy fundraising volunteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#662]

**Comment by PatReynolds** [comment]
@patreynolds to write role description, @DeniseColbert to recruit, closing date 2 March, interviews 16 March

**Comment by DeniseColbert** [comment]
Skeleton RD sent to @PatReynolds 7/2 for populating

**Comment by DeniseColbert** [comment]
Advertised 17/2

**Comment by DeniseColbert** [comment]
Suggested opportunity to suitable candidates on Reach 5/3
