### ISSUE TITLE
Revise  F U G Cookie policy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#669]
Make policy document
clear that it is only about cookies on FreeUKGenealogy.org.uk and that each of the projects has their own, check that it is in line with revision(s) to those

**Comment by PatReynolds** [comment]
@richpomfret to check cookie policy document for Gree uk gen and other websites.

**Comment by PatReynolds** [comment]
See action plan in 
https://www.reshiftmedia.com/gdpr-google-analytics-adwords/

We don't need to do 1. Denise and I have done 3 and 4.

Please start separate stories for 2 and 5, if needed. 

6 -  implies granular acceptence is needed

7 - I'm working on ...

**Comment by PatReynolds** [comment]
New T&Cs 10. Privacy

Our privacy policy explains how we treat your personal data and protect your privacy when you use our Services. By using our Services, you agree that Google can use such data in accordance with our privacy policy. You and Google also agree to the Google Ads Controller-Controller Data Protection Terms. You will ensure that at all times you use the Services, the Properties have a clearly labeled and easily accessible privacy policy that provides end users with clear and comprehensive information about cookies, device-specific information, location information and other information stored on, accessed on, or collected from end users' devices in connection with the Services, including, as applicable, information about end users' options for cookie management. You will use commercially reasonable efforts to ensure that an end user gives consent to the storing and accessing of cookies, device-specific information, location information or other information on the end user's device in connection with the Services where such consent is required by law.

Will put their privacy policy and the Google Ads Controller-Controller Data Protection Terms into the Security folder

**Comment by PatReynolds** [comment]
Key thing: If visits to your site do not influence the ads served elsewhere, the following notice might be appropriate:  looks nice and simple (http://www.cookiechoices.org/)  
Horrid thing is we need to comply with Google's EU Cookie Consent policy (https://www.google.com/about/company/user-consent-policy.html/) which they'll update on Friday, so won't know till then if granularity is needed.

**Comment by DeniseColbert** [comment]
Did you do each property re. Analytics @PatReynolds  ?

![image](https://user-images.githubusercontent.com/19173257/40367045-667002aa-5dd0-11e8-9fe2-1cca314561e7.png)

**Comment by richpomfret** [comment]
Added 2 & 5 to the FC and FR boards.

**Comment by PatReynolds** [comment]
Checked Analytics - very odd, some done in march, other's not - now all done

**Comment by PatReynolds** [comment]
Now need to offer choice of options on which cookies to accept.
