### ISSUE TITLE
Implement cookie consent on FR1

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#67]

**Comment by Captainkirkdawson** [comment]
Why??????

I thought we wanted to close FR1 down not continue its existence

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
We need to persuade people to move off, first.  This is going to take a few
months, and in the meantime, we need consent in place.


*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
We will never ever totally convince all people. Many (most???) of the users
are bots and they will never switch

I disagree with making any changes to the site that will continue its use.

We have given 18 months of overlap

Enough is enough.


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
