### ISSUE TITLE
Share on Social CTA buttons (when we have permanent URLs)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#673]
If possible with #FoundonFreeUKGEN ready populated on post

Add to Search Results / detailed search results for FreeBMD2?

**Comment by PatReynolds** [comment]
Move to FreeBMD2

**Comment by PatReynolds** [comment]
Now FreeBMD2 #126 - can you check the description and amend as needed, please, @DeniseColbert
