### ISSUE TITLE
Slack for comms volunteers project management

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#687]

**Comment by PatReynolds** [comment]
Use facebook?

**Comment by richpomfret** [comment]
Not had a chance to review last week but shall propose a solution this week - i'd be interested in any FB ideas you have though (not quite sure what you mean).

**Comment by DeniseColbert** [comment]
We currently use a Facebook group to communicate as a group, and post things for each other to use on the different channels.

Not sure if this would be a fit for the purpose this story was created for though- what's the goal?

**Comment by richpomfret** [comment]
It is for what we previously discussed in terms of allocating and tracking
tasks (ideally via Slack & Waffle combo).

*Richard Pomfret*
Technical Project Manager
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

Tel: ​+44 7930 525892
Working days: Monday, Wednesday and Thursday

**Comment by PatReynolds** [comment]
I'd go with FB, as it is easy to put requests there (links to web pages and other social media.  Other things start on the comms board - comms board for other tasks as at present.  @DeniseColbert can you add elle?

**Comment by PatReynolds** [comment]
@DeniseColbert added elle to github
