### ISSUE TITLE
Why is the FreeUKGEN website Missaligned

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/Coordination#698]
I rarely visit the site but ended up there today for some reason and see that the home page  has its action bar misaligned (at least on chrome). Poor advertising

![freeukgen](https://user-images.githubusercontent.com/2874694/37973449-c398b360-3197-11e8-8cff-abed4af65af0.JPG)

**Comment by PatReynolds** [comment]
Thanks, Kirk.  I didn't pick this up as it looks ok on my version of Chrome (Version 65.0.3325.181 (Official Build) (64-bit))
![image](https://user-images.githubusercontent.com/6338822/37974026-bb8bbcb2-31d3-11e8-9351-ebb4c87cf0e2.png)
Also fine on Comodo.

**Comment by Captainkirkdawson** [comment]
It is a function of the display size. On some it looks fine on my wide display it does not. Looks like the layout has some fixed positioning and should not. Get on a wide screen and play with the window size.

The original page layout for the projects actually had those actions in the ation line (The line with the twitter etc).

**Comment by PatReynolds** [comment]
Thanks - I have a very large screen, but if I take it down to 25% I can replicate what you see (simply reducing the screen size doesn't have an impact.

@DeniseColbert would bringing the tabs back into the line, rather than replacing 'home' and search with a line of text (as we'd been thinking) be a possible resolution?

**Comment by DeniseColbert** [comment]
I think so Pat, I'll look into it.

Thanks for picking that up Kirk; it's not something that's been reported before.

**Comment by DeniseColbert** [comment]
@Captainkirkdawson could you take another look, we've made the layout more like that on FreeREG so hopefully fixed this issue.

**Comment by Captainkirkdawson** [comment]
Fine now
