### ISSUE TITLE
Get consent for non-Newsletter non-volunteer mailing lists

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#706]
Ask newsletter and test groups, any other spreadsheets/lists of names and emails:
a) can we send you invitations to test?
b) can we send you emails about F U G  other than the regular newsletter?

**Comment by DeniseColbert** [comment]
Re. Data Audit point on Bounced Emails: Bounced email addresses are automatically cleaned from Flashissue. However, they are listed in reports, with no option to delete them from the report.

**Comment by PatReynolds** [comment]
Do we hold the listing of addresses, etc. anywhere but flashissue?

**Comment by DeniseColbert** [comment]
Yes we hold several spreadsheets of details on the drive. We have details for Archives, local studies libraries etc, Family History Societies and Higher Education institutions. Also, a press releases list. Have moved them into their own folder in Comms --> Making Links folder.

**Comment by PatReynolds** [comment]
FreeCEN and FreeBMD move to Google groups

**Comment by DeniseColbert** [comment]
I have sent consent email with form to all 'personal' email addresses.
