### ISSUE TITLE
Actions from FC2 feedback form

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#716]
Add 'what we have fixed' link to the search page, and feed back to those who submitted to let them know. 

Add common 'problems we know about, but haven't yet fixed' on the feedback form

what you said .... what we are going to do

Also add link to relevant blog post.

**Comment by DeniseColbert** [comment]
...(what we have done also?)

**Comment by DeniseColbert** [comment]
What you said document started, can use as a basis for other 2 tasks in this story

**Comment by DeniseColbert** [comment]
Added this text:

We've reviewed the feedback and the same core features/improvements are being requested by respondents and we plan to address these as 'high priority' in the coming months. Please check the list below and if your suggestion isn't there, do feel free to send it to us via this form.

* Reduce the amount of white-space / scrolling
* Search by address
* Search all of a country
* Search without inputting county
* Search by area/'place'
* Search by folio, page etc
* Search by occupation
* Search multiple census years
* Free text place name search

Read more about where we're up to with FreeCEN here: https://www.freeukgenealogy.org.uk/news/2019/12/09/update-on-the-new-freecen-website and about the rationale for updating FreeCEN here: https://www.freeukgenealogy.org.uk/news/2019/02/13/how-freecen-is-changing

If you're happy with this @PatReynolds , please close the issue

**Comment by PatReynolds** [comment]
Closing because happy.
