### ISSUE TITLE
Invite wider genealogical community to 2018 meeting

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#718]
Include Press Release list, blogger list, FHS list, post in Facebook groups etc.

**Comment by PatReynolds** [comment]
combine with gdpr consent

**Comment by DeniseColbert** [comment]
Th GDPR part of this is done so have removed that label

**Comment by DeniseColbert** [comment]
Sent emails to most mailing lists 23/5

Next: publications and bloggers.
