### ISSUE TITLE
Google GDPR

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#727]
Analytics - add entity and contact, agree to amendment, select expiry of data DONE

Adsense and DFP

This work is extra to GDPR:
[Adwords: "Please review Ad Grants policies and modify account (e.g. set up an automated rule to pause low quality keywords, pause single keywords, raise CTR)."]

**Comment by PatReynolds** [comment]
@DeniseColbert can you see if anything still needs to be done on Adwords?  I have contacted Kate re our choices on Adsense.

**Comment by DeniseColbert** [comment]
Adwords: to become compliant, we need to have text like this on the FreeUKGEN website as we are tracking conversions:
![image](https://user-images.githubusercontent.com/19173257/40358331-bc170042-5db6-11e8-9310-9e07119f1ae3.png)

**Comment by DeniseColbert** [comment]
(Above taken from https://www.cookiechoices.org)

**Comment by PatReynolds** [comment]
Yes, that's fine for the interim.  It will need changing when we start to serve personalised ads again.

**Comment by DeniseColbert** [comment]
@richpomfret can you confirm that the 'ok' box form is fine? (see snip above)

**Comment by richpomfret** [comment]
@DeniseColbert yes that's fine. As Pat comments, it will need to be updated to reflect personalised advertising consent when appropriate (which means it will then resemble what we plan to have on FC and FR etc).

**Comment by DeniseColbert** [comment]
Great, will email lemon now.

**Comment by DeniseColbert** [comment]
Done, unassigning. Add me back if anything else comes up :)
