### ISSUE TITLE
Apply to Facebook Charitable Giving

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#732]
https://www.facebook.com/donate/signup

Bank account pay-in details needed

**Comment by DeniseColbert** [comment]
From page: Please note that you will need to collect detailed financial information from your finance team in order to set up your donations account during the application phase.

Might be smoother if Denise liaises directly with Helen or @PatReynolds completes application.

**Comment by PatReynolds** [comment]
@patreynolds to send bank account details

**Comment by DeniseColbert** [comment]
First step is to verify the organisation, have sent documents, waiting for FB to verify.

**Comment by DeniseColbert** [comment]
Extra info required:
![image](https://user-images.githubusercontent.com/19173257/46873706-238c9280-ce2f-11e8-9835-155f93a76ab8.png)
