### ISSUE TITLE
Make FAQ for GDPR questions

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#734]
https://docs.google.com/document/d/18Od2J-RbJiFe96r0Ke763JqijEv-xjvsxP6RQXFUCmE/edit?usp=sharing
Thoughts as to where?

**Comment by PatReynolds** [comment]
Yes, lets do that!

**Comment by DeniseColbert** [comment]
https://www.freeukgenealogy.org.uk/about/pages/gdpr-faqs
