### ISSUE TITLE
Review lists / list membership

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#74]
All lists, including Support

**Comment by PatReynolds** [comment]
List of lists is in the gdrive, /communications/groupsandemails.docx

**Comment by richpomfret** [comment]
To review (with Pat) and update accordingly.

**Comment by richpomfret** [comment]
Will close this issue (review is now complete) and create new task for updating google email groups accordingly.

**Comment by PatReynolds** [comment]
Notes made in the v.2.  Please check with Barrie how groups function at the moment before moving to google groups.

**Comment by richpomfret** [comment]
Can close this (as above) and create a new story for moving to google groups (if applicable). Do we eventually want to set-up all of our email alias groups in google groups?
