### ISSUE TITLE
Get facebook onto FreeUK Gen

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#743]

**Comment by DeniseColbert** [comment]
Investigate FB pixel for SEO and analytics (does it replace FB:APP:ID?)
Explore adding a FB module to Craft

**Comment by arswright-alt-uk** [comment]
Now tracked at [FreeUKGen/FreeUKGenealogy Issue #19](https://github.com/FreeUKGen/FreeUKGenealogy/issues/19).
