### ISSUE TITLE
Create Documentation for Refinery from Video

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#752]
Possibly a task for a volunteer interested in working in Refinery

E0 U6 S7 C5:P18

**Comment by PatReynolds** [comment]
Rich to review the video

**Comment by richpomfret** [comment]
Remains in progress.

**Comment by PatReynolds** [comment]
Removed 'Good first issue' as cannot be undertaken as a first issue (i.e. without access to refinery)

**Comment by richpomfret** [comment]
@PatReynolds @DeniseColbert created a document based on what's in the video - take a look here and comment/add in anything that you have found useful! Perhaps worth having a general 'tips' section near the end with general advice: https://docs.google.com/document/d/1jX7x6uZQYjxkrNDjzf7fYWC3mQMqgybz15NkisMkxTw/edit?usp=sharing

**Comment by PatReynolds** [comment]
@PatReynolds @DeniseColbert to proof and link from Refinery in each project.@rich to update when Lemon has completed rake task

**Comment by PatReynolds** [comment]
Many thanks, that's great!  I've corrected a couple of typos and made a couple of comments.

**Comment by DeniseColbert** [comment]
Same as above.

**Comment by richpomfret** [comment]
Lemon has completed the REFINERY rake task, so everything in TEST3 (FR) is now on Production. Now it might be good to prepare this document on refinery with the caveat (as @DeniseColbert comments in the doc) that we might well update FreeCEN naming conventions to match those on FR (TEST2 will become TEST3..).

**Comment by richpomfret** [comment]
Discussion on where to put it and creating a version - it may well be that this document isn't suitable for adding to the FUG site (or somewhere 'live'). Internal document?

**Comment by PatReynolds** [comment]
Might be on FR and FC behind sign in, for tech volunteers? Only needed by
those with access to refinery (or possibly sent to those interested in
being a cms volunteer?)

**Comment by richpomfret** [comment]
Updated to reflect change to FreeCEN test2/3 (it now matches FR). @DeniseColbert please give it a sanity check for me.

**Comment by DeniseColbert** [comment]
Done, made a few additions/tweaks

**Comment by richpomfret** [comment]
I think we are done with this. :) Resolved any outstanding comments and reassigned to @PatReynolds to sign-off/create PDF. We then need to move it to a new home and add it to our list of documents to give to new volunteers who will be using Refinery.

**Comment by PatReynolds** [comment]
Done - no changes needed. PDF now in shared>projects>
