### ISSUE TITLE
Create status twitter account

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#756]
Tie to Plan B FreeREG753 - to alert all to status (planned down, error known, error rectification eta, now up)

**Comment by PatReynolds** [comment]
Draft text informing people of existence of the account / functionality for correction / development / proofing: https://docs.google.com/document/d/1X3y_WKoGdRLqweU9EH6bxZ5nW0dDQeZnz25qw7jDzBQ/edit?usp=sharing

**Comment by DeniseColbert** [comment]
Proof done.

**Comment by PatReynolds** [comment]
Hope I've managed to turn off the 'Your highlights' emails.

**Comment by richpomfret** [comment]
Reviewed and looks fine to me. :)

**Comment by richpomfret** [comment]
This is still assigned to me but unclear what remains to be done with this story. @PatReynolds can you clarify?
