### ISSUE TITLE
Register for Benevity

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#783]
An employee of Google wants to support 'FREE UK GENEALOGY' through their workplace giving programme!

Google is one of hundreds of companies around the world that uses Benevity’s technology to power their employee giving, matching, grant-making, and volunteering programmes. We’re contacting you because an employee has nominated 'FREE UK GENEALOGY' for their programme.
Complete your registration at the Benevity Causes Portal to be eligible to receive support from Google employees and the millions of others using Benevity to connect with their preferred causes.

**Comment by DeniseColbert** [comment]
https://causes.benevity.org/causesapp/dashboard/826-1167484

I've set up an account for us and made the declarations, however, banking info needed to complete

Username: FreeUKGEN
Password: ususal first part, will email rest

**Comment by PatReynolds** [comment]
Information submitted.  Awaiting verification 5/7/2018
