### ISSUE TITLE
Establish Glacier

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#785]

**Comment by richpomfret** [comment]
Lemon does not yet have access - have nudged Ben L again for this.

**Comment by richpomfret** [comment]
Lemon should now have access!

**Comment by richpomfret** [comment]
We also have the grant in place too - looks like it is GO. Next steps to get a brief timeline and set of tasks for moving our backups onto Glacier (and then allocate space for Open Data too).

**Comment by richpomfret** [comment]
This is now set-up and it is being used as back-up. To confirm if there is anything else we may wish to back-up on there - shall do this via Slack.

**Comment by richpomfret** [comment]
Closing as complete- created #948 to cover periodic check/update of what's stored on there.
