### ISSUE TITLE
Promote Recycle4Charity

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#787]

**Comment by PatReynolds** [comment]
https://www.recycle4charity.co.uk/Donators - encourage people to use this to recycle injet cartridges, we get £1.98 per cartridge recycled - need to go to that page, choose Free UK Genealogy as the charity to support, and they will send you some prepaid envelopes that each take one cartridge for you to send back to them.

**Comment by DeniseColbert** [comment]
Just signing up for myself, and wondered about how we get notified of people who want to hear from us:
![image](https://user-images.githubusercontent.com/19173257/42280941-16926304-7f9a-11e8-8704-5cc741012acb.png)

**Comment by DeniseColbert** [comment]
https://www.freeukgenealogy.org.uk/admin/entries/pages/2297-recycle4charity

**Comment by DeniseColbert** [comment]
First SM promo done.
