### ISSUE TITLE
Enhance Cookie notice on FreeUKGEN website

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#804]
When code is ready, Bev will do the task in Craft.

Needs #901

**Comment by DeniseColbert** [comment]
Pat suggested: "You can learn more about cookies and choose to accept some, decline others, or change your settings at a later date by clicking the 'About Cookies' button below, or in the footer of the website at any time"

**Comment by DeniseColbert** [comment]
Added Scott and Rich to story.

**Comment by richpomfret** [comment]
We will need to keep in mind the key actions we wish to trigger when users read the cookie banner text - the above looks good if, I presume, it is meant to be added to what is already there or combined in some way? Note that a slightly larger change will be to the actual cookie policy page text.

**Comment by PatReynolds** [comment]
@Rich are we ready to change the text now?

**Comment by PatReynolds** [comment]
@richpomfret says OK to change

**Comment by bev-fc** [comment]
what's the new text that will be used to replace current cookie notice?

**Comment by PatReynolds** [comment]
Hi @bev-fc thanks for picking this up.  The text is above, put on by Denise 20 Sept.

This will mean the button label needs changing, as well as the text.  Let me know if you have any questions.

**Comment by bev-fc** [comment]
The current notice is "We use cookies to ensure you get the best experience with our website. This includes carefully chosen third-party cookies for analysing traffic and advertising. Please select Accept if you consent and wish to continue using the site. Learn more about how we use cookies"

The new notice will be "You can learn more about cookies and choose to accept some, decline others, or change your settings at a later date by clicking the 'About Cookies' button below, or in the footer of the website at any time", is it correct? I feel some words is missing here, so please correct me if I am wrong.

**Comment by PatReynolds** [comment]
Well spotted @bev-fc !  Full text is: "We use cookies to ensure you get the best experience with our website. This includes carefully chosen third-party cookies for analysing traffic and advertising. Please select Accept if you consent and wish to continue using the site. You can learn more about cookies and choose to accept some, decline others, or change your settings at a later date by clicking the 'About Cookies' button below, or in the footer of the website at any time."

**Comment by bev-fc** [comment]
notice is modified, please take a look if any change is needed.

**Comment by PatReynolds** [comment]
Thanks, Bev - the wording is now fine.  

I am bringing @DeniseColbert into the conversation because I think we might need a new page (if it isn't already there - Denise if it is there, can you put a link to it here?)

The "About Cookies' button should replace the Decline button, and go to the page where the user can select which level of cookies to implement, if they wish.  

The link to our cookie policy should be in the selection page.

The footer should have a 'About cookies' link which goes to the selection page.

**Comment by DeniseColbert** [comment]
Bev has sent me the toggle code

**Comment by DeniseColbert** [comment]
Asked @arswright-alt-uk about this on Slack
