### ISSUE TITLE
Onboard Adsense Volunteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#811]

**Comment by DeniseColbert** [comment]
Emailed Ben L 13/8

**Comment by PatReynolds** [comment]
Pat to set up page on Benevity
Denise to contact Ben

**Comment by DeniseColbert** [comment]
Emailed Ben L 14/11

**Comment by PatReynolds** [comment]
Denise to organise initial meets.

**Comment by DeniseColbert** [comment]
Wrote to Benevity volunteer 19/11

**Comment by DeniseColbert** [comment]
Meeting with Sai on Thurs 29/11
