### ISSUE TITLE
Modify text on FreeUKGen homepage

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#82]
See Alex's suggested text:

https://docs.google.com/document/d/1OJsWYSuUNhex8RHdZEeSKdCvD2QiDU9erIa5tpfqz3c/edit?usp=sharing

**Comment by PatReynolds** [comment]
typo fixed and some comments replied to /made.

I found a broken link at the bottom of
http://www.freeukgenealogy.org.uk/about/ - maybe should go to Volunteers?

I've added a concluding paragraph to cover the other objectives of the
charity (and also to get Open Source and Open Data on the page.



*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
