### ISSUE TITLE
Create fundraising group (gmail)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#825]

**Comment by richpomfret** [comment]
We have an 'easyfundraising' group - is this the one now set-up or do we require a different one? Let's discuss next steps and get this completed.

**Comment by DeniseColbert** [comment]
Set up, Pat and Denise added. 

Next: email trustees and AB about joining

**Comment by DeniseColbert** [comment]
Email sent to Trustees, Nick and Barbara (AB)

Do we want to consider opening this out to project volunteers who have had fundraising experience?
