### ISSUE TITLE
Health and Safety Policy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#827]

**Comment by PatReynolds** [comment]
First draft written.  @richpomfret and @DeniseColbert can you have a quick look before I circulate to Trustees and AB?

**Comment by DeniseColbert** [comment]
Have made some comments

**Comment by PatReynolds** [comment]
PDF made and now in Communities/Health and Safety.  Needs adding to the Volunteer Induction Manual.  I have added it to the Employment Manual, and shared with employees and project leaders.

**Comment by DeniseColbert** [comment]
All policies added to Induction handbook and volunteer policy documents
