### ISSUE TITLE
Recruit Fund-raising intern

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#83]
Meed to discuss balance of work between us + intern

**Comment by PatReynolds** [comment]
I've drafted a job description.  I've created a fundraising intern folder in the interns folder, and put it there.  Could you proof it,  and advertise, please.  I would guess a closing date of 3 weeks after you send it out.

**Comment by DeniseColbert** [comment]
Ad on Uni recruitment services and draft blog post done for promoting on SM etc

**Comment by PatReynolds** [comment]
Looking at the York bursaries ...  there are limits on weeks/hours.  Student max 10 weeks, max 16 hours per week... so we would be limited to 160 hours, term time.  Graduates 2 weeks / 70 hours.  I think for this internship, we should go for a student internship with the bursary

**Comment by DeniseColbert** [comment]
York are shortlisting today and will send to you today
