### ISSUE TITLE
Fundraising and Donations Policy (acceptance and refusal)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#830]

**Comment by PatReynolds** [comment]
Draft ready for proofing @Denise - be good to be ready to circulate by the end of the year

**Comment by DeniseColbert** [comment]
I'll do it today or tomorrow if you let me know where it is?

**Comment by PatReynolds** [comment]
Apologies - I have made a new folder called Policies in Governance / Important documents and put it there.  Needs to be on agenda for next Trustees meeting.

**Comment by DeniseColbert** [comment]
Proofed. Highlighted areas for discussion and made comments. Added Governance label as it needs putting in April agenda.
