### ISSUE TITLE
Create Donations communications plan (make actions)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#856]

**Comment by PatReynolds** [comment]
I've now added the GoCardless data - I divided the first payment equally among previous months.

**Comment by DeniseColbert** [comment]
Free Adobe stock images trial (30 day,) https://stock.adobe.com/uk/promo/firstmonthfree?promoid=QBWYPQTR&as_channel=adobe_com&as_campclass=brand&as_source=flash_download&as_campaign=uk_b_1000x463&as_content=housead_reader
