### ISSUE TITLE
Streamline donation - put giftaid on thankyou page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#866]
Also see #925

**Comment by PatReynolds** [comment]
I have change d the words a bit - https://docs.google.com/document/d/1H2UJviNSxiQjLu7OBM7gq1_c-6i6gUMxqR_LCtpA9RY/edit?usp=sharing 
Also added a Data protection section for the page.

**Comment by DeniseColbert** [comment]
Draft 1 updated with gift aid text, but can't 'do' data protection text (tickybox issues) - have requested permission to comment on doc to explain.

**Comment by DeniseColbert** [comment]
Done.
