### ISSUE TITLE
Create test server for FUG Website

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#867]
Using server on AWS - with AWS Grant (if funding available, after Glacier)

Needs #785 to see how much money is left

**Comment by richpomfret** [comment]
As part of this, we should also introduce version/source control and move the site onto Github. Then we can manage the site as we do with all of our projects. :)

**Comment by lemon-ukgen** [comment]
Just curious: what's the motivation for hosting this on AWS? It'll cost money, whereas keeping it on kit we already pay for will cost no money.

**Comment by richpomfret** [comment]
Lemon has now set up an Amazon instance for Wordpress (for the live site). Test/Staging server location tba. @lemon-ukgen any thoughts on the latter? We may wish to have another server review, considering we will also want to host FreeBMD2 and FreePROBATE in good time.

**Comment by lemon-ukgen** [comment]
I can set up another AWS server but perhaps it's worth waiting for the Craft -> WordPress migration to land first? /cc @arswright-alt-uk

**Comment by richpomfret** [comment]
Thanks @lemon-ukgen. @arswright-alt-uk when can we schedule this migration in for? :)

**Comment by arswright-alt-uk** [comment]
@lemon-ukgen Sorry for the delay in getting to this - was just following up with @richpomfret on Slack RE: FreeUKGen/FreeUKGenealogy/issues/38 and I'm presently limited on availability owing to another volunteer project; Google Tag Manager setup is highest priority (but would rely upon test server access) so if it'd be possible to clone the production AWS instance, that'd be my preference.

**Comment by lemon-ukgen** [comment]
Just to confirm: you're after another EC2 instance like `wp1`, with `test{2,3}.freeukgenealogy.org.uk` aimed at it?

**Comment by arswright-alt-uk** [comment]
@lemon-ukgen Yes - if the goal is to isolate testing from production, `test{2,3}` can both point to the same instance and I'll set up the separate databases/vhosts/repository checkouts accordingly.

**Comment by lemon-ukgen** [comment]
Righto. I'm travelling / conferencing this week so will do this coming weekend.

**Comment by richpomfret** [comment]
No worries, thanks @lemon-ukgen. :)

**Comment by arswright-alt-uk** [comment]
https://test2.freeukgenealogy.org.uk/ and https://test3.freeukgenealogy.org.uk/ live with username "test" / password "test" enforced to discourage search engine indexing.

**Comment by PatReynolds** [comment]
Great!  Works fine (as far as I've tested test3). Is the next step to implement wordpress on the test server (or is that wp I'm seeing???!)

**Comment by arswright-alt-uk** [comment]
@PatReynolds 

> Is the next step to implement wordpress on the test server (or is that wp I'm seeing???!)

Still Craft - working through issues as prioritized by @DeniseColbert (WordPress migration is 23/23 in prioritized Backlog queue at [Zenhub](https://app.zenhub.com/workspaces/freeukgenealogysite-5cfdeab6c34c1b37ca337cab/board?repos=57374638,176381240) w/11 new issues awaiting prioritization).

**Comment by PatReynolds** [comment]
Thanks, @arswright-alt-uk I will close this issue now - thank you for making this happen!
