### ISSUE TITLE
Recruit developer for WinFreeREG / app

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#871]

**Comment by richpomfret** [comment]
I've not had a chance to move forward on this yet. @DeniseColbert do we have an old template I can update?

**Comment by DeniseColbert** [comment]
No, we've not actively recruited for this role before. I emailed an empty RD earlier.

**Comment by DeniseColbert** [comment]
Placed on Social Coder

**Comment by DeniseColbert** [comment]
Adsense applicant Sai KV is interested in this role additionally to Adsense role. Will place her CV in drive.

**Comment by richpomfret** [comment]
The search continues. Have contacted a number of recent (and not so recent) potential tech volunteers for this.

**Comment by richpomfret** [comment]
One interview this week and hoping to have a few more for next.

**Comment by richpomfret** [comment]
Changing to complete (for now). Recruitment will remain an on-going task for tech volunteers.
