### ISSUE TITLE
Remove index.php element from back-end in Craft

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#874]
One of the main problems is that pages are sometimes rendered in more than one way. freeukgenealogy.org.uk also shows up as freeukgenealogy.org.uk/index.php (the same page, with a codeline exposed) which makes Google Crawlers think that we run a lot of duplicate pages. This undermines our SEO structure scores.

**Comment by DeniseColbert** [comment]
Is this possible @bev-fc ?

**Comment by bev-fc** [comment]
@DeniseColbert please take a look if the change matches the requirement

**Comment by DeniseColbert** [comment]
Will do Bev, thanks.

**Comment by DeniseColbert** [comment]
That has fixed it. Many thanks, Bev.
