### ISSUE TITLE
Analyse Feedback on Conference

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#881]

**Comment by PatReynolds** [comment]
Emailed some thoughts 17/9/2018 (two emails, one on questionarire, one on Audrey's suggestion.

**Comment by PatReynolds** [comment]
Another thought: ask (particularly those who didn't book, but everyone really) 'We plan to alternate between a London venue and a regional venue: where would you want us to go next (E.g. within 2 hours drive of Bristol, on West Coast Mainline, in East Anglia)?  Do you know a good venue (c. 75 lecture, space for lunch, space for a Trustee's meeting)?

**Comment by DeniseColbert** [comment]
Emailed to Pat 11/10

**Comment by DeniseColbert** [comment]
Updates made (charging for tickets), @PatReynolds to check

**Comment by PatReynolds** [comment]
Replied 6/11

**Comment by DeniseColbert** [comment]
- Add to newsletter
- Email to Eventbrite list
- Email to volunteers
- Put on social media

(with "You may receive more than one request to complete this feedback form; please only complete it once")

**Comment by DeniseColbert** [comment]
Analysis round 1 - DONE

Extracted answers that inform date and location of future confs into a doc, discussing with Pat
