### ISSUE TITLE
Recruit donations volunteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#896]

**Comment by DeniseColbert** [comment]
Sent RD to Pat 5/11

**Comment by DeniseColbert** [comment]
Placed on Do-It

**Comment by DeniseColbert** [comment]
WRote to Benevity applicant 19/11

**Comment by PatReynolds** [comment]
Denise to submit to Leicester Museums Jobsdesk

**Comment by DeniseColbert** [comment]
Sent to JobsDesk and ARch/GEM/MCG Mailing lists & scheduled for SM

**Comment by DeniseColbert** [comment]
Added to CharityJobs

**Comment by DeniseColbert** [comment]
Made suggestions 18/01

**Comment by DeniseColbert** [comment]
@PatReynolds to proof Duty of Care statement/policy (shared via email)

ALSO: do we need/ have Public Liability Insurance?  (if so, can you send me a copy please?)

**Comment by PatReynolds** [comment]
Anything more you need from me on this one?

**Comment by DeniseColbert** [comment]
Not for now, hopefully I'll be able to complete registration with this and there'll be no curveballs :D

**Comment by DeniseColbert** [comment]
Awaiting return of Llinos in September.
