### ISSUE TITLE
Create an Annual Easyfundraising Plan

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#898]

**Comment by PatReynolds** [comment]
Put links in the document - weekly breakdown.

**Comment by DeniseColbert** [comment]
Done! https://docs.google.com/document/d/1tIG3xHnT0Byw-3UIpoaGvxu62NaIyX_ZoB4I3LBaEXI/edit?usp=sharing

Some spaces for flexibility/ideas (welcome)

**Comment by PatReynolds** [comment]
Looks good! I've addded a couple in apparently August, April and May are good times to buy computers ...
