### ISSUE TITLE
Sign up for FSI

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#908]
Foundation for Social Improvement

Support for small charities, incl. fundraising, training, advice. Free or heavily subsidised

https://www.thefsi.org/

**Comment by DeniseColbert** [comment]
Denise to send Pat login details

**Comment by PatReynolds** [comment]
I think this can be closed - please do so, Denise, if it can.

**Comment by DeniseColbert** [comment]
I removed the item from the basket, but now can't see a way to add to basket! There's a new dashboard since registration was completed, and I'm not sure if there's a glitch with it. Have taken you off and will email support.

**Comment by DeniseColbert** [comment]
Sorted (will email). Closing.
