### ISSUE TITLE
Actions from Code of Fundraising Practice review

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#916]
Includes discussion points, actions for Pat, and actions for Denise

ACTIONS:

 - [x] Pat (Twitter) re 10.2

 - [x] Act on decision from Fundraising Regulator (if there is one) - 10.2 Fees on Fundraising Platforms

 - [x] Check (Pat to email all to check) legally required info is on all comms that explicitly or implicitly talks about money (inc donations, requests for used cartridges, orders to suppliers)  https://knowhow.ncvo.org.uk/how-to/how-to-make-sure-you-include-the-right-information-about-your-charity-on-official-documents has what to include - 9.1.6

- [x] Pat to update our GDPR assessment spreadsheet with matters raised by the Fundraising Regulator (and ICO, in due course, if there are any)
 - [x] Pat to contact ICO re 2 queries not answered by the Fundraising Regulator

 - [x] Check 3rd party donation systems are clear about fees  - Pat to ask Fundrasing Regulator about Paypal - does not mention fees. Kindlink is OK.

 - [X] Check they have security measure (verified by visa/ securecode)  Both do.

 - [x] Pat to Check meaning of 10.4.1 You must not send bulk emails from
a named person’s email account. with Fundraising regulator

 - [x] Add to our  privacy policy - must clearly and expressly indicate that all PayPal transactions are subject to the PayPal Privacy Policy, the Kindlink Privacy policy (etc.).. see also 3.5.9 on purposes

 - [x] Add notice about privacy to the FreeBMD 

 - [x] Add generic donations preamble to FUG

  - [x] Update FreeBMD with fees levied on Paypal  -  issue with Fundraising regulator

 - [x]  Check point size of GDPR consent (should be as large as name/address or specifying donation amount or 10pt where neither) Needed for new Wordpress site, for Marketing purpose

 - [x] Implement response to email to fundraising regulator sent 20 July 2021

- [x] Check fees levied on donation

 - [x] Update FUG website page with fees levied on donations  -  issue with Fundraising regulator

E2, U 10, S 8, C 7 - P27

**Comment by DeniseColbert** [comment]
@patreynolds Re. tickyboxes 1 & 2, are we concerned with section 7.5 of the Code? https://www.fundraisingregulator.org.uk/code/working-with-others/professional-fundraisers-commercial-participators-and-partners#fees-and-payment

**Comment by PatReynolds** [comment]
Used ICO contact form 13 Sep 2021

Send draft of declaration footer email to Denise 13 Sep 2021

**Comment by PatReynolds** [comment]
Updated GDPR spreadsheet with HMRC info on retention of Giftaid.

**Comment by DeniseColbert** [comment]
Double-check GoCardless in light of 10.2 (also PayPal via FB).

**Comment by DeniseColbert** [comment]
Go Cardless doesn't have fees info accessible from the form: https://pay.gocardless.com/flow/RE001GG6BA7XPCG1PZENBKJV8GMPYRVN

But the info is easily accessible on their website: https://gocardless.com/pricing/

**Comment by PatReynolds** [comment]
Responded to the reglator, question remaining on point 1 (is Paypal "A fundraising platform"?) 20 Sep 2021

**Comment by DeniseColbert** [comment]
Privacy info to be added to FreeBMD (already on FUG):

Find out how your data is used by our charity in our Privacy Notice [LINK below]. The third-party platform you choose below has information on their websites about how they use your data.

https://drive.google.com/file/d/10r_c-5d9DDces-OUX7D4UJJKGNIhu8sV/view?usp=sharing

**Comment by PatReynolds** [comment]
Maybe ask https://www.digitalcandle.org.uk/ about the issue with  getting anonymous emails delivered

**Comment by PatReynolds** [comment]
Request added to Trac for final element  #728 28 Oct 2021

**Comment by PatReynolds** [comment]
Submitted 12 Jan 2022

**Comment by PatReynolds** [comment]
Paid fee 13 Jan, so closing
