### ISSUE TITLE
Draft text for Legacy page(s)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#919]
See #462 for information

E8, U 6, S 8 C 6 - P28

**Comment by PatReynolds** [comment]
Leave your mark on history, draft 1 saved.
Need to add to agenda for Advisory board

**Comment by DeniseColbert** [comment]
Had a look, seems good for now. Added to AB agenda. Seem to remember there was something else to be added to that, but I forget what. Can you remember Pat?

**Comment by PatReynolds** [comment]
Can't see anythinge else fo agenda, but will sleep on it.
