### ISSUE TITLE
Investigate PayPal marketing solutions

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#922]
https://www.paypal.com/uk/webapps/mpp/paypal-marketing-solutions

E4 U3 S4 C6: P17

**Comment by PatReynolds** [comment]
Two components: buyer demographics, amounts, etc., and promotional messages to appear on our websites.

Would need to put tracking code on our websites.

The promotional messages (e.g. "longer to pay") don't seem relevant to donations (and a search failed to find anything mentioning 2PayPal marketing messages" AND 'donations'.

Data bout donors _might_ be useful, but cookie consent would be an issue, and therefore, I don't think worth it (at least at this point).

**Comment by PatReynolds** [comment]
@DeniseColbert any thoughts on this?  If not, please close.

**Comment by DeniseColbert** [comment]
I agree: if there were obvious promotional benefits we could place it as a story for the WP site, where cookie consent will be easier to manage. In the current absence of such, will close.
