### ISSUE TITLE
Blog post for RQG

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#923]

**Comment by DeniseColbert** [comment]
The Register of Qualified Genealogists (RQG) are looking at having a series of guest blogs on their website.  As part of the Communications Team I wondered if you (or someone) would be willing to write a blog about Free UK Gen – i.e. its history, why/how it got started, what it covers etc., especially as it is its 20th anniversary this year.

**Comment by PatReynolds** [comment]
Pat to add open data sentences

**Comment by PatReynolds** [comment]
Have done 12/11 -  also a bit more on plan for FreeCEN.  Sorry, forgot to put to 'commenting' mode!

**Comment by PatReynolds** [comment]
Pat to look at timeline document and Denise to add month transcribers started signing the agreement
