### ISSUE TITLE
Assets/files problem in Craft

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#924]
A bunch of image files was 'broken' (see below) so I deleted them and tried to re-upload. This was the error message:

![2018-10-10](https://user-images.githubusercontent.com/19173257/46734793-2bf89800-cc8c-11e8-9e91-f23d0a2fcb17.png)

Broken jpg:

![image](https://user-images.githubusercontent.com/19173257/46735012-ce188000-cc8c-11e8-98b5-5ba972bb7178.png)

**Comment by DeniseColbert** [comment]
Would you be able to take a look please, Bev?

**Comment by bev-fc** [comment]
I tried to upload an image (left it in Gift-Aid) and it worked. Which page is it for your second attachment (Broken jpg)?

**Comment by DeniseColbert** [comment]
It was bank transfer and cheques, under Donate but I've since edited the page and removed the broken image. Maybe the images on my computer were somehow broken too?

**Comment by bev-fc** [comment]
Do you mean everything is okay now or you still get error message when you upload the image?

**Comment by DeniseColbert** [comment]
No, uploading the images still gets me the error message. I found some broken images on another page, if you want to take a look there too:

https://www.freeukgenealogy.org.uk/admin/entries/pages/1384-about-the-images-we-use

**Comment by DeniseColbert** [comment]
![image](https://user-images.githubusercontent.com/19173257/48001247-e51d8700-e0ff-11e8-8d10-c6be312d1083.png)

**Comment by bev-fc** [comment]
Can you send me a copy of your image file so I can give a try?

**Comment by DeniseColbert** [comment]
I'll share the folder with the Gift Aid images with you, look out for an email notification :)

**Comment by arswright-alt-uk** [comment]
Now tracked at [FreeUKGen/FreeUKGenealogy Issue #18](https://github.com/FreeUKGen/FreeUKGenealogy/issues/18).
