### ISSUE TITLE
Order business cards & flyers

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#926]
First draft, improvements required:
https://drive.google.com/open?id=1VSSdg4nRLbzapwawyoGOshNT-wiXAr8Z

Needs #983

**Comment by DeniseColbert** [comment]
Second draft:
https://drive.google.com/open?id=1XnWcdwt2LhNUx0h04YlZZ9dwEu6XV_Wd

Sun removed, tree and logo enlarged

**Comment by PatReynolds** [comment]
Good to go, thank you!
