### ISSUE TITLE
Managing stress / mh at work

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#928]
Find training

E5 U10 S6 C7: P28

**Comment by PatReynolds** [comment]
Draft shared with Denise and Rich 4/12/2018

**Comment by DeniseColbert** [comment]
Is this the Generic Coords info doc? If so, I've made my pass. If not, please resend as I can't find anything else.

**Comment by PatReynolds** [comment]
Yes, Generic Coords Info doc.

Separate issue: Has the Stress and Work policy been added to Volunteer Handbook and Employee Handbook?

**Comment by DeniseColbert** [comment]
Added to Volunteer Handbook, awaiting confirmation of which Employee document is current

**Comment by richpomfret** [comment]
Reviewed and looks fine to me. We can always add in more content if and when appropriate.

**Comment by PatReynolds** [comment]
@Denise, can this now be closed?

**Comment by DeniseColbert** [comment]
Yes, it's in both.
