### ISSUE TITLE
Notes for course leaders / lecturers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#946]
E3 U3 S5 C6: P19

**Comment by PatReynolds** [comment]
First draft for feedback .... https://docs.google.com/document/d/1BvQ5gmtAk1O9bUB_s630Mtg_ATapdqCAN_1ndsPArhI/edit?usp=sharing

**Comment by DeniseColbert** [comment]
Added some formatting and comments. I think (a version of?) this would be brilliant to offer as a free download on our website, too... Would be nice to make it into a branded PDF.

**Comment by DeniseColbert** [comment]
Sarah has shared my details with Area Coordinators

**Comment by DeniseColbert** [comment]
Added our FB groups by name
