### ISSUE TITLE
Review what's stored on Glacier

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/Coordination#948]
New task to review what's backed up on Glacier and to check in with other developers for suggestions on what we might add e.g. related to images, open data etc.

**Comment by richpomfret** [comment]
This is complete for now. We may wish to put it back into the backlog and check again in 3 months. Images are yet to be added (Lemon is scheduled to do this but it is a significant upload).

**Comment by richpomfret** [comment]
@PatReynolds can I ask why this has been moved to high priority? I don't see any urgent need to for another review in terms of what's on Glacier. Unless it is linked to our need for an alternative backup solution of 'last resort'?

**Comment by PatReynolds** [comment]
We now use Backblaze so closing.
