### ISSUE TITLE
Accessibility Statement FR #933

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#95]

**Comment by PatReynolds** [comment]
one for each website.  Place on freeukgen next to blog and twitter on front page, plus link in bullet points in Constitution and Policies

**Comment by PatReynolds** [comment]
also hyperlink from 'accessible to all' in first paragraph of front page (which I am writing at the moment).

**Comment by DeniseColbert** [comment]
Sent truncated 'temp' statement to group

**Comment by DeniseColbert** [comment]
We need to have a look at the page Alison created - is it on the test environment?

**Comment by DeniseColbert** [comment]
http://www.freereg.org.uk/cms/about/accessibility-statement not linked to as yet (I think)

**Comment by DeniseColbert** [comment]
From Alison:  "I guess we need a brief para on the About page that includes a link? Was thinking along the lines of: "You will notice some changes to the site as we seek to improve access to FreeReg, especially for mobile phone users and for visitors with a range of disabilities."

Eventually there will be a link in the footer -- I think that is the intention."

**Comment by DeniseColbert** [comment]
Done, and done again 11/1/17
