### ISSUE TITLE
Draft new version of 'other ways to support..'

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#959]
Place buttons to subpages

Needs #962 
Needs #994

**Comment by DeniseColbert** [comment]
Move to child of Donate page?

**Comment by DeniseColbert** [comment]
https://www.freeukgenealogy.org.uk/about/pages/other-ways-to-help?token=9735uczgIRKxpE0LYbpIok1dEkd1AILJ

**Comment by PatReynolds** [comment]
Pat to proof

**Comment by PatReynolds** [comment]
Good to go (for now) but also:

Separate story - I think workplace giving also needs to be in cash. Maybe text on that page needs tweeting to say that workplace giving can mean your company donates cash when you donate time, and / or matches your giving? And the buttons may need to be expanded so the cash page one says 'Workplace Giving - employer donates when you donate' and the 'other ways one' says 'Workplace Giving - employer donates when you volunteer'

**Comment by DeniseColbert** [comment]
New story made, this one's done
