### ISSUE TITLE
Address spacing in image block in Craft

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#960]
Column 1/3, add two images to block, images are both left aligned. Toggling the alignment button to 'center' doesn't work. There seems to be no way of spacing them across the 1/3 block.

![image](https://user-images.githubusercontent.com/19173257/47950200-b27c5e80-df46-11e8-89b1-087bec9ac197.png)
![image](https://user-images.githubusercontent.com/19173257/47950229-2880c580-df47-11e8-90f5-200b7d0b367f.png)

If a third image is added, they fit into the block and look well-spaced.

![image](https://user-images.githubusercontent.com/19173257/47950219-f1121900-df46-11e8-8ffb-a32e96772177.png)

(one image can be centered in a block by using these settings
![image](https://user-images.githubusercontent.com/19173257/47950253-86ada880-df47-11e8-9f24-e43358e61f8f.png)

**Comment by arswright-alt-uk** [comment]
Now tracked at [FreeUKGen/FreeUKGenealogy Issue #17](https://github.com/FreeUKGen/FreeUKGenealogy/issues/17).
