### ISSUE TITLE
Contact page (was Other ways to support our work - Subpages)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#962]
Pat to check subpages (emailed 3/11) and also check draft Contact page, for making live.

Once live, do story #959

**Comment by PatReynolds** [comment]
Subpages now live.

Contact page, text "Visit our Social Media page to find how our community can." needs finishing ... "help you with your family history research".  And perhaps before that "We have some links and advice you may find helpful on our Links pages".

Which is getting to be a lot of text for a 'please don't contact us' alert box ...

So maybe .. current alert box, but a second box (not as bright red - perhaps just a red border:? With a title 'Do you need help finding your family?' and the text bits about the Links page and facebook groups?

**Comment by DeniseColbert** [comment]
Shared mock0up 6/11

**Comment by DeniseColbert** [comment]
FH Help page done, awaiting Specialist Links pages finishing for buttons to be added.

Guest post page done.

**Comment by PatReynolds** [comment]
Pat to proof guest post page.

**Comment by PatReynolds** [comment]
Denise to make link for existing links page.  New story on specialist links pages to be made.

**Comment by DeniseColbert** [comment]
Done
