### ISSUE TITLE
Add 'Bug testing' call to action?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#973]
Provide a 'how to test bugs for FreeUKGen websites with links to waffle lablelled 'bug' and 'good first issue'? E.g. https://waffle.io/freeukgen/freecenmigration?label=Good%20First%20Issue,bug Or use a 'bug testing needed' label so doesn't get confused with issues further down the resolution trail???

**Comment by PatReynolds** [comment]
Agreed - could be any testing that does not need log-in.  E.g. new feature.

**Comment by richpomfret** [comment]
Great. Shall now close this.

**Comment by richpomfret** [comment]
Sounds good to me. I've resolved (for most part accepted) all of the comments, so I think we might be good to roll this out somewhere. @DeniseColbert does it look ok to you?

**Comment by DeniseColbert** [comment]
It looks fine (fixed one small spacing issue for aesthetics) to go out. WHere are we putting it?

**Comment by richpomfret** [comment]
@DeniseColbert to mae the page on the FUG site, then pass it back to me to add onto Github.

**Comment by DeniseColbert** [comment]
https://www.freeukgenealogy.org.uk/admin/entries/pages/2672-how-to-test-issues
(need to be logged into Craft)

**Comment by richpomfret** [comment]
Would check if I had Crafty access! It would appear I do not. Do you have admin permission to add users?

**Comment by DeniseColbert** [comment]
You do have access, last logged in 23rd Jan :D Let me know if you need me to reset your password from Craft.

**Comment by richpomfret** [comment]
Looks good to me - we might wish to put a link in to the 'contact' form but happy with it either way. Assigned back to @DeniseColbert.

**Comment by DeniseColbert** [comment]
@richpomfret I've made it live, but can add in link to Contact later. Can you clarify it's the page with the form you're suggesting? They come to me; I'm not sure I'd be best placed to respond but can pass queries on to you, or we could put your email address instead?

**Comment by richpomfret** [comment]
@DeniseColbert looks good to me! :) I would add in a 'contact our technical project manager' and include my email if they want to get involved with the coding side of things. Otherwise the form itself should be the tech volunteer questionnaire, in which case it should probably go to the recruitment email address so we all see them?

**Comment by PatReynolds** [comment]
Rich says: @Denise, please make these changes.

**Comment by DeniseColbert** [comment]
Ok, upon going to do this, I see that I've linked to the Tech vol page for people who want to get involved with the coding side. As both the form and your email are contained on *that* page, I don't think we need to put them here too.

Re. applications coming to recruit@ email: AFAIR email alerts go to the Owner of the form (you, for Tech Vol form, me for Foundation Vol form). If you want me to see the alert that someone has applied, you would need to set up a forwarding filter from your email I think.
