### ISSUE TITLE
Communicate release notes

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/Coordination#976]
We now include release notes for each sprint. Consider how best to communicate these e.g. include as part of FR/FC newsletters? Or add onto blog or on the site somewhere?

**Comment by PatReynolds** [comment]
Now on Github - need to find a way to communicate to users

**Comment by richpomfret** [comment]
These are now distributed over on Slack and are available in Github. For consideration - we may wish to include a link or auto-update this information on the actual site somewhere, however we need to discuss where.

**Comment by richpomfret** [comment]
Discussed putting a link on the About page (for each project) with 'What's new' or 'Release notes' and link to a document with changes, or to the Gitub folder.

**Comment by richpomfret** [comment]
Created issue #55 on the systemwide board to cover this. Now closing here.
