### ISSUE TITLE
Free UK Gen Timeline design

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#985]

**Comment by DeniseColbert** [comment]
Pat to check doc: https://docs.google.com/document/d/1xqQfVEFO6idXnTfutAAylTScOHAC4PowY8A1SPSvzME/edit#heading=h.cplkytho4zny

**Comment by PatReynolds** [comment]
Done - made a couple of suggestions

**Comment by DeniseColbert** [comment]
![timeline](https://user-images.githubusercontent.com/19173257/49153063-8917de00-f30c-11e8-8fe6-c606694d3957.jpg)

Is this OK Pat?

**Comment by PatReynolds** [comment]
Yes, that's fine.

**Comment by DeniseColbert** [comment]
Sent to Anne - Done
