### ISSUE TITLE
Move consent banners and enlarge them on FreeBMD

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#987]
In order to
a) force people to make a choice, and
b) not obscure advertising:
make all cookie consent banners larger, and at the bottom rather than the top of the screen (i.e. create this story on all websites' boards)

E4 U3 S8 C8

needs freeukgen/freecenmigration#513
needs freeukgen/myopicvicar#1787
needs Trac #670

**Comment by PatReynolds** [comment]
I'm not able to find on Trac - please add number, or add to Trac

**Comment by richpomfret** [comment]
Added and added.

**Comment by richpomfret** [comment]
Now complete on FR/FC2 and FC (ish - needs a colour change).

**Comment by richpomfret** [comment]
All done apart frmo FreeBMD. Will request that @smrr723 does this as one of his first tasks in FreeBMD (when he returns from holiday next week).

**Comment by richpomfret** [comment]
Asked Barrie to take a look at this. If he doesn't wish to pick this up then we might need to put it on hold in light of FreeBMD2 development (and the issues we faced getting the new test/dev facilities up and running on FreeBMD1).
