### ISSUE TITLE
Send out FreeBMD2 survey

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#993]
Coords first?

**Comment by PatReynolds** [comment]
No subscribed to coords - have asked Allan.

**Comment by PatReynolds** [comment]
Asked Allan if ther was any feedback 26/11

**Comment by PatReynolds** [comment]
Sent to syndicate coords for check/enhance 3/12, with plan to correct/enhance and send out 18/12/2018

**Comment by DeniseColbert** [comment]
Awaiting feedback on addition to survey, and title.
