### ISSUE TITLE
Fix spacing in button code

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#994]
e.g. 
![image](https://user-images.githubusercontent.com/19173257/48567750-c1272600-e8f5-11e8-8a79-5792ee956aca.png)

https://www.freeukgenealogy.org.uk/admin/entries/pages/1215-other-ways-to-help/drafts/115

**Comment by arswright-alt-uk** [comment]
Now tracked at [FreeUKGen/FreeUKGenealogy Issue #12](https://github.com/FreeUKGen/FreeUKGenealogy/issues/12).
